#include <datamunge/algorithms/search_batch.hpp>
#include <algorithm>
#include <functional>
#include <queue>
#include <stdexcept>
namespace datamunge::algorithms {
namespace {
using Adj=std::vector<std::vector<std::size_t>>;
Adj graph(std::size_t n,const std::vector<std::pair<std::size_t,std::size_t>>&e,bool directed){Adj a(n);for(auto[u,v]:e){if(u>=n||v>=n)throw std::invalid_argument("search: endpoint out of range");a[u].push_back(v);if(!directed)a[v].push_back(u);}return a;}
void terminals(std::size_t n,std::size_t s,std::size_t g){if(s>=n||g>=n)throw std::invalid_argument("search: terminal out of range");}
std::vector<std::size_t> path(std::size_t n,std::size_t s,std::size_t g,const std::vector<std::size_t>&p){if(s==g)return{s};if(p[g]==n)return{};std::vector<std::size_t>r;for(auto v=g;;v=p[v]){r.push_back(v);if(v==s)break;}std::reverse(r.begin(),r.end());return r;}
}
UnweightedSearchResult breadth_first_search(std::size_t n,const std::vector<std::pair<std::size_t,std::size_t>>&e,std::size_t s,std::size_t goal,bool directed){terminals(n,s,goal);auto a=graph(n,e,directed);std::vector<std::size_t>p(n,n);std::vector<bool>seen(n);std::queue<std::size_t>q;q.push(s);seen[s]=true;UnweightedSearchResult r;while(!q.empty()){auto u=q.front();q.pop();r.order.push_back(u);if(u==goal)break;for(auto v:a[u])if(!seen[v]){seen[v]=true;p[v]=u;q.push(v);}}r.path=path(n,s,goal,p);r.found=!r.path.empty();return r;}
UnweightedSearchResult backtracking_search(std::size_t n,const std::vector<std::pair<std::size_t,std::size_t>>&e,std::size_t s,std::size_t goal,bool directed){terminals(n,s,goal);auto a=graph(n,e,directed);std::vector<bool>on(n);UnweightedSearchResult r;std::function<bool(std::size_t)>dfs=[&](auto u){r.order.push_back(u);r.path.push_back(u);if(u==goal)return true;on[u]=true;for(auto v:a[u])if(!on[v]&&dfs(v))return true;on[u]=false;r.path.pop_back();return false;};r.found=dfs(s);if(!r.found)r.path.clear();return r;}
UnweightedSearchResult best_first_search(std::size_t n,const std::vector<std::pair<std::size_t,std::size_t>>&e,std::size_t s,std::size_t goal,const std::vector<double>&h,bool directed){terminals(n,s,goal);if(h.size()!=n)throw std::invalid_argument("best_first: heuristic size");auto a=graph(n,e,directed);using Q=std::pair<double,std::size_t>;std::priority_queue<Q,std::vector<Q>,std::greater<Q>>q;std::vector<bool>seen(n);std::vector<std::size_t>p(n,n);q.push({h[s],s});seen[s]=true;UnweightedSearchResult r;while(!q.empty()){auto[_,u]=q.top();q.pop();r.order.push_back(u);if(u==goal)break;for(auto v:a[u])if(!seen[v]){seen[v]=true;p[v]=u;q.push({h[v],v});}}r.path=path(n,s,goal,p);r.found=!r.path.empty();return r;}
UnweightedSearchResult beam_search(std::size_t n,const std::vector<std::pair<std::size_t,std::size_t>>&e,std::size_t s,std::size_t goal,const std::vector<double>&h,std::size_t width,bool directed){terminals(n,s,goal);if(h.size()!=n||width==0)throw std::invalid_argument("beam_search: invalid parameter");auto a=graph(n,e,directed);std::vector<std::vector<std::size_t>>beam{{s}};UnweightedSearchResult r;while(!beam.empty()){std::vector<std::vector<std::size_t>>next;for(auto p:beam){auto u=p.back();r.order.push_back(u);if(u==goal){r.path=p;r.found=true;return r;}for(auto v:a[u])if(std::find(p.begin(),p.end(),v)==p.end()){auto x=p;x.push_back(v);next.push_back(std::move(x));}}std::sort(next.begin(),next.end(),[&](auto&a,auto&b){return h[a.back()]<h[b.back()];});if(next.size()>width)next.resize(width);beam.swap(next);}return r;}
UnweightedSearchResult beam_stack_search(std::size_t n,const std::vector<std::pair<std::size_t,std::size_t>>&e,std::size_t s,std::size_t goal,const std::vector<double>&h,std::size_t width,bool directed){terminals(n,s,goal);if(h.size()!=n||width==0)throw std::invalid_argument("beam_stack: invalid parameter");auto a=graph(n,e,directed);using P=std::vector<std::size_t>;std::vector<P>frontier{{s}},deferred;UnweightedSearchResult r;while(!frontier.empty()||!deferred.empty()){if(frontier.empty()){frontier.push_back(std::move(deferred.back()));deferred.pop_back();}std::vector<P>next;for(auto p:frontier){auto u=p.back();r.order.push_back(u);if(u==goal){r.path=p;r.found=true;return r;}for(auto v:a[u])if(std::find(p.begin(),p.end(),v)==p.end()){auto x=p;x.push_back(v);next.push_back(std::move(x));}}std::sort(next.begin(),next.end(),[&](auto&a,auto&b){return h[a.back()]<h[b.back()];});while(next.size()>width){deferred.push_back(std::move(next.back()));next.pop_back();}frontier.swap(next);}return r;}
UnweightedSearchResult bidirectional_search(std::size_t n,const std::vector<std::pair<std::size_t,std::size_t>>&e,std::size_t s,std::size_t goal){terminals(n,s,goal);auto a=graph(n,e,false);std::vector<std::size_t>ps(n,n),pg(n,n);std::vector<int>side(n);std::queue<std::size_t>q;q.push(s);side[s]=1;if(s!=goal){q.push(goal);side[goal]=2;}UnweightedSearchResult r;std::size_t meet=s;while(!q.empty()){auto u=q.front();q.pop();r.order.push_back(u);for(auto v:a[u])if(!side[v]){side[v]=side[u];(side[u]==1?ps:pg)[v]=u;q.push(v);}else if(side[v]!=side[u]){meet=side[u]==1?u:v;auto other=side[u]==1?v:u;ps[other]=meet;meet=other;q={};break;}}if(side[goal]==1||s==goal){r.path=path(n,s,goal,ps);}else if(meet<n&&side[meet]){auto left=path(n,s,meet,ps);if(!left.empty()){r.path=left;auto v=pg[meet];while(v<n){r.path.push_back(v);if(v==goal)break;v=pg[v];}}}r.found=!r.path.empty();return r;}
}
