#include <datamunge/algorithms/tour_search.hpp>
#include <algorithm>
#include <cmath>
#include <limits>
#include <numeric>
#include <queue>
#include <stdexcept>
namespace datamunge::algorithms {
namespace {
void matrix_ok(const std::vector<std::vector<double>>&d){for(auto&r:d)if(r.size()!=d.size())throw std::invalid_argument("TSP: distance matrix must be square");for(std::size_t i=0;i<d.size();++i)for(std::size_t j=0;j<d.size();++j)if(d[i][j]<0||!std::isfinite(d[i][j]))throw std::invalid_argument("TSP: invalid distance");}
double length(const std::vector<std::size_t>&t,const std::vector<std::vector<double>>&d){double x=0;for(std::size_t i=1;i<t.size();++i)x+=d[t[i-1]][t[i]];return x;}
struct D{std::vector<std::size_t>p;explicit D(std::size_t n):p(n){std::iota(p.begin(),p.end(),0);}std::size_t f(std::size_t x){return p[x]==x?x:p[x]=f(p[x]);}bool j(std::size_t a,std::size_t b){a=f(a);b=f(b);if(a==b)return false;p[a]=b;return true;}};
}
TourResult nearest_neighbor_tsp(const std::vector<std::vector<double>>&d,std::size_t s){matrix_ok(d);if(d.empty())return{};if(s>=d.size())throw std::invalid_argument("nearest_neighbor_tsp: start");std::vector<bool>used(d.size());TourResult r;r.tour={s};used[s]=true;while(r.tour.size()<d.size()){auto u=r.tour.back(),best=d.size();for(std::size_t v=0;v<d.size();++v)if(!used[v]&&(best==d.size()||d[u][v]<d[u][best]))best=v;used[best]=true;r.tour.push_back(best);}r.tour.push_back(s);r.cost=length(r.tour,d);return r;}
TourResult christofides_tsp(const std::vector<std::vector<double>>&d,std::size_t s){matrix_ok(d);const auto n=d.size();if(!n)return{};if(s>=n)throw std::invalid_argument("christofides_tsp: start");
 struct E{std::size_t u,v;double w;};std::vector<E>all;for(std::size_t i=0;i<n;++i)for(std::size_t j=i+1;j<n;++j)all.push_back({i,j,d[i][j]});std::sort(all.begin(),all.end(),[](auto&a,auto&b){return a.w<b.w;});D ds(n);std::vector<E>multi;std::vector<int>degree(n);for(auto e:all)if(ds.j(e.u,e.v)){multi.push_back(e);++degree[e.u];++degree[e.v];}
 std::vector<std::size_t>odd;for(std::size_t i=0;i<n;++i)if(degree[i]%2)odd.push_back(i);if(odd.size()>22)throw std::invalid_argument("christofides_tsp: too many odd vertices for exact matching");
 const std::size_t full=(1ULL<<odd.size())-1;std::vector<double>dp(full+1,std::numeric_limits<double>::infinity());std::vector<std::pair<int,int>>choice(full+1,{-1,-1});dp[0]=0;for(std::size_t mask=1;mask<=full;++mask){int i=__builtin_ctzll(mask);for(std::size_t j=i+1;j<odd.size();++j)if(mask&(1ULL<<j)){auto rest=mask^(1ULL<<i)^(1ULL<<j);double x=dp[rest]+d[odd[i]][odd[j]];if(x<dp[mask]){dp[mask]=x;choice[mask]={i,(int)j};}}}for(auto mask=full;mask;){auto[i,j]=choice[mask];multi.push_back({odd[i],odd[j],d[odd[i]][odd[j]]});mask^=(1ULL<<i)|(1ULL<<j);}
 std::vector<std::vector<std::pair<std::size_t,std::size_t>>>a(n);for(std::size_t i=0;i<multi.size();++i){a[multi[i].u].push_back({multi[i].v,i});a[multi[i].v].push_back({multi[i].u,i});}std::vector<bool>used_edge(multi.size());std::vector<std::size_t>stack{s},circuit;while(!stack.empty()){auto u=stack.back();while(!a[u].empty()&&used_edge[a[u].back().second])a[u].pop_back();if(a[u].empty()){circuit.push_back(u);stack.pop_back();}else{auto[v,i]=a[u].back();a[u].pop_back();used_edge[i]=true;stack.push_back(v);}}
 std::reverse(circuit.begin(),circuit.end());std::vector<bool>seen(n);TourResult r;for(auto v:circuit)if(!seen[v]){seen[v]=true;r.tour.push_back(v);}r.tour.push_back(r.tour.front());r.cost=length(r.tour,d);return r;}
VehicleRoutes clarke_wright_savings(const std::vector<std::pair<double,double>>&p,const std::vector<double>&dem,double cap,std::size_t depot){if(p.size()!=dem.size()||depot>=p.size()||cap<=0)throw std::invalid_argument("clarke_wright: invalid input");auto dist=[&](auto i,auto j){return std::hypot(p[i].first-p[j].first,p[i].second-p[j].second);};std::vector<std::vector<std::size_t>>r;std::vector<double>load;for(std::size_t i=0;i<p.size();++i)if(i!=depot){if(dem[i]>cap)throw std::invalid_argument("clarke_wright: demand exceeds capacity");r.push_back({i});load.push_back(dem[i]);}
 struct S{std::size_t i,j;double v;};std::vector<S>s;for(std::size_t i=0;i<p.size();++i)for(std::size_t j=i+1;j<p.size();++j)if(i!=depot&&j!=depot)s.push_back({i,j,dist(depot,i)+dist(depot,j)-dist(i,j)});std::sort(s.begin(),s.end(),[](auto&a,auto&b){return a.v>b.v;});
 for(auto x:s){std::size_t A=r.size(),B=r.size();for(std::size_t k=0;k<r.size();++k){if(!r[k].empty()&&(r[k].front()==x.i||r[k].back()==x.i))A=k;if(!r[k].empty()&&(r[k].front()==x.j||r[k].back()==x.j))B=k;}if(A==B||A==r.size()||B==r.size()||load[A]+load[B]>cap)continue;if(r[A].front()==x.i)std::reverse(r[A].begin(),r[A].end());if(r[B].back()==x.j)std::reverse(r[B].begin(),r[B].end());r[A].insert(r[A].end(),r[B].begin(),r[B].end());load[A]+=load[B];r[B].clear();}
 VehicleRoutes out;for(auto&x:r)if(!x.empty()){x.insert(x.begin(),depot);x.push_back(depot);for(std::size_t i=1;i<x.size();++i)out.total_distance+=dist(x[i-1],x[i]);out.routes.push_back(x);}return out;}
std::vector<std::pair<int,int>> warnsdorff_knight_tour(int R,int C,int sr,int sc){if(R<=0||C<=0||sr<0||sr>=R||sc<0||sc>=C)throw std::invalid_argument("warnsdorff: invalid board");const int dr[]={2,2,1,1,-1,-1,-2,-2},dc[]={1,-1,2,-2,2,-2,1,-1};std::vector<std::vector<bool>>seen(R,std::vector<bool>(C));std::vector<std::pair<int,int>>path{{sr,sc}};seen[sr][sc]=true;while(path.size()<static_cast<std::size_t>(R*C)){auto[r,c]=path.back();std::tuple<int,int,int>best{99,-1,-1};for(int k=0;k<8;++k){int nr=r+dr[k],nc=c+dc[k];if(nr<0||nr>=R||nc<0||nc>=C||seen[nr][nc])continue;int degree=0;for(int z=0;z<8;++z){int x=nr+dr[z],y=nc+dc[z];if(x>=0&&x<R&&y>=0&&y<C&&!seen[x][y])++degree;}best=std::min(best,{degree,nr,nc});}auto[d,nr,nc]=best;if(nr<0)return{};seen[nr][nc]=true;path.push_back({nr,nc});}return path;}
static SearchResult search(std::size_t n,const std::vector<std::tuple<std::size_t,std::size_t,double>>&edges,std::size_t start,const std::vector<bool>&goal,const std::vector<double>&h){if(start>=n||goal.size()!=n||h.size()!=n)throw std::invalid_argument("informed search: invalid input");std::vector<std::vector<std::pair<std::size_t,double>>>a(n);for(auto[u,v,w]:edges){if(u>=n||v>=n||w<0)throw std::invalid_argument("informed search: invalid edge");a[u].push_back({v,w});}std::vector<double>g(n,std::numeric_limits<double>::infinity());std::vector<std::size_t>pre(n,n);using Q=std::pair<double,std::size_t>;std::priority_queue<Q,std::vector<Q>,std::greater<Q>>q;g[start]=0;q.push({h[start],start});SearchResult r;while(!q.empty()){auto[f,u]=q.top();q.pop();if(f!=g[u]+h[u])continue;++r.expanded;if(goal[u]){r.found=true;r.cost=g[u];for(auto v=u;v<n;v=pre[v])r.path.push_back(v);std::reverse(r.path.begin(),r.path.end());return r;}for(auto[v,w]:a[u])if(g[u]+w<g[v]){g[v]=g[u]+w;pre[v]=u;q.push({g[v]+h[v],v});}}return r;}
SearchResult a_star_search(std::size_t n,const std::vector<std::tuple<std::size_t,std::size_t,double>>&e,std::size_t s,std::size_t goal,const std::vector<double>&h){std::vector<bool>g(n);if(goal>=n)throw std::invalid_argument("a_star: goal");g[goal]=true;return search(n,e,s,g,h);}
SearchResult b_star_search(std::size_t n,const std::vector<std::tuple<std::size_t,std::size_t,double>>&e,std::size_t s,const std::vector<std::size_t>&goals,const std::vector<double>&h){if(goals.empty())throw std::invalid_argument("b_star: no goals");std::vector<bool>g(n);for(auto x:goals){if(x>=n)throw std::invalid_argument("b_star: goal");g[x]=true;}return search(n,e,s,g,h);}
}
