(use-modules (datamunge))

(define (rosenbrock-dual x0 x1)
  (let* ((a (Dual-subtract (new-Dual 1.0 0.0) x0))
         (b (Dual-subtract x1 (Dual-multiply x0 x0))))
    (Dual-add (Dual-multiply a a) (Dual-multiply-scalar (Dual-multiply b b) 100.0))))

(define (rosenbrock-value x0 x1)
  (let* ((a (- 1.0 x0))
         (b (- x1 (* x0 x0))))
    (+ (* a a) (* 100.0 b b))))

(define (rosenbrock-hyperdual x0 x1)
  (let* ((a (HyperDual-subtract (new-HyperDual 1.0 0.0 0.0 0.0) x0))
         (b (HyperDual-subtract x1 (HyperDual-multiply x0 x0))))
    (HyperDual-add (HyperDual-multiply a a) (HyperDual-multiply-scalar (HyperDual-multiply b b) 100.0))))

(format #t "=================== Forward mode: scalar derivative ===================\n")
(define x0 (new-Dual 2.0 1.0))
(define f (Dual-subtract (Dual-multiply (Dual-multiply x0 x0) x0) (Dual-multiply-scalar x0 2.0)))
(format #t "f(x) = x^3 - 2x, f'(2) = ~a (exact: 10)\n" (Dual-derivative f))

(format #t "\n=================== Reverse mode: build a graph by hand ===================\n")
(define tape (new-Tape))
(define a (new-Var tape 2.0))
(define b (new-Var tape 3.0))
(define y (Var-add (Var-multiply a b) (Var-sin a)))
(format #t "y = a*b + sin(a) at a=2, b=3 -> y = ~a\n" (Var-value y))
(define adjoint (Tape-backward tape y))
(format #t "dy/da = ~a (exact: b + cos(a))\n" (vector-ref adjoint (Var-index a)))
(format #t "dy/db = ~a (exact: a)\n" (vector-ref adjoint (Var-index b)))

(format #t "\n=================== Forward vs reverse mode agree on the Rosenbrock function ===================\n")
(define px 0.0)
(define py 0.0)

(define gx (Dual-derivative (rosenbrock-dual (new-Dual px 1.0) (new-Dual py 0.0))))
(define gy (Dual-derivative (rosenbrock-dual (new-Dual px 0.0) (new-Dual py 1.0))))

(define tape2 (new-Tape))
(define vx (new-Var tape2 px))
(define vy (new-Var tape2 py))
(define va (Var-subtract (new-Var tape2 1.0) vx))
(define vb (Var-subtract vy (Var-multiply vx vx)))
(define vf (Var-add (Var-multiply va va) (Var-multiply-scalar (Var-multiply vb vb) 100.0)))
(define grad-rev (Tape-backward tape2 vf))

(format #t "f(0,0) = ~a\n" (rosenbrock-value px py))
(format #t "gradient (forward mode): [~a, ~a]\n" gx gy)
(format #t "gradient (reverse mode): [~a, ~a]\n" (vector-ref grad-rev (Var-index vx)) (vector-ref grad-rev (Var-index vy)))

(format #t "\n=================== Jacobian of a vector-valued function ===================\n")
(define vx-val 2.0)
(define vy-val 3.0)

(define jac (make-vector 6 0.0))
(define (jac-set! row col val) (vector-set! jac (+ (* row 2) col) val))
(define (jac-ref row col) (vector-ref jac (+ (* row 2) col)))
(for-each
  (lambda (c)
    (let* ((col (car c)) (seed-x (cadr c)) (seed-y (caddr c))
           (ox (Dual-multiply (new-Dual vx-val seed-x) (new-Dual vx-val seed-x)))
           (oy (Dual-multiply (new-Dual vx-val seed-x) (new-Dual vy-val seed-y)))
           (oz (Dual-multiply (Dual-multiply (new-Dual vy-val seed-y) (new-Dual vy-val seed-y)) (new-Dual vy-val seed-y))))
      (jac-set! 0 col (Dual-derivative ox))
      (jac-set! 1 col (Dual-derivative oy))
      (jac-set! 2 col (Dual-derivative oz))))
  (list (list 0 1.0 0.0) (list 1 0.0 1.0)))
(format #t "f(x,y) = [x^2, xy, y^3] at (2,3), Jacobian:\n")
(do ((row 0 (+ row 1))) ((= row 3))
  (format #t "  [~a, ~a]\n" (jac-ref row 0) (jac-ref row 1)))

(format #t "\n=================== Hessian via second-order forward mode (HyperDual) ===================\n")
(define mx 1.0)
(define my 1.0)

(define seeds (list (list 1.0 0.0) (list 0.0 1.0)))
(define h (make-vector 4 0.0))
(define (h-set! i j val) (vector-set! h (+ (* i 2) j) val))
(define (h-ref i j) (vector-ref h (+ (* i 2) j)))
(do ((i 0 (+ i 1))) ((= i 2))
  (do ((j 0 (+ j 1))) ((= j 2))
    (let* ((e1 (list-ref seeds i)) (e2 (list-ref seeds j))
           (hx (new-HyperDual mx (car e1) (car e2) 0.0))
           (hy (new-HyperDual my (cadr e1) (cadr e2) 0.0)))
      (h-set! i j (HyperDual-eps1eps2 (rosenbrock-hyperdual hx hy))))))
(format #t "Hessian of the Rosenbrock function at its minimum (1,1):\n")
(do ((row 0 (+ row 1))) ((= row 2))
  (format #t "  [~a, ~a]\n" (h-ref row 0) (h-ref row 1)))

(format #t "\n=================== Gradient descent driven by reverse-mode gradients ===================\n")
(define point-x -1.2)
(define point-y 1.0)
(define learning-rate 0.001)
(define n-steps 2000)
(do ((step 0 (+ step 1))) ((= step n-steps))
  (let* ((t (new-Tape))
         (vx2 (new-Var t point-x))
         (vy2 (new-Var t point-y))
         (va2 (Var-subtract (new-Var t 1.0) vx2))
         (vb2 (Var-subtract vy2 (Var-multiply vx2 vx2)))
         (vf2 (Var-add (Var-multiply va2 va2) (Var-multiply-scalar (Var-multiply vb2 vb2) 100.0)))
         (grad (Tape-backward t vf2))
         (loss (Var-value vf2)))
    (set! point-x (- point-x (* learning-rate (vector-ref grad (Var-index vx2)))))
    (set! point-y (- point-y (* learning-rate (vector-ref grad (Var-index vy2)))))
    (when (or (= step 0) (= step (- n-steps 1)))
      (format #t "step ~a: loss = ~a, x = [~a, ~a]\n" step loss point-x point-y))))
(format #t "(true minimum is at [1, 1] with loss 0)\n")
