(use-modules (datamunge) (ice-9 format))

(define (report-purity cluster-labels species n-clusters)
  (let ((votes (make-hash-table))
        (n (vector-length cluster-labels)))
    (do ((i 0 (+ i 1))) ((= i n))
      (let ((label (vector-ref cluster-labels i)))
        (when (>= label 0)
          (let* ((sp (list-ref species i))
                 (key (cons label sp)))
            (hash-set! votes key (+ 1 (hash-ref votes key 0)))))))
    (do ((c 0 (+ c 1))) ((= c n-clusters))
      (let ((total 0) (best 0) (best-sp ""))
        (hash-for-each
          (lambda (key cnt)
            (when (= (car key) c)
              (set! total (+ total cnt))
              (when (> cnt best)
                (set! best cnt)
                (set! best-sp (cdr key)))))
          votes)
        (when (> total 0)
          (format #t "  cluster ~a: ~a points, majority ~a (~a/~a)\n" c total best-sp best total))))))

(define iris (DataFrame-iris))
(define n (DataFrame-nrows iris))
(define species '())
(do ((i 0 (+ i 1))) ((= i n))
  (set! species (cons (DataFrame-string-at iris "Species" i) species)))
(set! species (reverse species))
(define features (list "Sepal.Length" "Sepal.Width" "Petal.Length" "Petal.Width"))

(format #t "=================== K-means (k=3) on iris ===================\n")
(define kmeans (new-KMeans iris features 3))
(format #t "Inertia: ~a, iterations (best run): ~a\n" (KMeans-inertia kmeans) (KMeans-iterations-used kmeans))
(report-purity (KMeans-labels kmeans) species 3)

(format #t "\n=================== Agglomerative clustering on iris ===================\n")
(for-each
  (lambda (linkage)
    (define model (new-AgglomerativeClustering iris features 3 linkage))
    (format #t "--- linkage=~a ---\n" linkage)
    (report-purity (AgglomerativeClustering-labels model) species 3))
  (list "ward" "complete" "average"))

(format #t "\n--- Re-cutting the ward dendrogram at k=2 without refitting ---\n")
(define ward-model (new-AgglomerativeClustering iris features 3 "ward"))
(report-purity (AgglomerativeClustering-cut ward-model 2) species 2)

(format #t "\n=================== DBSCAN on iris ===================\n")
(define dbscan (new-DBSCAN iris features 0.6 5))
(format #t "Clusters found: ~a, noise points: ~a (of ~a)\n" (DBSCAN-n-clusters dbscan) (DBSCAN-n-noise dbscan) (DBSCAN-observations dbscan))
(report-purity (DBSCAN-labels dbscan) species (DBSCAN-n-clusters dbscan))
