(use-modules (datamunge))

(define iris (DataFrame-iris))

(define is-virginica '())
(define petal-length '())
(define petal-width '())
(define n (DataFrame-nrows iris))
(do ((i 0 (+ i 1))) ((= i n))
  (let ((species (DataFrame-string-at iris "Species" i)))
    (when (or (string=? species "versicolor") (string=? species "virginica"))
      (set! is-virginica (cons (if (string=? species "virginica") 1.0 0.0) is-virginica))
      (set! petal-length (cons (DataFrame-numeric-at iris "Petal.Length" i) petal-length))
      (set! petal-width (cons (DataFrame-numeric-at iris "Petal.Width" i) petal-width)))))
(set! is-virginica (reverse is-virginica))
(set! petal-length (reverse petal-length))
(set! petal-width (reverse petal-width))

(define sub (DataFrame-empty))
(DataFrame-add-numeric-column sub "Petal.Length" petal-length)
(DataFrame-add-numeric-column sub "Petal.Width" petal-width)
(DataFrame-add-numeric-column sub "is_virginica" is-virginica)

(format #t "=================== Logistic regression (binomial, logit link) ===================\n")
(define logit (new-GLM sub "is_virginica ~ Petal.Length + Petal.Width" "binomial"))
(GLM-print-summary logit)

(define fitted (GLM-fitted-values logit))
(define correct 0)
(define nn (length is-virginica))
(do ((i 0 (+ i 1))) ((= i nn))
  (let ((fv (vector-ref fitted i))
        (av (list-ref is-virginica i)))
    (when (eq? (>= fv 0.5) (>= av 0.5))
      (set! correct (+ correct 1)))))
(format #t "\nResubstitution accuracy at 0.5 threshold: ~a%\n" (* 100.0 (/ correct nn)))

(GLM-save-diagnostic-plots logit "glm_logistic_iris")
(format #t "\nSaved glm_logistic_iris_{residuals_vs_fitted,normal_qq,scale_location,residuals_vs_leverage}.svg\n")

(define width-mean (/ (apply + petal-width) (exact->inexact nn)))
(define grid-n 100)
(define pl-min (- (apply min petal-length) 0.3))
(define pl-max (+ (apply max petal-length) 0.3))
(define grid-x '())
(define grid-w '())
(do ((i 0 (+ i 1))) ((= i grid-n))
  (set! grid-x (cons (+ pl-min (* (- pl-max pl-min) (/ i (- grid-n 1)))) grid-x))
  (set! grid-w (cons width-mean grid-w)))
(set! grid-x (reverse grid-x))
(set! grid-w (reverse grid-w))
(define grid (DataFrame-empty))
(DataFrame-add-numeric-column grid "Petal.Length" grid-x)
(DataFrame-add-numeric-column grid "Petal.Width" grid-w)
(define curve-frame (GLM-predict-frame logit grid "confidence"))
(format #t "\nPredicted-probability curve (first 5 rows):\n")
(format #t "~a\n" (DataFrame-to-string curve-frame 5))

(format #t "\n=================== Poisson regression (log link) ===================\n")
(define count '())
(define sepal-width '())
(define all-petal-length '())
(do ((i 0 (+ i 1))) ((= i n))
  (set! count (cons (round (DataFrame-numeric-at iris "Sepal.Length" i)) count))
  (set! sepal-width (cons (DataFrame-numeric-at iris "Sepal.Width" i) sepal-width))
  (set! all-petal-length (cons (DataFrame-numeric-at iris "Petal.Length" i) all-petal-length)))
(set! count (reverse count))
(set! sepal-width (reverse sepal-width))
(set! all-petal-length (reverse all-petal-length))
(define count-data (DataFrame-empty))
(DataFrame-add-numeric-column count-data "Sepal.Width" sepal-width)
(DataFrame-add-numeric-column count-data "Petal.Length" all-petal-length)
(DataFrame-add-numeric-column count-data "count" count)

(define poisson (new-GLM count-data "count ~ Sepal.Width + Petal.Length" "poisson"))
(GLM-print-summary poisson)
