(use-modules (datamunge) (srfi srfi-1))

(define (my-rand) (random 1.0))
(define (my-randn)
  (let ((u1 (my-rand)) (u2 (my-rand)))
    (* (sqrt (* -2.0 (log u1))) (cos (* 2.0 3.14159265358979323846 u2)))))

(format #t "=================== Binomial (logistic) mixed model on a real dataset (penguins) ===================\n")
(define penguins (DataFrame-penguins))
(define is-male '())
(define body-mass '())
(define island '())
(define n (DataFrame-nrows penguins))
(do ((i 0 (+ i 1))) ((= i n))
  (unless (or (DataFrame-is-null penguins "sex" i) (DataFrame-is-null penguins "body_mass_g" i) (DataFrame-is-null penguins "island" i))
    (set! is-male (cons (if (string=? (DataFrame-string-at penguins "sex" i) "male") 1.0 0.0) is-male))
    (set! body-mass (cons (DataFrame-numeric-at penguins "body_mass_g" i) body-mass))
    (set! island (cons (DataFrame-string-at penguins "island" i) island))))
(set! is-male (reverse is-male))
(set! body-mass (reverse body-mass))
(set! island (reverse island))

(define sex-df (DataFrame-empty))
(DataFrame-add-numeric-column sex-df "is_male" is-male)
(DataFrame-add-numeric-column sex-df "body_mass_g" body-mass)
(DataFrame-add-string-column sex-df "island" island)

(define sex-model (new-GLMM sex-df "is_male ~ body_mass_g + (1 | island)" "binomial"))
(GLMM-print-summary sex-model)

(format #t "\n=================== Poisson mixed model on simulated multi-site count data ===================\n")
(set! *random-state* (seed->random-state 4242))
(define n-stores 25)
(define store-effect (map (lambda (i) (* (my-randn) 0.4)) (iota n-stores)))

(define true-intercept 2.0)
(define true-slope 0.3)
(define store '())
(define promo '())
(define visits '())
(do ((s 0 (+ s 1))) ((= s n-stores))
  (let ((n-days (+ 15 (inexact->exact (truncate (* (my-rand) 11))))))
    (do ((d 0 (+ d 1))) ((= d n-days))
      (let* ((promo-intensity (* (my-rand) 3.0))
             (lam (exp (+ true-intercept (list-ref store-effect s) (* true-slope promo-intensity))))
             (l-thresh (exp (- lam)))
             (k 0)
             (p 1.0))
        (let loop ()
          (set! k (+ k 1))
          (set! p (* p (my-rand)))
          (when (> p l-thresh) (loop)))
        (set! store (cons s store))
        (set! promo (cons promo-intensity promo))
        (set! visits (cons (- k 1) visits))))))
(set! store (reverse store))
(set! promo (reverse promo))
(set! visits (reverse visits))

(define df (DataFrame-empty))
(DataFrame-add-numeric-column df "store" store)
(DataFrame-add-numeric-column df "promo" promo)
(DataFrame-add-numeric-column df "visits" visits)

(define store-model (new-GLMM df "visits ~ promo + (1 | store)" "poisson"))
(GLMM-print-summary store-model)

(format #t "\nTrue generating values: intercept=~a, slope=~a, random-intercept SD (log scale)=0.4\n" true-intercept true-slope)

(format #t "\n--- BLUPs for a few stores ---\n")
(define group-labels (GLMM-group-labels store-model))
(do ((idx 0 (+ idx 1))) ((= idx 3))
  (let ((re (GLMM-random-effects-for-group store-model idx)))
    (format #t "store ~a: intercept shift=~a\n" (vector-ref group-labels idx) (vector-ref re 0))))

(format #t "\n--- Prediction: population-level vs. store-adjusted ---\n")
(define newdata-population (DataFrame-empty))
(DataFrame-add-numeric-column newdata-population "promo" (list 1.5))
(define newdata-store0 (DataFrame-empty))
(DataFrame-add-numeric-column newdata-store0 "promo" (list 1.5))
(DataFrame-add-numeric-column newdata-store0 "store" (list 0.0))
(define pred-pop (GLMM-predict store-model newdata-population))
(define pred-s0 (GLMM-predict store-model newdata-store0))
(format #t "promo=1.5, unseen store:   ~a expected visits (fixed effects only)\n" (vector-ref pred-pop 0))
(format #t "promo=1.5, store 0 (known): ~a expected visits (fixed effects + store 0's BLUP)\n" (vector-ref pred-s0 0))
