(use-modules (datamunge))

(define (print-result label r)
  (let ((line (string-append label ": statistic=" (number->string (HypothesisTestResult-statistic-get r)))))
    (unless (= (HypothesisTestResult-parameter1-get r) 0.0)
      (set! line (string-append line ", df1=" (number->string (HypothesisTestResult-parameter1-get r)))))
    (unless (= (HypothesisTestResult-parameter2-get r) 0.0)
      (set! line (string-append line ", df2=" (number->string (HypothesisTestResult-parameter2-get r)))))
    (let ((alt-names (vector "two.sided" "less" "greater")))
      (set! line (string-append line ", p=" (number->string (HypothesisTestResult-p-value-get r))
                                 " (" (vector-ref alt-names (HypothesisTestResult-alternative-get r)) ")")))
    (when (HypothesisTestResult-has-conf-int-get r)
      (set! line (string-append line ", CI=[" (number->string (HypothesisTestResult-conf-int-lower-get r))
                                 ", " (number->string (HypothesisTestResult-conf-int-upper-get r)) "]")))
    (set! line (string-append line " -- " (HypothesisTestResult-method-get r)))
    (format #t "~a\n" line)))

(define (column-for-species df column species)
  (let ((out '()) (n (DataFrame-nrows df)))
    (do ((i 0 (+ i 1))) ((= i n))
      (when (string=? (DataFrame-string-at df "Species" i) species)
        (set! out (cons (DataFrame-numeric-at df column i) out))))
    (reverse out)))

(define iris (DataFrame-iris))

(define setosa-petal (column-for-species iris "Petal.Length" "setosa"))
(define versicolor-petal (column-for-species iris "Petal.Length" "versicolor"))
(define virginica-petal (column-for-species iris "Petal.Length" "virginica"))

(format #t "=================== t-tests: petal length, setosa vs. versicolor ===================\n")
(print-result "Welch two-sample t-test" (t-test-two-sample setosa-petal versicolor-petal))
(print-result "Wilcoxon rank-sum test" (wilcoxon-rank-sum-test setosa-petal versicolor-petal))

(format #t "\n=================== One-way ANOVA / Kruskal-Wallis across all 3 species ===================\n")
(define all-petal (append setosa-petal versicolor-petal virginica-petal))
(define sizes (list (length setosa-petal) (length versicolor-petal) (length virginica-petal)))
(print-result "One-way ANOVA" (one-way-anova all-petal sizes))
(print-result "Kruskal-Wallis" (kruskal-wallis-test all-petal sizes))

(format #t "\n=================== Correlation: sepal length vs. petal length ===================\n")
(define n (DataFrame-nrows iris))
(define sepal-length '())
(define petal-length '())
(do ((i 0 (+ i 1))) ((= i n))
  (set! sepal-length (cons (DataFrame-numeric-at iris "Sepal.Length" i) sepal-length))
  (set! petal-length (cons (DataFrame-numeric-at iris "Petal.Length" i) petal-length)))
(set! sepal-length (reverse sepal-length))
(set! petal-length (reverse petal-length))
(print-result "Pearson correlation" (pearson-correlation-test sepal-length petal-length))
(print-result "Spearman correlation" (spearman-correlation-test sepal-length petal-length))

(format #t "\n=================== F-test: petal length variance, setosa vs. virginica ===================\n")
(print-result "F test" (f-test-variance setosa-petal virginica-petal))

(format #t "\n=================== Normality: is sepal length normally distributed within setosa? ===================\n")
(define setosa-sepal (column-for-species iris "Sepal.Length" "setosa"))
(print-result "Shapiro-Francia" (shapiro-francia-test setosa-sepal))
(print-result "KS vs. fitted normal" (ks-test-one-sample-normal setosa-sepal 5.006 0.3525))

(format #t "\n=================== Chi-squared / Fisher: is petal length \"long\" independent of species? ===================\n")
(define sorted-all (sort all-petal <))
(define median-all (list-ref sorted-all (quotient (length all-petal) 2)))
(define setosa-long (length (filter (lambda (x) (> x median-all)) setosa-petal)))
(define setosa-short (- (length setosa-petal) setosa-long))
(define versicolor-long (length (filter (lambda (x) (> x median-all)) versicolor-petal)))
(define versicolor-short (- (length versicolor-petal) versicolor-long))
(format #t "table: setosa=[~a,~a] versicolor=[~a,~a]\n" setosa-long setosa-short versicolor-long versicolor-short)
(define table-vec (list setosa-long setosa-short versicolor-long versicolor-short))
(print-result "Chi-squared independence" (chi-squared-test-independence table-vec 2 2))
(print-result "Fisher's exact test" (fisher-exact-test-2x2 setosa-long setosa-short versicolor-long versicolor-short))

(format #t "\n=================== Proportion / binomial: fraction of \"long\" petals overall ===================\n")
(define long-count (length (filter (lambda (x) (> x median-all)) all-petal)))
(print-result "One-sample proportion test (vs 0.5)" (proportion-test-one-sample long-count (length all-petal) 0.5))
(print-result "Exact binomial test (vs 0.5)" (binomial-test long-count (length all-petal) 0.5))
