(use-modules (datamunge) (srfi srfi-1) (ice-9 format))

(define (my-rand) (random 1.0))
(define (my-randn)
  (let ((u1 (my-rand)) (u2 (my-rand)))
    (* (sqrt (* -2.0 (log u1))) (cos (* 2.0 3.14159265358979323846 u2)))))

(format #t "=================== Random intercept on a real dataset (penguins) ===================\n")
(define penguins (DataFrame-penguins))
(define species-model (new-LMM penguins "body_mass_g ~ flipper_length_mm + bill_length_mm + (1 | species)"))
(LMM-print-summary species-model)

(format #t "\n=================== Random intercept + slope on a simulated multi-school dataset ===================\n")
(set! *random-state* (seed->random-state 2024))
(define n-schools 30)
(define school-intercept (map (lambda (i) (* (my-randn) 6.0)) (iota n-schools)))
(define school-slope (map (lambda (i) (* (my-randn) 1.2)) (iota n-schools)))

(define true-intercept 60.0)
(define true-slope 3.0)
(define school '())
(define study-hours '())
(define score '())
(do ((s 0 (+ s 1))) ((= s n-schools))
  (let ((n-students (+ 15 (inexact->exact (truncate (* (my-rand) 21))))))
    (do ((j 0 (+ j 1))) ((= j n-students))
      (let* ((hours (* (my-rand) 10.0))
             (noise (* (my-randn) 4.0))
             (s-val (+ true-intercept (list-ref school-intercept s)
                       (* (+ true-slope (list-ref school-slope s)) hours) noise)))
        (set! school (cons s school))
        (set! study-hours (cons hours study-hours))
        (set! score (cons s-val score))))))
(set! school (reverse school))
(set! study-hours (reverse study-hours))
(set! score (reverse score))

(define df (DataFrame-empty))
(DataFrame-add-numeric-column df "school" school)
(DataFrame-add-numeric-column df "study_hours" study-hours)
(DataFrame-add-numeric-column df "score" score)

(define model (new-LMM df "score ~ study_hours + (1 + study_hours | school)"))
(LMM-print-summary model)

(format #t "\nTrue generating values: intercept=~a, slope=~a, random-intercept SD=6.0, random-slope SD=1.2, residual SD=4.0\n" true-intercept true-slope)

(format #t "\n--- Best Linear Unbiased Predictors (BLUPs) for a few schools ---\n")
(define group-labels (LMM-group-labels model))
(do ((idx 0 (+ idx 1))) ((= idx 3))
  (let ((re (LMM-random-effects-for-group model idx)))
    (format #t "school ~a: intercept shift=~a, slope shift=~a\n" (vector-ref group-labels idx) (vector-ref re 0) (vector-ref re 1))))

(format #t "\n--- Prediction: population-level vs. school-adjusted ---\n")
(define newdata-population (DataFrame-empty))
(DataFrame-add-numeric-column newdata-population "study_hours" (list 5.0))
(define newdata-school0 (DataFrame-empty))
(DataFrame-add-numeric-column newdata-school0 "study_hours" (list 5.0))
(DataFrame-add-numeric-column newdata-school0 "school" (list 0.0))
(define pred-pop (LMM-predict model newdata-population))
(define pred-s0 (LMM-predict model newdata-school0))
(format #t "5 study hours, unseen school:      ~a (fixed effects only)\n" (vector-ref pred-pop 0))
(format #t "5 study hours, school 0 (known):    ~a (fixed effects + school 0's BLUP)\n" (vector-ref pred-s0 0))
