(use-modules (datamunge) (srfi srfi-1))

(define (my-rand) (random 1.0))
(define (my-randn)
  (let ((u1 (my-rand)) (u2 (my-rand)))
    (* (sqrt (* -2.0 (log u1))) (cos (* 2.0 3.14159265358979323846 u2)))))

(define (cell-join v)
  (string-join (map number->string (vector->list v)) ", "))

(format #t "=================== ARIMA(1,1,1) on a simulated random walk with drift ===================\n")
(set! *random-state* (seed->random-state 42))
(define y '())
(define level 100.0)
(define prev-shock 0.0)
(do ((i 0 (+ i 1))) ((= i 150))
  (let ((shock (my-randn)))
    (set! level (+ level 0.3 (* 0.4 prev-shock) shock))
    (set! y (cons level y))
    (set! prev-shock shock)))
(set! y (reverse y))

(define options (new-ARIMAOptions))
(ARIMAOptions-p-set options 1)
(ARIMAOptions-d-set options 1)
(ARIMAOptions-q-set options 1)
(ARIMAOptions-de-population-size-set options 80)
(ARIMAOptions-de-max-generations-set options 400)
(define model (new-ARIMA y options))

(define ar (ARIMA-ar-coefficients model))
(define ma (ARIMA-ma-coefficients model))
(format #t "AR coefficient: ~a\n" (DVector-ref ar 0))
(format #t "MA coefficient: ~a\n" (DVector-ref ma 0))
(format #t "sigma^2: ~a, AIC: ~a, BIC: ~a\n" (ARIMA-sigma2 model) (ARIMA-aic model) (ARIMA-bic model))

(define pair (ARIMA-forecast-with-intervals model 6))
(define fc (car pair))
(define se (cdr pair))
(format #t "6-step forecast: ~a\n"
        (string-join (map (lambda (i) (number->string (DVector-ref fc i))) (iota (DVector-length fc))) ", "))
(format #t "forecast std. errors: ~a\n"
        (string-join (map (lambda (i) (number->string (DVector-ref se i))) (iota (DVector-length se))) ", "))

(format #t "\n=================== SARIMA(1,0,0)(1,1,0)_12 on a seasonal series ===================\n")
(set! *random-state* (seed->random-state 7))
(define s '())
(define prev 0.0)
(do ((i 0 (+ i 1))) ((= i 120))
  (set! prev (+ (* 0.5 prev) (my-randn)))
  (set! s (cons (+ 20.0 (* 0.2 i) (* 5.0 (sin (/ (* 2.0 3.14159265358979323846 i) 12.0))) prev) s)))
(set! s (reverse s))

(define options2 (new-ARIMAOptions))
(ARIMAOptions-p-set options2 1)
(ARIMAOptions-seasonal-p-set options2 1)
(ARIMAOptions-seasonal-d-set options2 1)
(ARIMAOptions-seasonal-period-set options2 12)
(ARIMAOptions-de-population-size-set options2 100)
(ARIMAOptions-de-max-generations-set options2 500)
(define model2 (new-ARIMA s options2))
(define ar2 (ARIMA-ar-coefficients model2))
(define sar2 (ARIMA-seasonal-ar-coefficients model2))
(format #t "AR coefficient: ~a, seasonal AR coefficient: ~a\n" (DVector-ref ar2 0) (DVector-ref sar2 0))
(format #t "12-step forecast: ~a\n" (cell-join (ARIMA-forecast model2 12)))

(format #t "\n=================== Exponential smoothing: Holt-Winters on retail-style seasonal data ===================\n")
(define seasonal-shape (vector 0.8 0.75 0.9 0.95 1.0 1.05 1.1 1.05 1.0 1.1 1.3 1.6))
(set! *random-state* (seed->random-state 11))
(define y2 '())
(do ((i 0 (+ i 1))) ((= i 48))
  (let ((lvl (+ 100.0 (* 2.0 i))))
    (set! y2 (cons (+ (* lvl (vector-ref seasonal-shape (modulo i 12))) (* (my-randn) 3.0)) y2))))
(set! y2 (reverse y2))

(define es-options (new-ExponentialSmoothingOptions))
(ExponentialSmoothingOptions-trend-set es-options (TrendType-Additive))
(ExponentialSmoothingOptions-seasonal-set es-options (SeasonalType-Multiplicative))
(ExponentialSmoothingOptions-seasonal-period-set es-options 12)
(ExponentialSmoothingOptions-de-population-size-set es-options 60)
(ExponentialSmoothingOptions-de-max-generations-set es-options 300)
(define es-model (new-ExponentialSmoothing y2 es-options))
(format #t "alpha=~a beta=~a gamma=~a\n" (ExponentialSmoothing-alpha es-model) (ExponentialSmoothing-beta es-model) (ExponentialSmoothing-gamma es-model))
(format #t "sigma^2: ~a, AIC: ~a\n" (ExponentialSmoothing-sigma2 es-model) (ExponentialSmoothing-aic es-model))
(format #t "12-month forecast: ~a\n" (cell-join (ExponentialSmoothing-forecast es-model 12)))

(format #t "\n=================== Simple exponential smoothing vs. Holt's linear trend ===================\n")
(define flat (list 50.2 49.8 50.5 49.6 50.1 50.3 49.9 50.0 50.4 49.7))

(define ses (new-ExponentialSmoothing flat (new-ExponentialSmoothingOptions)))
(format #t "SES alpha= ~a\n" (ExponentialSmoothing-alpha ses))
(format #t "SES 5-step forecast: ~a\n" (cell-join (ExponentialSmoothing-forecast ses 5)))

(define holt-options (new-ExponentialSmoothingOptions))
(ExponentialSmoothingOptions-trend-set holt-options (TrendType-Additive))
(define holt (new-ExponentialSmoothing flat holt-options))
(format #t "Holt alpha=~a beta=~a\n" (ExponentialSmoothing-alpha holt) (ExponentialSmoothing-beta holt))
(format #t "Holt 5-step forecast: ~a\n" (cell-join (ExponentialSmoothing-forecast holt 5)))
