/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_datamunge_WRAP_H_
#define SWIG_datamunge_WRAP_H_

class SwigDirector_Callback : public datamunge::Callback, public Swig::Director {

public:
    SwigDirector_Callback();
    virtual ~SwigDirector_Callback();
    virtual double call(double x);

    typedef double (* SWIG_Callback0_t)(void *dobj, double);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackcall);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_call;
};

class SwigDirector_ArbitraryFunction : public datamunge::optim::ArbitraryFunction, public Swig::Director {

public:
    SwigDirector_ArbitraryFunction();
    virtual ~SwigDirector_ArbitraryFunction();
    virtual double evaluate(std::vector< double > const &coordinates);

    typedef double (* SWIG_Callback0_t)(void *dobj, void *);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackevaluate);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_evaluate;
};

class SwigDirector_DifferentiableFunction : public datamunge::optim::DifferentiableFunction, public Swig::Director {

public:
    SwigDirector_DifferentiableFunction();
    virtual ~SwigDirector_DifferentiableFunction();
    virtual double evaluate(std::vector< double > const &coordinates);
    virtual std::vector< double > gradient(std::vector< double > const &coordinates);

    typedef double (* SWIG_Callback0_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback1_t)(void *dobj, void *);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackevaluate, SWIG_Callback1_t callbackgradient);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_evaluate;
    SWIG_Callback1_t swig_callback_gradient;
};

class SwigDirector_SeparableFunction : public datamunge::optim::SeparableFunction, public Swig::Director {

public:
    SwigDirector_SeparableFunction();
    virtual ~SwigDirector_SeparableFunction();
    virtual double evaluate(std::vector< double > const &coordinates);
    virtual std::size_t num_functions() const;
    virtual double evaluate_term(std::vector< double > const &coordinates,std::size_t i);

    typedef double (* SWIG_Callback0_t)(void *dobj, void *);
    typedef size_t (* SWIG_Callback1_t)(void *dobj);
    typedef double (* SWIG_Callback2_t)(void *dobj, void *, size_t);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackevaluate, SWIG_Callback1_t callbacknum_functions, SWIG_Callback2_t callbackevaluate_term);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_evaluate;
    SWIG_Callback1_t swig_callback_num_functions;
    SWIG_Callback2_t swig_callback_evaluate_term;
};

class SwigDirector_DifferentiableSeparableFunction : public datamunge::optim::DifferentiableSeparableFunction, public Swig::Director {

public:
    SwigDirector_DifferentiableSeparableFunction();
    virtual ~SwigDirector_DifferentiableSeparableFunction();
    virtual double evaluate(std::vector< double > const &coordinates);
    virtual std::vector< double > gradient(std::vector< double > const &coordinates);
    virtual std::size_t num_functions() const;
    virtual double evaluate_term(std::vector< double > const &coordinates,std::size_t i);
    virtual std::vector< double > gradient_term(std::vector< double > const &coordinates,std::size_t i);

    typedef double (* SWIG_Callback0_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback1_t)(void *dobj, void *);
    typedef size_t (* SWIG_Callback2_t)(void *dobj);
    typedef double (* SWIG_Callback3_t)(void *dobj, void *, size_t);
    typedef void * (* SWIG_Callback4_t)(void *dobj, void *, size_t);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackevaluate, SWIG_Callback1_t callbackgradient, SWIG_Callback2_t callbacknum_functions, SWIG_Callback3_t callbackevaluate_term, SWIG_Callback4_t callbackgradient_term);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_evaluate;
    SWIG_Callback1_t swig_callback_gradient;
    SWIG_Callback2_t swig_callback_num_functions;
    SWIG_Callback3_t swig_callback_evaluate_term;
    SWIG_Callback4_t swig_callback_gradient_term;
};

class SwigDirector_ProximalFunction : public datamunge::optim::ProximalFunction, public Swig::Director {

public:
    SwigDirector_ProximalFunction();
    virtual ~SwigDirector_ProximalFunction();
    virtual double evaluate(std::vector< double > const &coordinates);
    virtual std::vector< double > gradient(std::vector< double > const &coordinates);
    virtual std::vector< double > proximal(std::vector< double > const &point,double step);

    typedef double (* SWIG_Callback0_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback1_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback2_t)(void *dobj, void *, double);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackevaluate, SWIG_Callback1_t callbackgradient, SWIG_Callback2_t callbackproximal);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_evaluate;
    SWIG_Callback1_t swig_callback_gradient;
    SWIG_Callback2_t swig_callback_proximal;
};

class SwigDirector_HessianFunction : public datamunge::optim::HessianFunction, public Swig::Director {

public:
    SwigDirector_HessianFunction();
    virtual ~SwigDirector_HessianFunction();
    virtual double evaluate(std::vector< double > const &coordinates);
    virtual std::vector< double > gradient(std::vector< double > const &coordinates);
    virtual std::vector< std::vector< double > > hessian(std::vector< double > const &coordinates);

    typedef double (* SWIG_Callback0_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback1_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback2_t)(void *dobj, void *);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackevaluate, SWIG_Callback1_t callbackgradient, SWIG_Callback2_t callbackhessian);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_evaluate;
    SWIG_Callback1_t swig_callback_gradient;
    SWIG_Callback2_t swig_callback_hessian;
};

class SwigDirector_EqualityConstrainedFunction : public datamunge::optim::EqualityConstrainedFunction, public Swig::Director {

public:
    SwigDirector_EqualityConstrainedFunction();
    virtual ~SwigDirector_EqualityConstrainedFunction();
    virtual double evaluate(std::vector< double > const &coordinates);
    virtual std::vector< double > gradient(std::vector< double > const &coordinates);
    virtual std::vector< double > constraints(std::vector< double > const &coordinates);
    virtual std::vector< std::vector< double > > constraint_jacobian(std::vector< double > const &coordinates);

    typedef double (* SWIG_Callback0_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback1_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback2_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback3_t)(void *dobj, void *);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackevaluate, SWIG_Callback1_t callbackgradient, SWIG_Callback2_t callbackconstraints, SWIG_Callback3_t callbackconstraint_jacobian);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_evaluate;
    SWIG_Callback1_t swig_callback_gradient;
    SWIG_Callback2_t swig_callback_constraints;
    SWIG_Callback3_t swig_callback_constraint_jacobian;
};

class SwigDirector_InequalityConstrainedFunction : public datamunge::optim::InequalityConstrainedFunction, public Swig::Director {

public:
    SwigDirector_InequalityConstrainedFunction();
    virtual ~SwigDirector_InequalityConstrainedFunction();
    virtual double evaluate(std::vector< double > const &coordinates);
    virtual std::vector< double > gradient(std::vector< double > const &coordinates);
    virtual std::vector< double > inequalities(std::vector< double > const &coordinates);
    virtual std::vector< std::vector< double > > inequality_jacobian(std::vector< double > const &coordinates);

    typedef double (* SWIG_Callback0_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback1_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback2_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback3_t)(void *dobj, void *);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackevaluate, SWIG_Callback1_t callbackgradient, SWIG_Callback2_t callbackinequalities, SWIG_Callback3_t callbackinequality_jacobian);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_evaluate;
    SWIG_Callback1_t swig_callback_gradient;
    SWIG_Callback2_t swig_callback_inequalities;
    SWIG_Callback3_t swig_callback_inequality_jacobian;
};

class SwigDirector_ResidualFunction : public datamunge::optim::ResidualFunction, public Swig::Director {

public:
    SwigDirector_ResidualFunction();
    virtual ~SwigDirector_ResidualFunction();
    virtual std::vector< double > residuals(std::vector< double > const &coordinates);
    virtual std::vector< std::vector< double > > jacobian(std::vector< double > const &coordinates);

    typedef void * (* SWIG_Callback0_t)(void *dobj, void *);
    typedef void * (* SWIG_Callback1_t)(void *dobj, void *);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackresiduals, SWIG_Callback1_t callbackjacobian);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_residuals;
    SWIG_Callback1_t swig_callback_jacobian;
};

class SwigDirector_BayesianSurrogate : public datamunge::optim::BayesianSurrogate, public Swig::Director {

public:
    SwigDirector_BayesianSurrogate();
    virtual ~SwigDirector_BayesianSurrogate();
    virtual void fit(std::vector< std::vector< double > > const &points,std::vector< double > const &values);
    virtual double acquisition(std::vector< double > const &point,double incumbent);

    typedef void (* SWIG_Callback0_t)(void *dobj, void *, void *);
    typedef double (* SWIG_Callback1_t)(void *dobj, void *, double);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackfit, SWIG_Callback1_t callbackacquisition);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_fit;
    SWIG_Callback1_t swig_callback_acquisition;
};


#endif
