//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ACOROptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ACOROptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ACOROptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ACOROptions obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ACOROptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_ACOROptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>k: number of solutions kept in the archive.</summary>
  public uint archive_size {
    set {
      datamungePINVOKE.ACOROptions_archive_size_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.ACOROptions_archive_size_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>m: new ants generated each iteration.</summary>
  public uint samples_per_iteration {
    set {
      datamungePINVOKE.ACOROptions_samples_per_iteration_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.ACOROptions_samples_per_iteration_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>q: locality of the search; smaller values concentrate sampling more tightly        around the best-ranked archive solutions.</summary>
  public double locality {
    set {
      datamungePINVOKE.ACOROptions_locality_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.ACOROptions_locality_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>xi (ξ): convergence speed; larger values widen sampling around each archive        solution, slowing convergence.</summary>
  public double convergence_speed {
    set {
      datamungePINVOKE.ACOROptions_convergence_speed_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.ACOROptions_convergence_speed_get(swigCPtr);
      return ret;
    } 
  }

  public uint max_iterations {
    set {
      datamungePINVOKE.ACOROptions_max_iterations_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.ACOROptions_max_iterations_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Stops after the best-ever value has improved by less than this for 20 consecutive        iterations.</summary>
  public double tolerance {
    set {
      datamungePINVOKE.ACOROptions_tolerance_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.ACOROptions_tolerance_get(swigCPtr);
      return ret;
    } 
  }

  public ulong seed {
    set {
      datamungePINVOKE.ACOROptions_seed_set(swigCPtr, value);
    } 
    get {
      ulong ret = datamungePINVOKE.ACOROptions_seed_get(swigCPtr);
      return ret;
    } 
  }

  public ACOROptions() : this(datamungePINVOKE.new_ACOROptions(), true) {
  }

}
