//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class AdaGradOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AdaGradOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AdaGradOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AdaGradOptions obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AdaGradOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_AdaGradOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double step_size {
    set {
      datamungePINVOKE.AdaGradOptions_step_size_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.AdaGradOptions_step_size_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Added inside the square root to keep early and zero-gradient updates finite.</summary>
  public double epsilon {
    set {
      datamungePINVOKE.AdaGradOptions_epsilon_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.AdaGradOptions_epsilon_get(swigCPtr);
      return ret;
    } 
  }

  public uint max_iterations {
    set {
      datamungePINVOKE.AdaGradOptions_max_iterations_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.AdaGradOptions_max_iterations_get(swigCPtr);
      return ret;
    } 
  }

  public double tolerance {
    set {
      datamungePINVOKE.AdaGradOptions_tolerance_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.AdaGradOptions_tolerance_get(swigCPtr);
      return ret;
    } 
  }

  public AdaGradOptions() : this(datamungePINVOKE.new_AdaGradOptions(), true) {
  }

}
