//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ArtificialBeeColonyOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ArtificialBeeColonyOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ArtificialBeeColonyOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ArtificialBeeColonyOptions obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ArtificialBeeColonyOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_ArtificialBeeColonyOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>Number of food sources; also the number of employed bees and the number of        onlooker bees.</summary>
  public uint population_size {
    set {
      datamungePINVOKE.ArtificialBeeColonyOptions_population_size_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.ArtificialBeeColonyOptions_population_size_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>A food source that fails to improve for this many consecutive trials is        abandoned and replaced with a fresh random point. Zero selects the standard        heuristic default of population_size * dimension.</summary>
  public uint abandonment_limit {
    set {
      datamungePINVOKE.ArtificialBeeColonyOptions_abandonment_limit_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.ArtificialBeeColonyOptions_abandonment_limit_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>One cycle == one employed-bee phase + one onlooker-bee phase (+ scout phase).</summary>
  public uint max_generations {
    set {
      datamungePINVOKE.ArtificialBeeColonyOptions_max_generations_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.ArtificialBeeColonyOptions_max_generations_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Stops after the best-ever value has improved by less than this for 20        consecutive generations.</summary>
  public double tolerance {
    set {
      datamungePINVOKE.ArtificialBeeColonyOptions_tolerance_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.ArtificialBeeColonyOptions_tolerance_get(swigCPtr);
      return ret;
    } 
  }

  public ulong seed {
    set {
      datamungePINVOKE.ArtificialBeeColonyOptions_seed_set(swigCPtr, value);
    } 
    get {
      ulong ret = datamungePINVOKE.ArtificialBeeColonyOptions_seed_get(swigCPtr);
      return ret;
    } 
  }

  public ArtificialBeeColonyOptions() : this(datamungePINVOKE.new_ArtificialBeeColonyOptions(), true) {
  }

}
