//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DataSeries : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DataSeries(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DataSeries obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DataSeries obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DataSeries() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_DataSeries(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DataSeries.Kind kind {
    set {
      datamungePINVOKE.DataSeries_kind_set(swigCPtr, (int)value);
    } 
    get {
      DataSeries.Kind ret = (DataSeries.Kind)datamungePINVOKE.DataSeries_kind_get(swigCPtr);
      return ret;
    } 
  }

  public DVector x {
    set {
      datamungePINVOKE.DataSeries_x_set(swigCPtr, DVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = datamungePINVOKE.DataSeries_x_get(swigCPtr);
      DVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DVector(cPtr, false);
      return ret;
    } 
  }

  public DVector y {
    set {
      datamungePINVOKE.DataSeries_y_set(swigCPtr, DVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = datamungePINVOKE.DataSeries_y_get(swigCPtr);
      DVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DVector(cPtr, false);
      return ret;
    } 
  }

  public string label {
    set {
      datamungePINVOKE.DataSeries_label_set(swigCPtr, value);
      if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = datamungePINVOKE.DataSeries_label_get(swigCPtr);
      if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public RGB color {
    set {
      datamungePINVOKE.DataSeries_color_set(swigCPtr, RGB.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = datamungePINVOKE.DataSeries_color_get(swigCPtr);
      RGB ret = (cPtr == global::System.IntPtr.Zero) ? null : new RGB(cPtr, false);
      return ret;
    } 
  }

  public double stroke_width {
    set {
      datamungePINVOKE.DataSeries_stroke_width_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.DataSeries_stroke_width_get(swigCPtr);
      return ret;
    } 
  }

  public double marker_size {
    set {
      datamungePINVOKE.DataSeries_marker_size_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.DataSeries_marker_size_get(swigCPtr);
      return ret;
    } 
  }

  public double bar_width {
    set {
      datamungePINVOKE.DataSeries_bar_width_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.DataSeries_bar_width_get(swigCPtr);
      return ret;
    } 
  }

  public bool filled {
    set {
      datamungePINVOKE.DataSeries_filled_set(swigCPtr, value);
    } 
    get {
      bool ret = datamungePINVOKE.DataSeries_filled_get(swigCPtr);
      return ret;
    } 
  }

  public DataSeries() : this(datamungePINVOKE.new_DataSeries(), true) {
  }

  public enum Kind {
    Scatter,
    Line,
    Bar,
    Box,
    Polygon,
    Text,
    Segment
  }

}
