//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>An objective function that additionally supports exact gradient evaluation.        Optimizers that consume this type (GradientDescent, Adam, LBFGS) use the full        gradient at every step.</summary>

public class DifferentiableFunction : ArbitraryFunction {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DifferentiableFunction(global::System.IntPtr cPtr, bool cMemoryOwn) : base(datamungePINVOKE.DifferentiableFunction_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DifferentiableFunction obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DifferentiableFunction obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_DifferentiableFunction(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  /// <summary>Returns the gradient of the objective at ``coordinates``.</summary>
  public virtual DVector gradient(DVector coordinates) {
    DVector ret = new DVector(datamungePINVOKE.DifferentiableFunction_gradient(swigCPtr, DVector.getCPtr(coordinates)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DifferentiableFunction() : this(datamungePINVOKE.new_DifferentiableFunction(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("evaluate", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateDifferentiableFunction_0(SwigDirectorMethodevaluate);
    if (SwigDerivedClassHasMethod("gradient", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateDifferentiableFunction_1(SwigDirectorMethodgradient);
    datamungePINVOKE.DifferentiableFunction_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(DifferentiableFunction))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private double SwigDirectorMethodevaluate(global::System.IntPtr coordinates) {
    return evaluate(new DVector(coordinates, false));
  }

  private global::System.IntPtr SwigDirectorMethodgradient(global::System.IntPtr coordinates) {
    return DVector.getCPtr(gradient(new DVector(coordinates, false))).Handle;
  }

  public delegate double SwigDelegateDifferentiableFunction_0(global::System.IntPtr coordinates);
  public delegate global::System.IntPtr SwigDelegateDifferentiableFunction_1(global::System.IntPtr coordinates);

  private SwigDelegateDifferentiableFunction_0 swigDelegate0;
  private SwigDelegateDifferentiableFunction_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(DVector) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(DVector) };
}
