//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DVectorPair : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DVectorPair(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DVectorPair obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DVectorPair obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DVectorPair() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_DVectorPair(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DVectorPair() : this(datamungePINVOKE.new_DVectorPair__SWIG_0(), true) {
  }

  public DVectorPair(DVector first, DVector second) : this(datamungePINVOKE.new_DVectorPair__SWIG_1(DVector.getCPtr(first), DVector.getCPtr(second)), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public DVectorPair(DVectorPair other) : this(datamungePINVOKE.new_DVectorPair__SWIG_2(DVectorPair.getCPtr(other)), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public DVector first {
    set {
      datamungePINVOKE.DVectorPair_first_set(swigCPtr, DVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = datamungePINVOKE.DVectorPair_first_get(swigCPtr);
      DVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DVector(cPtr, false);
      return ret;
    } 
  }

  public DVector second {
    set {
      datamungePINVOKE.DVectorPair_second_set(swigCPtr, DVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = datamungePINVOKE.DVectorPair_second_get(swigCPtr);
      DVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DVector(cPtr, false);
      return ret;
    } 
  }

}
