//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class EstimationOfDistributionOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EstimationOfDistributionOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EstimationOfDistributionOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EstimationOfDistributionOptions obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~EstimationOfDistributionOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_EstimationOfDistributionOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>Lambda: candidates sampled from the Gaussian model each generation.</summary>
  public uint population_size {
    set {
      datamungePINVOKE.EstimationOfDistributionOptions_population_size_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.EstimationOfDistributionOptions_population_size_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Fraction of population_size kept as "elite" each generation to re-estimate the        Gaussian from; mu = max(2, ceil(population_size * selection_ratio)).</summary>
  public double selection_ratio {
    set {
      datamungePINVOKE.EstimationOfDistributionOptions_selection_ratio_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.EstimationOfDistributionOptions_selection_ratio_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Per-dimension standard deviation of the initial diagonal covariance.</summary>
  public double initial_std_dev {
    set {
      datamungePINVOKE.EstimationOfDistributionOptions_initial_std_dev_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.EstimationOfDistributionOptions_initial_std_dev_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Diagonal regularization added to the re-estimated covariance every generation, to        keep it numerically well-conditioned (needed whenever mu &lt;= dimension, or whenever        the elite set happens to be nearly coplanar).</summary>
  public double covariance_regularization {
    set {
      datamungePINVOKE.EstimationOfDistributionOptions_covariance_regularization_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.EstimationOfDistributionOptions_covariance_regularization_get(swigCPtr);
      return ret;
    } 
  }

  public uint max_generations {
    set {
      datamungePINVOKE.EstimationOfDistributionOptions_max_generations_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.EstimationOfDistributionOptions_max_generations_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Stops after the best-ever value has improved by less than this for 20 consecutive        generations, or once the covariance has collapsed to near-zero.</summary>
  public double tolerance {
    set {
      datamungePINVOKE.EstimationOfDistributionOptions_tolerance_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.EstimationOfDistributionOptions_tolerance_get(swigCPtr);
      return ret;
    } 
  }

  public ulong seed {
    set {
      datamungePINVOKE.EstimationOfDistributionOptions_seed_set(swigCPtr, value);
    } 
    get {
      ulong ret = datamungePINVOKE.EstimationOfDistributionOptions_seed_get(swigCPtr);
      return ret;
    } 
  }

  public EstimationOfDistributionOptions() : this(datamungePINVOKE.new_EstimationOfDistributionOptions(), true) {
  }

}
