//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class GibbsResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GibbsResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GibbsResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(GibbsResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~GibbsResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_GibbsResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>Post-warmup draws, one vector&lt;double&gt; per sample.</summary>
  public DVectorVector samples {
    set {
      datamungePINVOKE.GibbsResult_samples_set(swigCPtr, DVectorVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = datamungePINVOKE.GibbsResult_samples_get(swigCPtr);
      DVectorVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DVectorVector(cPtr, false);
      return ret;
    } 
  }

  /// <summary>Mean acceptance rate per coordinate (across all iterations), in parameter order.</summary>
  public DVector accept_rates {
    set {
      datamungePINVOKE.GibbsResult_accept_rates_set(swigCPtr, DVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = datamungePINVOKE.GibbsResult_accept_rates_get(swigCPtr);
      DVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DVector(cPtr, false);
      return ret;
    } 
  }

  public DVector final_step_sizes {
    set {
      datamungePINVOKE.GibbsResult_final_step_sizes_set(swigCPtr, DVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = datamungePINVOKE.GibbsResult_final_step_sizes_get(swigCPtr);
      DVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DVector(cPtr, false);
      return ret;
    } 
  }

  public GibbsResult() : this(datamungePINVOKE.new_GibbsResult(), true) {
  }

}
