//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>SWIG-friendly facade for datamunge::autodiff::HyperDual -- a second-order        forward-mode dual number carrying two independent derivative directions plus        their exact mixed second partial, for computing Hessian entries.</summary>

public class HyperDual : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HyperDual(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HyperDual obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(HyperDual obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~HyperDual() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_HyperDual(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public HyperDual(double value, double eps1, double eps2, double eps1eps2) : this(datamungePINVOKE.new_HyperDual__SWIG_0(value, eps1, eps2, eps1eps2), true) {
  }

  public HyperDual(double value, double eps1, double eps2) : this(datamungePINVOKE.new_HyperDual__SWIG_1(value, eps1, eps2), true) {
  }

  public HyperDual(double value, double eps1) : this(datamungePINVOKE.new_HyperDual__SWIG_2(value, eps1), true) {
  }

  public HyperDual(double value) : this(datamungePINVOKE.new_HyperDual__SWIG_3(value), true) {
  }

  public double value() {
    double ret = datamungePINVOKE.HyperDual_value(swigCPtr);
    return ret;
  }

  public double eps1() {
    double ret = datamungePINVOKE.HyperDual_eps1(swigCPtr);
    return ret;
  }

  public double eps2() {
    double ret = datamungePINVOKE.HyperDual_eps2(swigCPtr);
    return ret;
  }

  public double eps1eps2() {
    double ret = datamungePINVOKE.HyperDual_eps1eps2(swigCPtr);
    return ret;
  }

  public HyperDual add(HyperDual other) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_add(swigCPtr, HyperDual.getCPtr(other)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public HyperDual subtract(HyperDual other) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_subtract(swigCPtr, HyperDual.getCPtr(other)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public HyperDual multiply(HyperDual other) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_multiply(swigCPtr, HyperDual.getCPtr(other)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public HyperDual divide(HyperDual other) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_divide(swigCPtr, HyperDual.getCPtr(other)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public HyperDual negate() {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_negate(swigCPtr), true);
    return ret;
  }

  public HyperDual add_scalar(double scalar) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_add_scalar(swigCPtr, scalar), true);
    return ret;
  }

  public HyperDual subtract_scalar(double scalar) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_subtract_scalar(swigCPtr, scalar), true);
    return ret;
  }

  public HyperDual multiply_scalar(double scalar) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_multiply_scalar(swigCPtr, scalar), true);
    return ret;
  }

  public HyperDual divide_scalar(double scalar) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_divide_scalar(swigCPtr, scalar), true);
    return ret;
  }

  public HyperDual pow(double exponent) {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_pow(swigCPtr, exponent), true);
    return ret;
  }

  public HyperDual exp() {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_exp(swigCPtr), true);
    return ret;
  }

  public HyperDual log() {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_log(swigCPtr), true);
    return ret;
  }

  public HyperDual sqrt() {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_sqrt(swigCPtr), true);
    return ret;
  }

  public HyperDual sin() {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_sin(swigCPtr), true);
    return ret;
  }

  public HyperDual cos() {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_cos(swigCPtr), true);
    return ret;
  }

  public HyperDual tan() {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_tan(swigCPtr), true);
    return ret;
  }

  public HyperDual tanh() {
    HyperDual ret = new HyperDual(datamungePINVOKE.HyperDual_tanh(swigCPtr), true);
    return ret;
  }

}
