//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>SWIG-friendly facade for datamunge::stats::KernelPCA — principal component analysis        generalized to a nonlinear feature space via the kernel trick. With a linear kernel it        reproduces plain unscaled PCA's scores (up to a sign flip per component).</summary>

public class KernelPCA : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal KernelPCA(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KernelPCA obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(KernelPCA obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~KernelPCA() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_KernelPCA(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <param name="kernel"> One of "linear", "rbf" (default), "polynomial".</param>
  public KernelPCA(DataFrame data, SVector feature_columns, uint n_components, string kernel, double gamma, double degree, double coef0) : this(datamungePINVOKE.new_KernelPCA__SWIG_0(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, kernel, gamma, degree, coef0), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="kernel"> One of "linear", "rbf" (default), "polynomial".</param>
  public KernelPCA(DataFrame data, SVector feature_columns, uint n_components, string kernel, double gamma, double degree) : this(datamungePINVOKE.new_KernelPCA__SWIG_1(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, kernel, gamma, degree), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="kernel"> One of "linear", "rbf" (default), "polynomial".</param>
  public KernelPCA(DataFrame data, SVector feature_columns, uint n_components, string kernel, double gamma) : this(datamungePINVOKE.new_KernelPCA__SWIG_2(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, kernel, gamma), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="kernel"> One of "linear", "rbf" (default), "polynomial".</param>
  public KernelPCA(DataFrame data, SVector feature_columns, uint n_components, string kernel) : this(datamungePINVOKE.new_KernelPCA__SWIG_3(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, kernel), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public KernelPCA(DataFrame data, SVector feature_columns, uint n_components) : this(datamungePINVOKE.new_KernelPCA__SWIG_4(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public KernelPCA(DataFrame data, SVector feature_columns) : this(datamungePINVOKE.new_KernelPCA__SWIG_5(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns)), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public KernelPCA(DataFrame data, string encoded_feature_columns, uint n_components, string kernel, double gamma, double degree, double coef0) : this(datamungePINVOKE.new_KernelPCA__SWIG_6(DataFrame.getCPtr(data), encoded_feature_columns, n_components, kernel, gamma, degree, coef0), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public KernelPCA(DataFrame data, string encoded_feature_columns, uint n_components, string kernel, double gamma, double degree) : this(datamungePINVOKE.new_KernelPCA__SWIG_7(DataFrame.getCPtr(data), encoded_feature_columns, n_components, kernel, gamma, degree), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public KernelPCA(DataFrame data, string encoded_feature_columns, uint n_components, string kernel, double gamma) : this(datamungePINVOKE.new_KernelPCA__SWIG_8(DataFrame.getCPtr(data), encoded_feature_columns, n_components, kernel, gamma), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public KernelPCA(DataFrame data, string encoded_feature_columns, uint n_components, string kernel) : this(datamungePINVOKE.new_KernelPCA__SWIG_9(DataFrame.getCPtr(data), encoded_feature_columns, n_components, kernel), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public KernelPCA(DataFrame data, string encoded_feature_columns, uint n_components) : this(datamungePINVOKE.new_KernelPCA__SWIG_10(DataFrame.getCPtr(data), encoded_feature_columns, n_components), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public KernelPCA(DataFrame data, string encoded_feature_columns) : this(datamungePINVOKE.new_KernelPCA__SWIG_11(DataFrame.getCPtr(data), encoded_feature_columns), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public SVector feature_names() {
    SVector ret = new SVector(datamungePINVOKE.KernelPCA_feature_names(swigCPtr), true);
    return ret;
  }

  public uint observations() {
    uint ret = datamungePINVOKE.KernelPCA_observations(swigCPtr);
    return ret;
  }

  public uint n_components() {
    uint ret = datamungePINVOKE.KernelPCA_n_components(swigCPtr);
    return ret;
  }

  public SizeVector kept_row_indices() {
    SizeVector ret = new SizeVector(datamungePINVOKE.KernelPCA_kept_row_indices(swigCPtr), true);
    return ret;
  }

  public DVector eigenvalues() {
    DVector ret = new DVector(datamungePINVOKE.KernelPCA_eigenvalues(swigCPtr), true);
    return ret;
  }

  public DVector dimension(uint index) {
    DVector ret = new DVector(datamungePINVOKE.KernelPCA_dimension(swigCPtr, index), true);
    return ret;
  }

  public DataFrame embedding_frame() {
    global::System.IntPtr cPtr = datamungePINVOKE.KernelPCA_embedding_frame(swigCPtr);
    DataFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataFrame(cPtr, false);
    return ret;
  }

  public string summary() {
    string ret = datamungePINVOKE.KernelPCA_summary(swigCPtr);
    return ret;
  }

  public void print_summary() {
    datamungePINVOKE.KernelPCA_print_summary(swigCPtr);
  }

  public RPlot plot_embedding(uint dimension_x, uint dimension_y) {
    RPlot ret = new RPlot(datamungePINVOKE.KernelPCA_plot_embedding__SWIG_0(swigCPtr, dimension_x, dimension_y), true);
    return ret;
  }

  public RPlot plot_embedding(uint dimension_x) {
    RPlot ret = new RPlot(datamungePINVOKE.KernelPCA_plot_embedding__SWIG_1(swigCPtr, dimension_x), true);
    return ret;
  }

  public RPlot plot_embedding() {
    RPlot ret = new RPlot(datamungePINVOKE.KernelPCA_plot_embedding__SWIG_2(swigCPtr), true);
    return ret;
  }

  public RPlot plot_embedding_grouped(SVector group_labels, uint dimension_x, uint dimension_y) {
    RPlot ret = new RPlot(datamungePINVOKE.KernelPCA_plot_embedding_grouped__SWIG_0(swigCPtr, SVector.getCPtr(group_labels), dimension_x, dimension_y), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RPlot plot_embedding_grouped(SVector group_labels, uint dimension_x) {
    RPlot ret = new RPlot(datamungePINVOKE.KernelPCA_plot_embedding_grouped__SWIG_1(swigCPtr, SVector.getCPtr(group_labels), dimension_x), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RPlot plot_embedding_grouped(SVector group_labels) {
    RPlot ret = new RPlot(datamungePINVOKE.KernelPCA_plot_embedding_grouped__SWIG_2(swigCPtr, SVector.getCPtr(group_labels)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
