//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>SWIG-friendly facade for datamunge::stats::Lasso — pure L1-penalized ("lasso") regression, a special        case of ElasticNet with alpha fixed to 1. Can shrink coefficients exactly to zero, performing        variable selection.</summary>

public class Lasso : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Lasso(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Lasso obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Lasso obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Lasso() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_Lasso(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Lasso(DataFrame data, string formula, double lambda, uint n_lambda, uint cv_folds, bool standardize, ulong seed) : this(datamungePINVOKE.new_Lasso__SWIG_0(DataFrame.getCPtr(data), formula, lambda, n_lambda, cv_folds, standardize, seed), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public Lasso(DataFrame data, string formula, double lambda, uint n_lambda, uint cv_folds, bool standardize) : this(datamungePINVOKE.new_Lasso__SWIG_1(DataFrame.getCPtr(data), formula, lambda, n_lambda, cv_folds, standardize), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public Lasso(DataFrame data, string formula, double lambda, uint n_lambda, uint cv_folds) : this(datamungePINVOKE.new_Lasso__SWIG_2(DataFrame.getCPtr(data), formula, lambda, n_lambda, cv_folds), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public Lasso(DataFrame data, string formula, double lambda, uint n_lambda) : this(datamungePINVOKE.new_Lasso__SWIG_3(DataFrame.getCPtr(data), formula, lambda, n_lambda), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public Lasso(DataFrame data, string formula, double lambda) : this(datamungePINVOKE.new_Lasso__SWIG_4(DataFrame.getCPtr(data), formula, lambda), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public Lasso(DataFrame data, string formula) : this(datamungePINVOKE.new_Lasso__SWIG_5(DataFrame.getCPtr(data), formula), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public string formula_text() {
    string ret = datamungePINVOKE.Lasso_formula_text(swigCPtr);
    return ret;
  }

  public bool has_intercept() {
    bool ret = datamungePINVOKE.Lasso_has_intercept(swigCPtr);
    return ret;
  }

  public SVector predictor_names() {
    SVector ret = new SVector(datamungePINVOKE.Lasso_predictor_names(swigCPtr), true);
    return ret;
  }

  public uint observations() {
    uint ret = datamungePINVOKE.Lasso_observations(swigCPtr);
    return ret;
  }

  public double lambda() {
    double ret = datamungePINVOKE.Lasso_lambda(swigCPtr);
    return ret;
  }

  public bool lambda_was_selected() {
    bool ret = datamungePINVOKE.Lasso_lambda_was_selected(swigCPtr);
    return ret;
  }

  public DVector lambda_path() {
    DVector ret = new DVector(datamungePINVOKE.Lasso_lambda_path(swigCPtr), true);
    return ret;
  }

  public DVector cv_mean_squared_error() {
    DVector ret = new DVector(datamungePINVOKE.Lasso_cv_mean_squared_error(swigCPtr), true);
    return ret;
  }

  public DVector coefficients() {
    DVector ret = new DVector(datamungePINVOKE.Lasso_coefficients(swigCPtr), true);
    return ret;
  }

  public double intercept() {
    double ret = datamungePINVOKE.Lasso_intercept(swigCPtr);
    return ret;
  }

  public uint non_zero_coefficients() {
    uint ret = datamungePINVOKE.Lasso_non_zero_coefficients(swigCPtr);
    return ret;
  }

  public DVector fitted_values() {
    DVector ret = new DVector(datamungePINVOKE.Lasso_fitted_values(swigCPtr), true);
    return ret;
  }

  public DVector residuals() {
    DVector ret = new DVector(datamungePINVOKE.Lasso_residuals(swigCPtr), true);
    return ret;
  }

  public double r_squared() {
    double ret = datamungePINVOKE.Lasso_r_squared(swigCPtr);
    return ret;
  }

  public double rmse() {
    double ret = datamungePINVOKE.Lasso_rmse(swigCPtr);
    return ret;
  }

  public string summary() {
    string ret = datamungePINVOKE.Lasso_summary(swigCPtr);
    return ret;
  }

  public void print_summary() {
    datamungePINVOKE.Lasso_print_summary(swigCPtr);
  }

  public DVector predict(DataFrame newdata) {
    DVector ret = new DVector(datamungePINVOKE.Lasso_predict(swigCPtr, DataFrame.getCPtr(newdata)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RPlot plot_coefficient_path() {
    RPlot ret = new RPlot(datamungePINVOKE.Lasso_plot_coefficient_path(swigCPtr), true);
    return ret;
  }

  public RPlot plot_cv_curve() {
    RPlot ret = new RPlot(datamungePINVOKE.Lasso_plot_cv_curve(swigCPtr), true);
    return ret;
  }

  public RPlot plot_predicted_vs_actual() {
    RPlot ret = new RPlot(datamungePINVOKE.Lasso_plot_predicted_vs_actual(swigCPtr), true);
    return ret;
  }

  public RPlot plot_residuals_vs_fitted() {
    RPlot ret = new RPlot(datamungePINVOKE.Lasso_plot_residuals_vs_fitted(swigCPtr), true);
    return ret;
  }

}
