//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>SWIG-friendly facade for datamunge::stats::LDA — R-`MASS::lda()`-style linear discriminant analysis.</summary>

public class LDA : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LDA(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LDA obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LDA obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LDA() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_LDA(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <param name="priors"> Optional class prior probabilities (must sum to 1, ordered as classes() once sorted
  ///                    alphabetically); pass an empty vector (the default) to use observed class proportions.</param>
  public LDA(DataFrame data, string formula, DVector priors) : this(datamungePINVOKE.new_LDA__SWIG_0(DataFrame.getCPtr(data), formula, DVector.getCPtr(priors)), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public LDA(DataFrame data, string formula) : this(datamungePINVOKE.new_LDA__SWIG_1(DataFrame.getCPtr(data), formula), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public SVector classes() {
    SVector ret = new SVector(datamungePINVOKE.LDA_classes(swigCPtr), true);
    return ret;
  }

  public SVector predictor_names() {
    SVector ret = new SVector(datamungePINVOKE.LDA_predictor_names(swigCPtr), true);
    return ret;
  }

  public uint observations() {
    uint ret = datamungePINVOKE.LDA_observations(swigCPtr);
    return ret;
  }

  public uint num_discriminants() {
    uint ret = datamungePINVOKE.LDA_num_discriminants(swigCPtr);
    return ret;
  }

  public DVector priors() {
    DVector ret = new DVector(datamungePINVOKE.LDA_priors(swigCPtr), true);
    return ret;
  }

  /// <summary>One row per class, one numeric column per predictor.</summary>
  public DataFrame group_means() {
    global::System.IntPtr cPtr = datamungePINVOKE.LDA_group_means(swigCPtr);
    DataFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataFrame(cPtr, false);
    return ret;
  }

  /// <summary>One row per predictor, one numeric column per linear discriminant (LD1, LD2, ...).</summary>
  public DataFrame scaling() {
    global::System.IntPtr cPtr = datamungePINVOKE.LDA_scaling(swigCPtr);
    DataFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataFrame(cPtr, false);
    return ret;
  }

  public DVector proportion_of_trace() {
    DVector ret = new DVector(datamungePINVOKE.LDA_proportion_of_trace(swigCPtr), true);
    return ret;
  }

  public double training_accuracy() {
    double ret = datamungePINVOKE.LDA_training_accuracy(swigCPtr);
    return ret;
  }

  /// <summary>"actual" column plus one numeric column per class (counts), both ordered as classes().</summary>
  public DataFrame confusion_matrix() {
    global::System.IntPtr cPtr = datamungePINVOKE.LDA_confusion_matrix(swigCPtr);
    DataFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataFrame(cPtr, false);
    return ret;
  }

  public string summary() {
    string ret = datamungePINVOKE.LDA_summary(swigCPtr);
    return ret;
  }

  public void print_summary() {
    datamungePINVOKE.LDA_print_summary(swigCPtr);
  }

  public SVector predict(DataFrame newdata) {
    SVector ret = new SVector(datamungePINVOKE.LDA_predict(swigCPtr, DataFrame.getCPtr(newdata)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>"class" column, LD1/LD2/... discriminant scores, and posterior_&lt;class&gt; probability columns.</summary>
  public DataFrame predict_frame(DataFrame newdata) {
    global::System.IntPtr cPtr = datamungePINVOKE.LDA_predict_frame(swigCPtr, DataFrame.getCPtr(newdata));
    DataFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataFrame(cPtr, false);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RPlot plot_discriminants() {
    RPlot ret = new RPlot(datamungePINVOKE.LDA_plot_discriminants(swigCPtr), true);
    return ret;
  }

  public void save_discriminant_plot(string path) {
    datamungePINVOKE.LDA_save_discriminant_plot(swigCPtr, path);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

}
