//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>SWIG-friendly facade for datamunge::stats::RandomForestRegressor — a bagged ensemble of CART regression        trees, each fit on a bootstrap sample with a random subset of predictors considered at every split.</summary>

public class RandomForestRegressor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RandomForestRegressor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RandomForestRegressor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RandomForestRegressor obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RandomForestRegressor() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_RandomForestRegressor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <param name="max_features"> 0 = auto (floor(number of predictors / 3)).</param>
  public RandomForestRegressor(DataFrame data, string formula, uint n_trees, uint max_depth, uint min_samples_split, uint min_samples_leaf, uint max_features, bool bootstrap, double sample_fraction, ulong seed) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_0(DataFrame.getCPtr(data), formula, n_trees, max_depth, min_samples_split, min_samples_leaf, max_features, bootstrap, sample_fraction, seed), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="max_features"> 0 = auto (floor(number of predictors / 3)).</param>
  public RandomForestRegressor(DataFrame data, string formula, uint n_trees, uint max_depth, uint min_samples_split, uint min_samples_leaf, uint max_features, bool bootstrap, double sample_fraction) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_1(DataFrame.getCPtr(data), formula, n_trees, max_depth, min_samples_split, min_samples_leaf, max_features, bootstrap, sample_fraction), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="max_features"> 0 = auto (floor(number of predictors / 3)).</param>
  public RandomForestRegressor(DataFrame data, string formula, uint n_trees, uint max_depth, uint min_samples_split, uint min_samples_leaf, uint max_features, bool bootstrap) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_2(DataFrame.getCPtr(data), formula, n_trees, max_depth, min_samples_split, min_samples_leaf, max_features, bootstrap), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="max_features"> 0 = auto (floor(number of predictors / 3)).</param>
  public RandomForestRegressor(DataFrame data, string formula, uint n_trees, uint max_depth, uint min_samples_split, uint min_samples_leaf, uint max_features) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_3(DataFrame.getCPtr(data), formula, n_trees, max_depth, min_samples_split, min_samples_leaf, max_features), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public RandomForestRegressor(DataFrame data, string formula, uint n_trees, uint max_depth, uint min_samples_split, uint min_samples_leaf) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_4(DataFrame.getCPtr(data), formula, n_trees, max_depth, min_samples_split, min_samples_leaf), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public RandomForestRegressor(DataFrame data, string formula, uint n_trees, uint max_depth, uint min_samples_split) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_5(DataFrame.getCPtr(data), formula, n_trees, max_depth, min_samples_split), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public RandomForestRegressor(DataFrame data, string formula, uint n_trees, uint max_depth) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_6(DataFrame.getCPtr(data), formula, n_trees, max_depth), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public RandomForestRegressor(DataFrame data, string formula, uint n_trees) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_7(DataFrame.getCPtr(data), formula, n_trees), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public RandomForestRegressor(DataFrame data, string formula) : this(datamungePINVOKE.new_RandomForestRegressor__SWIG_8(DataFrame.getCPtr(data), formula), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public SVector predictor_names() {
    SVector ret = new SVector(datamungePINVOKE.RandomForestRegressor_predictor_names(swigCPtr), true);
    return ret;
  }

  public uint observations() {
    uint ret = datamungePINVOKE.RandomForestRegressor_observations(swigCPtr);
    return ret;
  }

  public uint n_trees() {
    uint ret = datamungePINVOKE.RandomForestRegressor_n_trees(swigCPtr);
    return ret;
  }

  public uint max_features_used() {
    uint ret = datamungePINVOKE.RandomForestRegressor_max_features_used(swigCPtr);
    return ret;
  }

  public DVector feature_importance() {
    DVector ret = new DVector(datamungePINVOKE.RandomForestRegressor_feature_importance(swigCPtr), true);
    return ret;
  }

  public DVector fitted_values() {
    DVector ret = new DVector(datamungePINVOKE.RandomForestRegressor_fitted_values(swigCPtr), true);
    return ret;
  }

  public double r_squared() {
    double ret = datamungePINVOKE.RandomForestRegressor_r_squared(swigCPtr);
    return ret;
  }

  public double rmse() {
    double ret = datamungePINVOKE.RandomForestRegressor_rmse(swigCPtr);
    return ret;
  }

  public double oob_r_squared() {
    double ret = datamungePINVOKE.RandomForestRegressor_oob_r_squared(swigCPtr);
    return ret;
  }

  public double oob_rmse() {
    double ret = datamungePINVOKE.RandomForestRegressor_oob_rmse(swigCPtr);
    return ret;
  }

  public string summary() {
    string ret = datamungePINVOKE.RandomForestRegressor_summary(swigCPtr);
    return ret;
  }

  public void print_summary() {
    datamungePINVOKE.RandomForestRegressor_print_summary(swigCPtr);
  }

  public DVector predict(DataFrame newdata) {
    DVector ret = new DVector(datamungePINVOKE.RandomForestRegressor_predict(swigCPtr, DataFrame.getCPtr(newdata)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ScatterPlot plot_predicted_vs_actual() {
    ScatterPlot ret = new ScatterPlot(datamungePINVOKE.RandomForestRegressor_plot_predicted_vs_actual(swigCPtr), true);
    return ret;
  }

  public ScatterPlot plot_residuals_vs_fitted() {
    ScatterPlot ret = new ScatterPlot(datamungePINVOKE.RandomForestRegressor_plot_residuals_vs_fitted(swigCPtr), true);
    return ret;
  }

}
