//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>An objective that decomposes as a sum over num_functions() independent terms        (e.g. one term per training example). evaluate() defaults to summing every term,        but remains overridable for a more efficient full-objective computation.</summary>

public class SeparableFunction : ArbitraryFunction {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal SeparableFunction(global::System.IntPtr cPtr, bool cMemoryOwn) : base(datamungePINVOKE.SeparableFunction_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SeparableFunction obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SeparableFunction obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_SeparableFunction(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  /// <summary>The number of additive terms the objective decomposes into.</summary>
  public virtual uint num_functions() {
    uint ret = datamungePINVOKE.SeparableFunction_num_functions(swigCPtr);
    return ret;
  }

  /// <summary>Evaluates just term ``i`` of the objective at ``coordinates``.</summary>
  public virtual double evaluate_term(DVector coordinates, uint i) {
    double ret = datamungePINVOKE.SeparableFunction_evaluate_term(swigCPtr, DVector.getCPtr(coordinates), i);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override double evaluate(DVector coordinates) {
    double ret = (SwigDerivedClassHasMethod("evaluate", swigMethodTypes0) ? datamungePINVOKE.SeparableFunction_evaluateSwigExplicitSeparableFunction(swigCPtr, DVector.getCPtr(coordinates)) : datamungePINVOKE.SeparableFunction_evaluate(swigCPtr, DVector.getCPtr(coordinates)));
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SeparableFunction() : this(datamungePINVOKE.new_SeparableFunction(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("evaluate", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateSeparableFunction_0(SwigDirectorMethodevaluate);
    if (SwigDerivedClassHasMethod("num_functions", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateSeparableFunction_1(SwigDirectorMethodnum_functions);
    if (SwigDerivedClassHasMethod("evaluate_term", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateSeparableFunction_2(SwigDirectorMethodevaluate_term);
    datamungePINVOKE.SeparableFunction_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(SeparableFunction))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private double SwigDirectorMethodevaluate(global::System.IntPtr coordinates) {
    return evaluate(new DVector(coordinates, false));
  }

  private uint SwigDirectorMethodnum_functions() {
    return num_functions();
  }

  private double SwigDirectorMethodevaluate_term(global::System.IntPtr coordinates, uint i) {
    return evaluate_term(new DVector(coordinates, false), i);
  }

  public delegate double SwigDelegateSeparableFunction_0(global::System.IntPtr coordinates);
  public delegate uint SwigDelegateSeparableFunction_1();
  public delegate double SwigDelegateSeparableFunction_2(global::System.IntPtr coordinates, uint i);

  private SwigDelegateSeparableFunction_0 swigDelegate0;
  private SwigDelegateSeparableFunction_1 swigDelegate1;
  private SwigDelegateSeparableFunction_2 swigDelegate2;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(DVector) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(DVector), typeof(uint) };
}
