//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>Stochastic (mini-batch) gradient descent on a DifferentiableSeparableFunction: each        step updates coordinates from the average gradient of one shuffled mini-batch of        terms, rather than the full objective's gradient.</summary>

public class SGD : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SGD(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SGD obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SGD obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SGD() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_SGD(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SGD(SGDOptions options) : this(datamungePINVOKE.new_SGD__SWIG_0(SGDOptions.getCPtr(options)), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public SGD() : this(datamungePINVOKE.new_SGD__SWIG_1(), true) {
  }

  public double optimize(DifferentiableSeparableFunction function, DVector coordinates) {
    double ret = datamungePINVOKE.SGD_optimize(swigCPtr, DifferentiableSeparableFunction.getCPtr(function), DVector.getCPtr(coordinates));
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
