//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>SWIG-friendly facade for datamunge::stats::SVM — R-`e1071::svm()`-style multi-class SVM classification.</summary>

public class SVM : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SVM(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SVM obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SVM obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SVM() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_SVM(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <param name="kernel"> One of "linear", "polynomial", "radial" (default), "sigmoid".</param> 
  /// <param name="gamma">  <= 0 means "auto" = 1 / number of predictors.</param>
  public SVM(DataFrame data, string formula, string kernel, double cost, double gamma, double coef0, int degree, bool scale) : this(datamungePINVOKE.new_SVM__SWIG_0(DataFrame.getCPtr(data), formula, kernel, cost, gamma, coef0, degree, scale), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="kernel"> One of "linear", "polynomial", "radial" (default), "sigmoid".</param> 
  /// <param name="gamma">  <= 0 means "auto" = 1 / number of predictors.</param>
  public SVM(DataFrame data, string formula, string kernel, double cost, double gamma, double coef0, int degree) : this(datamungePINVOKE.new_SVM__SWIG_1(DataFrame.getCPtr(data), formula, kernel, cost, gamma, coef0, degree), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="kernel"> One of "linear", "polynomial", "radial" (default), "sigmoid".</param> 
  /// <param name="gamma">  <= 0 means "auto" = 1 / number of predictors.</param>
  public SVM(DataFrame data, string formula, string kernel, double cost, double gamma, double coef0) : this(datamungePINVOKE.new_SVM__SWIG_2(DataFrame.getCPtr(data), formula, kernel, cost, gamma, coef0), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="kernel"> One of "linear", "polynomial", "radial" (default), "sigmoid".</param> 
  /// <param name="gamma">  <= 0 means "auto" = 1 / number of predictors.</param>
  public SVM(DataFrame data, string formula, string kernel, double cost, double gamma) : this(datamungePINVOKE.new_SVM__SWIG_3(DataFrame.getCPtr(data), formula, kernel, cost, gamma), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="kernel"> One of "linear", "polynomial", "radial" (default), "sigmoid".</param>
  public SVM(DataFrame data, string formula, string kernel, double cost) : this(datamungePINVOKE.new_SVM__SWIG_4(DataFrame.getCPtr(data), formula, kernel, cost), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="kernel"> One of "linear", "polynomial", "radial" (default), "sigmoid".</param>
  public SVM(DataFrame data, string formula, string kernel) : this(datamungePINVOKE.new_SVM__SWIG_5(DataFrame.getCPtr(data), formula, kernel), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public SVM(DataFrame data, string formula) : this(datamungePINVOKE.new_SVM__SWIG_6(DataFrame.getCPtr(data), formula), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public SVector classes() {
    SVector ret = new SVector(datamungePINVOKE.SVM_classes(swigCPtr), true);
    return ret;
  }

  public SVector predictor_names() {
    SVector ret = new SVector(datamungePINVOKE.SVM_predictor_names(swigCPtr), true);
    return ret;
  }

  public uint observations() {
    uint ret = datamungePINVOKE.SVM_observations(swigCPtr);
    return ret;
  }

  public uint num_support_vectors() {
    uint ret = datamungePINVOKE.SVM_num_support_vectors(swigCPtr);
    return ret;
  }

  public double training_accuracy() {
    double ret = datamungePINVOKE.SVM_training_accuracy(swigCPtr);
    return ret;
  }

  /// <summary>"actual" column plus one numeric column per class (counts), both ordered as classes().</summary>
  public DataFrame confusion_matrix() {
    global::System.IntPtr cPtr = datamungePINVOKE.SVM_confusion_matrix(swigCPtr);
    DataFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataFrame(cPtr, false);
    return ret;
  }

  public string summary() {
    string ret = datamungePINVOKE.SVM_summary(swigCPtr);
    return ret;
  }

  public void print_summary() {
    datamungePINVOKE.SVM_print_summary(swigCPtr);
  }

  public SVector predict(DataFrame newdata) {
    SVector ret = new SVector(datamungePINVOKE.SVM_predict(swigCPtr, DataFrame.getCPtr(newdata)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>"class" column plus one numeric vote-count column per class (votes_&lt;class&gt;).</summary>
  public DataFrame predict_frame(DataFrame newdata) {
    global::System.IntPtr cPtr = datamungePINVOKE.SVM_predict_frame(swigCPtr, DataFrame.getCPtr(newdata));
    DataFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataFrame(cPtr, false);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
