//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TrustRegionNewtonOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TrustRegionNewtonOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TrustRegionNewtonOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TrustRegionNewtonOptions obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TrustRegionNewtonOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_TrustRegionNewtonOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double initial_radius {
    set {
      datamungePINVOKE.TrustRegionNewtonOptions_initial_radius_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.TrustRegionNewtonOptions_initial_radius_get(swigCPtr);
      return ret;
    } 
  }

  public double max_radius {
    set {
      datamungePINVOKE.TrustRegionNewtonOptions_max_radius_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.TrustRegionNewtonOptions_max_radius_get(swigCPtr);
      return ret;
    } 
  }

  public uint max_iterations {
    set {
      datamungePINVOKE.TrustRegionNewtonOptions_max_iterations_set(swigCPtr, value);
    } 
    get {
      uint ret = datamungePINVOKE.TrustRegionNewtonOptions_max_iterations_get(swigCPtr);
      return ret;
    } 
  }

  public double tolerance {
    set {
      datamungePINVOKE.TrustRegionNewtonOptions_tolerance_set(swigCPtr, value);
    } 
    get {
      double ret = datamungePINVOKE.TrustRegionNewtonOptions_tolerance_get(swigCPtr);
      return ret;
    } 
  }

  public TrustRegionNewtonOptions() : this(datamungePINVOKE.new_TrustRegionNewtonOptions(), true) {
  }

}
