//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>SWIG-friendly facade for datamunge::stats::UMAP — builds a fuzzy simplicial set (a        smoothly-calibrated, fuzzy-union-symmetrized k-nearest-neighbor graph) and optimizes a        low-dimensional embedding via cross-entropy minimization (attractive + negative-sampled        repulsive forces). A deliberately simplified but honest implementation -- see the real        class's own documentation for the two named simplifications.</summary>

public class UMAP : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UMAP(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UMAP obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(UMAP obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~UMAP() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_UMAP(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <param name="metric"> One of "euclidean" (default) or "manhattan".</param>
  public UMAP(DataFrame data, SVector feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations, double learning_rate, double negative_sample_rate, string metric, ulong seed) : this(datamungePINVOKE.new_UMAP__SWIG_0(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, n_neighbors, min_dist, max_iterations, learning_rate, negative_sample_rate, metric, seed), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <param name="metric"> One of "euclidean" (default) or "manhattan".</param>
  public UMAP(DataFrame data, SVector feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations, double learning_rate, double negative_sample_rate, string metric) : this(datamungePINVOKE.new_UMAP__SWIG_1(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, n_neighbors, min_dist, max_iterations, learning_rate, negative_sample_rate, metric), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public UMAP(DataFrame data, SVector feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations, double learning_rate, double negative_sample_rate) : this(datamungePINVOKE.new_UMAP__SWIG_2(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, n_neighbors, min_dist, max_iterations, learning_rate, negative_sample_rate), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public UMAP(DataFrame data, SVector feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations, double learning_rate) : this(datamungePINVOKE.new_UMAP__SWIG_3(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, n_neighbors, min_dist, max_iterations, learning_rate), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public UMAP(DataFrame data, SVector feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations) : this(datamungePINVOKE.new_UMAP__SWIG_4(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, n_neighbors, min_dist, max_iterations), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public UMAP(DataFrame data, SVector feature_columns, uint n_components, uint n_neighbors, double min_dist) : this(datamungePINVOKE.new_UMAP__SWIG_5(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, n_neighbors, min_dist), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public UMAP(DataFrame data, SVector feature_columns, uint n_components, uint n_neighbors) : this(datamungePINVOKE.new_UMAP__SWIG_6(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components, n_neighbors), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public UMAP(DataFrame data, SVector feature_columns, uint n_components) : this(datamungePINVOKE.new_UMAP__SWIG_7(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns), n_components), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// 
  public UMAP(DataFrame data, SVector feature_columns) : this(datamungePINVOKE.new_UMAP__SWIG_8(DataFrame.getCPtr(data), SVector.getCPtr(feature_columns)), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations, double learning_rate, double negative_sample_rate, string metric, ulong seed) : this(datamungePINVOKE.new_UMAP__SWIG_9(DataFrame.getCPtr(data), encoded_feature_columns, n_components, n_neighbors, min_dist, max_iterations, learning_rate, negative_sample_rate, metric, seed), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations, double learning_rate, double negative_sample_rate, string metric) : this(datamungePINVOKE.new_UMAP__SWIG_10(DataFrame.getCPtr(data), encoded_feature_columns, n_components, n_neighbors, min_dist, max_iterations, learning_rate, negative_sample_rate, metric), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations, double learning_rate, double negative_sample_rate) : this(datamungePINVOKE.new_UMAP__SWIG_11(DataFrame.getCPtr(data), encoded_feature_columns, n_components, n_neighbors, min_dist, max_iterations, learning_rate, negative_sample_rate), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations, double learning_rate) : this(datamungePINVOKE.new_UMAP__SWIG_12(DataFrame.getCPtr(data), encoded_feature_columns, n_components, n_neighbors, min_dist, max_iterations, learning_rate), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns, uint n_components, uint n_neighbors, double min_dist, uint max_iterations) : this(datamungePINVOKE.new_UMAP__SWIG_13(DataFrame.getCPtr(data), encoded_feature_columns, n_components, n_neighbors, min_dist, max_iterations), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns, uint n_components, uint n_neighbors, double min_dist) : this(datamungePINVOKE.new_UMAP__SWIG_14(DataFrame.getCPtr(data), encoded_feature_columns, n_components, n_neighbors, min_dist), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns, uint n_components, uint n_neighbors) : this(datamungePINVOKE.new_UMAP__SWIG_15(DataFrame.getCPtr(data), encoded_feature_columns, n_components, n_neighbors), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns, uint n_components) : this(datamungePINVOKE.new_UMAP__SWIG_16(DataFrame.getCPtr(data), encoded_feature_columns, n_components), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Same as the vector&lt;string&gt; constructor, but feature_columns is a single "&lt;count&gt;\x1e        col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.</summary>
  public UMAP(DataFrame data, string encoded_feature_columns) : this(datamungePINVOKE.new_UMAP__SWIG_17(DataFrame.getCPtr(data), encoded_feature_columns), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public SVector feature_names() {
    SVector ret = new SVector(datamungePINVOKE.UMAP_feature_names(swigCPtr), true);
    return ret;
  }

  public uint observations() {
    uint ret = datamungePINVOKE.UMAP_observations(swigCPtr);
    return ret;
  }

  public uint n_components() {
    uint ret = datamungePINVOKE.UMAP_n_components(swigCPtr);
    return ret;
  }

  public SizeVector kept_row_indices() {
    SizeVector ret = new SizeVector(datamungePINVOKE.UMAP_kept_row_indices(swigCPtr), true);
    return ret;
  }

  public DVector dimension(uint index) {
    DVector ret = new DVector(datamungePINVOKE.UMAP_dimension(swigCPtr, index), true);
    return ret;
  }

  public DataFrame embedding_frame() {
    global::System.IntPtr cPtr = datamungePINVOKE.UMAP_embedding_frame(swigCPtr);
    DataFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataFrame(cPtr, false);
    return ret;
  }

  /// <summary>Per-point sigma_i / rho_i from the smooth k-NN calibration -- mainly for diagnostics.</summary>
  public DVector sigmas() {
    DVector ret = new DVector(datamungePINVOKE.UMAP_sigmas(swigCPtr), true);
    return ret;
  }

  public DVector rhos() {
    DVector ret = new DVector(datamungePINVOKE.UMAP_rhos(swigCPtr), true);
    return ret;
  }

  public string summary() {
    string ret = datamungePINVOKE.UMAP_summary(swigCPtr);
    return ret;
  }

  public void print_summary() {
    datamungePINVOKE.UMAP_print_summary(swigCPtr);
  }

  public RPlot plot_embedding(uint dimension_x, uint dimension_y) {
    RPlot ret = new RPlot(datamungePINVOKE.UMAP_plot_embedding__SWIG_0(swigCPtr, dimension_x, dimension_y), true);
    return ret;
  }

  public RPlot plot_embedding(uint dimension_x) {
    RPlot ret = new RPlot(datamungePINVOKE.UMAP_plot_embedding__SWIG_1(swigCPtr, dimension_x), true);
    return ret;
  }

  public RPlot plot_embedding() {
    RPlot ret = new RPlot(datamungePINVOKE.UMAP_plot_embedding__SWIG_2(swigCPtr), true);
    return ret;
  }

  public RPlot plot_embedding_grouped(SVector group_labels, uint dimension_x, uint dimension_y) {
    RPlot ret = new RPlot(datamungePINVOKE.UMAP_plot_embedding_grouped__SWIG_0(swigCPtr, SVector.getCPtr(group_labels), dimension_x, dimension_y), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RPlot plot_embedding_grouped(SVector group_labels, uint dimension_x) {
    RPlot ret = new RPlot(datamungePINVOKE.UMAP_plot_embedding_grouped__SWIG_1(swigCPtr, SVector.getCPtr(group_labels), dimension_x), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RPlot plot_embedding_grouped(SVector group_labels) {
    RPlot ret = new RPlot(datamungePINVOKE.UMAP_plot_embedding_grouped__SWIG_2(swigCPtr, SVector.getCPtr(group_labels)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
