//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

/// <summary>SWIG-friendly facade for datamunge::autodiff::Var -- a handle into a Tape.</summary>

public class Var : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Var(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Var obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Var obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Var() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          datamungePINVOKE.delete_Var(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>Records a new independent leaf variable on ``tape``.</summary>
  public Var(Tape tape, double value) : this(datamungePINVOKE.new_Var(Tape.getCPtr(tape), value), true) {
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
  }

  public double value() {
    double ret = datamungePINVOKE.Var_value(swigCPtr);
    return ret;
  }

  public uint index() {
    uint ret = datamungePINVOKE.Var_index(swigCPtr);
    return ret;
  }

  public Var add(Var other) {
    Var ret = new Var(datamungePINVOKE.Var_add(swigCPtr, Var.getCPtr(other)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Var subtract(Var other) {
    Var ret = new Var(datamungePINVOKE.Var_subtract(swigCPtr, Var.getCPtr(other)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Var multiply(Var other) {
    Var ret = new Var(datamungePINVOKE.Var_multiply(swigCPtr, Var.getCPtr(other)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Var divide(Var other) {
    Var ret = new Var(datamungePINVOKE.Var_divide(swigCPtr, Var.getCPtr(other)), true);
    if (datamungePINVOKE.SWIGPendingException.Pending) throw datamungePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Var negate() {
    Var ret = new Var(datamungePINVOKE.Var_negate(swigCPtr), true);
    return ret;
  }

  public Var add_scalar(double scalar) {
    Var ret = new Var(datamungePINVOKE.Var_add_scalar(swigCPtr, scalar), true);
    return ret;
  }

  public Var subtract_scalar(double scalar) {
    Var ret = new Var(datamungePINVOKE.Var_subtract_scalar(swigCPtr, scalar), true);
    return ret;
  }

  public Var multiply_scalar(double scalar) {
    Var ret = new Var(datamungePINVOKE.Var_multiply_scalar(swigCPtr, scalar), true);
    return ret;
  }

  public Var divide_scalar(double scalar) {
    Var ret = new Var(datamungePINVOKE.Var_divide_scalar(swigCPtr, scalar), true);
    return ret;
  }

  public Var pow(double exponent) {
    Var ret = new Var(datamungePINVOKE.Var_pow(swigCPtr, exponent), true);
    return ret;
  }

  public Var exp() {
    Var ret = new Var(datamungePINVOKE.Var_exp(swigCPtr), true);
    return ret;
  }

  public Var log() {
    Var ret = new Var(datamungePINVOKE.Var_log(swigCPtr), true);
    return ret;
  }

  public Var sqrt() {
    Var ret = new Var(datamungePINVOKE.Var_sqrt(swigCPtr), true);
    return ret;
  }

  public Var sin() {
    Var ret = new Var(datamungePINVOKE.Var_sin(swigCPtr), true);
    return ret;
  }

  public Var cos() {
    Var ret = new Var(datamungePINVOKE.Var_cos(swigCPtr), true);
    return ret;
  }

  public Var tan() {
    Var ret = new Var(datamungePINVOKE.Var_tan(swigCPtr), true);
    return ret;
  }

  public Var tanh() {
    Var ret = new Var(datamungePINVOKE.Var_tanh(swigCPtr), true);
    return ret;
  }

  public Var abs() {
    Var ret = new Var(datamungePINVOKE.Var_abs(swigCPtr), true);
    return ret;
  }

}
