#include <gtest/gtest.h>

#include <datamunge/algebra/algebra.hpp>

using namespace datamunge::algebra;

namespace {
MultivariatePolynomial make_poly(int num_vars, std::vector<std::vector<int>> exponents, std::vector<double> coefs) {
    return MultivariatePolynomial(num_vars, exponents, coefs);
}
} // namespace

TEST(MultivariatePolynomial, EvaluateMatchesHandComputation) {
    // p(x, y) = 2xy + 3x - 1
    const MultivariatePolynomial p = make_poly(2, {{1, 1}, {1, 0}, {0, 0}}, {2.0, 3.0, -1.0});
    EXPECT_DOUBLE_EQ(p.evaluate({2.0, 3.0}), 2 * 2 * 3 + 3 * 2 - 1);
    EXPECT_EQ(p.num_terms(), 3);
}

TEST(MultivariatePolynomial, LikeTermsAreCombinedAndZeroTermsDropped) {
    const MultivariatePolynomial p = make_poly(1, {{2}, {2}, {0}}, {3.0, -3.0, 5.0});
    EXPECT_EQ(p.num_terms(), 1); // the two x^2 terms cancel
    EXPECT_DOUBLE_EQ(p.evaluate({100.0}), 5.0);
}

TEST(MultivariatePolynomial, AddSubtractMultiplyMatchEvaluationAtSamplePoints) {
    const MultivariatePolynomial p = make_poly(2, {{1, 0}, {0, 1}}, {1.0, 1.0});  // x + y
    const MultivariatePolynomial q = make_poly(2, {{1, 0}, {0, 0}}, {1.0, -1.0}); // x - 1

    const MultivariatePolynomial sum = p.add(q);
    const MultivariatePolynomial diff = p.subtract(q);
    const MultivariatePolynomial prod = p.multiply(q);

    for (double x : {0.5, 2.0}) {
        for (double y : {-1.0, 3.0}) {
            EXPECT_NEAR(sum.evaluate({x, y}), (x + y) + (x - 1), 1e-9);
            EXPECT_NEAR(diff.evaluate({x, y}), (x + y) - (x - 1), 1e-9);
            EXPECT_NEAR(prod.evaluate({x, y}), (x + y) * (x - 1), 1e-9);
        }
    }
}

TEST(MonomialOrder, LexPrefersHigherPowerOfFirstVariable) {
    const MultivariatePolynomial p = make_poly(2, {{2, 0}, {0, 5}}, {1.0, 1.0}); // x^2 + y^5
    EXPECT_EQ(p.leading_exponent(MonomialOrder::Lex), (std::vector<int>{2, 0}));
}

TEST(MonomialOrder, GrlexPrefersHigherTotalDegree) {
    const MultivariatePolynomial p = make_poly(2, {{2, 0}, {0, 5}}, {1.0, 1.0}); // x^2 + y^5
    EXPECT_EQ(p.leading_exponent(MonomialOrder::Grlex), (std::vector<int>{0, 5}));
}

TEST(MonomialOrder, GrevlexBreaksDegreeTiesByPreferringSmallerTrailingExponent) {
    // x^2*y (total degree 3) vs x*y^2 (total degree 3): grevlex prefers the one with a
    // SMALLER last-variable exponent, i.e. x^2*y.
    const MultivariatePolynomial p = make_poly(2, {{2, 1}, {1, 2}}, {1.0, 1.0});
    EXPECT_EQ(p.leading_exponent(MonomialOrder::Grevlex), (std::vector<int>{2, 1}));
}

TEST(GroebnerBasis, LinearSystemReducesToASingleSolutionForm) {
    // Ideal generated by (x + y - 3, x - y - 1) over Q[x,y] -- a linear system with the unique
    // solution x=2, y=1. A Groebner basis (lex order) for a zero-dimensional linear ideal in 2
    // variables should let us read off each variable's value by reducing x and y themselves.
    const MultivariatePolynomial g1 = make_poly(2, {{1, 0}, {0, 1}, {0, 0}}, {1.0, 1.0, -3.0});
    const MultivariatePolynomial g2 = make_poly(2, {{1, 0}, {0, 1}, {0, 0}}, {1.0, -1.0, -1.0});

    const auto basis = groebner_basis({g1, g2}, MonomialOrder::Lex);
    ASSERT_FALSE(basis.empty());

    // Every generator must reduce to zero against the computed basis (basis generates the same
    // ideal as the originals).
    EXPECT_TRUE(multivariate_reduce(g1, basis, MonomialOrder::Lex).is_zero());
    EXPECT_TRUE(multivariate_reduce(g2, basis, MonomialOrder::Lex).is_zero());

    // The true solution point must be a common root of every basis element.
    for (const auto& b : basis) EXPECT_NEAR(b.evaluate({2.0, 1.0}), 0.0, 1e-9);
}

TEST(GroebnerBasis, MembershipTestViaReduceToZero) {
    // Ideal <x^2 - y, x^3 - z> in Q[x,y,z]. x*y - z lies in the ideal (since y=x^2, z=x^3, so
    // x*y - z = x^3 - x^3 = 0 on the variety) -- verify normal-form reduction recognizes this.
    const MultivariatePolynomial g1 = make_poly(3, {{2, 0, 0}, {0, 1, 0}}, {1.0, -1.0});
    const MultivariatePolynomial g2 = make_poly(3, {{3, 0, 0}, {0, 0, 1}}, {1.0, -1.0});
    const auto basis = groebner_basis({g1, g2}, MonomialOrder::Grevlex);

    const MultivariatePolynomial member = make_poly(3, {{1, 1, 0}, {0, 0, 1}}, {1.0, -1.0}); // xy - z
    EXPECT_TRUE(multivariate_reduce(member, basis, MonomialOrder::Grevlex).is_zero());

    const MultivariatePolynomial non_member = make_poly(3, {{0, 0, 0}}, {1.0}); // the constant 1
    EXPECT_FALSE(multivariate_reduce(non_member, basis, MonomialOrder::Grevlex).is_zero());
}
