#include <gtest/gtest.h>

#include <datamunge/algorithms/schreier_sims.hpp>

#include <numeric>
#include <vector>

using namespace datamunge::algorithms;

namespace {

std::vector<int> cyclic_shift(int n) { // (0 1 2 ... n-1)
    std::vector<int> p(n);
    for (int i = 0; i < n; ++i) p[i] = (i + 1) % n;
    return p;
}
std::vector<int> transpose01(int n) { // (0 1)
    std::vector<int> p(n);
    std::iota(p.begin(), p.end(), 0);
    std::swap(p[0], p[1]);
    return p;
}
unsigned long long factorial(int n) {
    unsigned long long r = 1;
    for (int i = 2; i <= n; ++i) r *= i;
    return r;
}
std::vector<int> compose(const std::vector<int>& a, const std::vector<int>& b) {
    std::vector<int> r(b.size());
    for (std::size_t i = 0; i < b.size(); ++i) r[i] = a[b[i]];
    return r;
}

} // namespace

TEST(SchreierSims, SymmetricGroupOrder) {
    for (int n = 2; n <= 7; ++n) {
        const auto g = schreier_sims(n, {transpose01(n), cyclic_shift(n)});
        EXPECT_EQ(g.order, factorial(n)) << "S_" << n;
    }
}

TEST(SchreierSims, CyclicGroupOrder) {
    for (int n = 2; n <= 10; ++n) {
        const auto g = schreier_sims(n, {cyclic_shift(n)});
        EXPECT_EQ(g.order, static_cast<unsigned long long>(n)) << "C_" << n;
    }
}

TEST(SchreierSims, DihedralGroupOrder) {
    // D_4 on the square: rotation r = (0 1 2 3), reflection s = (0 1)(2 3).
    const std::vector<int> r = {1, 2, 3, 0};
    const std::vector<int> s = {1, 0, 3, 2};
    const auto             g = schreier_sims(4, {r, s});
    EXPECT_EQ(g.order, 8ull);
}

TEST(SchreierSims, TrivialAndSingleTransposition) {
    // Identity generator only -> trivial group.
    const auto triv = schreier_sims(4, {{0, 1, 2, 3}});
    EXPECT_EQ(triv.order, 1ull);
    // A single transposition generates a group of order 2.
    const auto g2 = schreier_sims(4, {{1, 0, 2, 3}});
    EXPECT_EQ(g2.order, 2ull);
}

TEST(SchreierSims, Membership) {
    const int  n = 5;
    const auto g = schreier_sims(n, {transpose01(n), cyclic_shift(n)}); // S_5
    // Every permutation is a member of S_5.
    std::vector<int> perm = {2, 4, 0, 1, 3};
    EXPECT_TRUE(bsgs_contains(g, perm));

    // Alternating group A_4 (order 12): generated by two 3-cycles.
    const std::vector<int> a = {1, 2, 0, 3}; // (0 1 2)
    const std::vector<int> b = {0, 2, 3, 1}; // (1 2 3)
    const auto             a4 = schreier_sims(4, {a, b});
    EXPECT_EQ(a4.order, 12ull);
    // A transposition (odd permutation) is NOT in A_4.
    EXPECT_FALSE(bsgs_contains(a4, {1, 0, 2, 3}));
    // A 3-cycle (even) IS in A_4.
    EXPECT_TRUE(bsgs_contains(a4, compose(a, b)));
}
