#pragma once

#include <datamunge/algebra/monomial_order.hpp>
#include <datamunge/algebra/multivariate_polynomial.hpp>

#include <algorithm>
#include <cstddef>
#include <utility>
#include <vector>

namespace datamunge::algebra {

namespace detail {

[[nodiscard]] inline std::vector<int> lcm_exponent(const std::vector<int>& a, const std::vector<int>& b) {
    std::vector<int> result(a.size());
    for (std::size_t i = 0; i < a.size(); ++i) result[i] = std::max(a[i], b[i]);
    return result;
}

[[nodiscard]] inline bool monomial_divides(const std::vector<int>& divisor, const std::vector<int>& dividend) {
    for (std::size_t i = 0; i < divisor.size(); ++i)
        if (divisor[i] > dividend[i]) return false;
    return true;
}

/// @brief S-polynomial of f and g: the combination that cancels their leading terms via the
///        LCM of their leading monomials -- Buchberger's algorithm's basic building block.
[[nodiscard]] inline MultivariatePolynomial s_polynomial(const MultivariatePolynomial& f, const MultivariatePolynomial& g, MonomialOrder order) {
    const auto lf = f.leading_exponent(order);
    const auto lg = g.leading_exponent(order);
    const auto lcm = lcm_exponent(lf, lg);
    const int n = f.num_variables();

    std::vector<int> exp_f(static_cast<std::size_t>(n)), exp_g(static_cast<std::size_t>(n));
    for (int i = 0; i < n; ++i) {
        const std::size_t si = static_cast<std::size_t>(i);
        exp_f[si] = lcm[si] - lf[si];
        exp_g[si] = lcm[si] - lg[si];
    }

    const MultivariatePolynomial mono_f(n, {exp_f}, {1.0 / f.leading_coefficient(order)});
    const MultivariatePolynomial mono_g(n, {exp_g}, {1.0 / g.leading_coefficient(order)});
    return f.multiply(mono_f).subtract(g.multiply(mono_g));
}

/// @brief Reduces p modulo `basis` (repeated division: subtract a multiple of whichever basis
///        element's leading term divides p's current leading term, moving undivided leading
///        terms into the remainder) until nothing is left, returning the remainder.
[[nodiscard]] inline MultivariatePolynomial reduce(MultivariatePolynomial p, const std::vector<MultivariatePolynomial>& basis, MonomialOrder order) {
    MultivariatePolynomial remainder(p.num_variables());
    while (!p.is_zero()) {
        const auto lp = p.leading_exponent(order);
        bool divided = false;
        for (const auto& g : basis) {
            if (g.is_zero()) continue;
            const auto lg = g.leading_exponent(order);
            if (!monomial_divides(lg, lp)) continue;

            const int n = p.num_variables();
            std::vector<int> exp(static_cast<std::size_t>(n));
            for (int i = 0; i < n; ++i) {
                const std::size_t si = static_cast<std::size_t>(i);
                exp[si] = lp[si] - lg[si];
            }
            const MultivariatePolynomial factor(n, {exp}, {p.leading_coefficient(order) / g.leading_coefficient(order)});
            p = p.subtract(g.multiply(factor));
            divided = true;
            break;
        }
        if (!divided) {
            const MultivariatePolynomial lead_term(p.num_variables(), {lp}, {p.leading_coefficient(order)});
            remainder = remainder.add(lead_term);
            p = p.subtract(lead_term);
        }
    }
    return remainder;
}

} // namespace detail

/// @brief Reduces p modulo `basis` under `order`, returning the remainder (the "normal form"
///        of p with respect to basis). Zero if and only if p lies in the ideal generated by a
///        Groebner basis `basis`.
[[nodiscard]] inline MultivariatePolynomial multivariate_reduce(const MultivariatePolynomial& p, const std::vector<MultivariatePolynomial>& basis, MonomialOrder order) {
    return detail::reduce(p, basis, order);
}

/// @brief Buchberger's algorithm: computes a Groebner basis of the ideal generated by
///        `generators` under `order`. Basic textbook form (no Buchberger-criterion
///        pair-skipping optimizations, matching this module's "simple, correct" scoping
///        elsewhere) -- reduces every S-polynomial against the CURRENT basis and appends any
///        nonzero remainder until no pair produces one.
[[nodiscard]] inline std::vector<MultivariatePolynomial> groebner_basis(std::vector<MultivariatePolynomial> generators, MonomialOrder order) {
    std::vector<MultivariatePolynomial> basis;
    for (auto& g : generators)
        if (!g.is_zero()) basis.push_back(std::move(g));

    std::vector<std::pair<std::size_t, std::size_t>> pairs;
    for (std::size_t i = 0; i < basis.size(); ++i)
        for (std::size_t j = i + 1; j < basis.size(); ++j) pairs.emplace_back(i, j);

    while (!pairs.empty()) {
        const auto [i, j] = pairs.back();
        pairs.pop_back();

        const MultivariatePolynomial s = detail::s_polynomial(basis[i], basis[j], order);
        const MultivariatePolynomial r = detail::reduce(s, basis, order);
        if (!r.is_zero()) {
            for (std::size_t k = 0; k < basis.size(); ++k) pairs.emplace_back(k, basis.size());
            basis.push_back(r);
        }
    }
    return basis;
}

} // namespace datamunge::algebra
