#pragma once

// Convenience umbrella header — includes all stats components.

#include <datamunge/stats/agglomerative_clustering.hpp>
#include <datamunge/stats/anova_test.hpp>
#include <datamunge/stats/arima.hpp>
#include <datamunge/stats/chi_squared_test.hpp>
#include <datamunge/stats/correlation_test.hpp>
#include <datamunge/stats/dbscan.hpp>
#include <datamunge/stats/decision_tree_classifier.hpp>
#include <datamunge/stats/decision_tree_regressor.hpp>
#include <datamunge/stats/elastic_net.hpp>
#include <datamunge/stats/exponential_smoothing.hpp>
#include <datamunge/stats/fisher_exact_test.hpp>
#include <datamunge/stats/formula.hpp>
#include <datamunge/stats/gaussian_process_regression.hpp>
#include <datamunge/stats/gbm_classifier.hpp>
#include <datamunge/stats/gbm_regressor.hpp>
#include <datamunge/stats/glm.hpp>
#include <datamunge/stats/glmm.hpp>
#include <datamunge/stats/hypothesis_test_result.hpp>
#include <datamunge/stats/kernel_regression.hpp>
#include <datamunge/stats/kmeans.hpp>
#include <datamunge/stats/knn_classifier.hpp>
#include <datamunge/stats/knn_regressor.hpp>
#include <datamunge/stats/ks_test.hpp>
#include <datamunge/stats/lda.hpp>
#include <datamunge/stats/lm.hpp>
#include <datamunge/stats/lmm.hpp>
#include <datamunge/stats/naive_bayes_classifier.hpp>
#include <datamunge/stats/normality_test.hpp>
#include <datamunge/stats/p_adjust.hpp>
#include <datamunge/stats/proportion_test.hpp>
#include <datamunge/stats/random_forest_classifier.hpp>
#include <datamunge/stats/random_forest_regressor.hpp>
#include <datamunge/stats/svm.hpp>
#include <datamunge/stats/t_test.hpp>
#include <datamunge/stats/variance_test.hpp>
#include <datamunge/stats/wilcoxon_test.hpp>
#include <datamunge/stats/xgboost_classifier.hpp>
#include <datamunge/stats/xgboost_regressor.hpp>
