#pragma once

// Umbrella header for datamunge::algorithms -- general combinatorial, graph, and string algorithms.

#include <datamunge/algorithms/aho_corasick.hpp>
#include <datamunge/algorithms/advanced_graph.hpp>
#include <datamunge/algorithms/arc_consistency.hpp>
#include <datamunge/algorithms/arithmetic_extra.hpp>
#include <datamunge/algorithms/bellman_ford.hpp>
#include <datamunge/algorithms/berlekamp.hpp>
#include <datamunge/algorithms/bicubic_interpolation.hpp>
#include <datamunge/algorithms/birkhoff_interpolation.hpp>
#include <datamunge/algorithms/bkm.hpp>
#include <datamunge/algorithms/borwein_pi.hpp>
#include <datamunge/algorithms/bitap.hpp>
#include <datamunge/algorithms/branch_and_bound.hpp>
#include <datamunge/algorithms/boyer_moore.hpp>
#include <datamunge/algorithms/blossom.hpp>
#include <datamunge/algorithms/chinese_remainder.hpp>
#include <datamunge/algorithms/comparison_sorts.hpp>
#include <datamunge/algorithms/counting_sort.hpp>
#include <datamunge/algorithms/cycle_detection.hpp>
#include <datamunge/algorithms/dijkstra.hpp>
#include <datamunge/algorithms/distribution_sorts.hpp>
#include <datamunge/algorithms/division.hpp>
#include <datamunge/algorithms/dpll.hpp>
#include <datamunge/algorithms/edmonds_karp.hpp>
#include <datamunge/algorithms/elementary.hpp>
#include <datamunge/algorithms/elementary_more.hpp>
#include <datamunge/algorithms/ellipsoid.hpp>
#include <datamunge/algorithms/exact_cover.hpp>
#include <datamunge/algorithms/exchange_sorts.hpp>
#include <datamunge/algorithms/extended_euclidean.hpp>
#include <datamunge/algorithms/floyd_warshall.hpp>
#include <datamunge/algorithms/filtered_back_projection.hpp>
#include <datamunge/algorithms/frank_wolfe.hpp>
#include <datamunge/algorithms/game_search.hpp>
#include <datamunge/algorithms/golden_section_search.hpp>
#include <datamunge/algorithms/graph_coloring.hpp>
#include <datamunge/algorithms/graph_connectivity.hpp>
#include <datamunge/algorithms/graph_hard.hpp>
#include <datamunge/algorithms/graph_layout.hpp>
#include <datamunge/algorithms/hopcroft_karp.hpp>
#include <datamunge/algorithms/hungarian.hpp>
#include <datamunge/algorithms/index_calculus.hpp>
#include <datamunge/algorithms/interpolation.hpp>
#include <datamunge/algorithms/kmp.hpp>
#include <datamunge/algorithms/knuth_bendix.hpp>
#include <datamunge/algorithms/kruskal.hpp>
#include <datamunge/algorithms/lanczos_resampling.hpp>
#include <datamunge/algorithms/lex_bfs.hpp>
#include <datamunge/algorithms/interpolation_extra.hpp>
#include <datamunge/algorithms/linear_algebra.hpp>
#include <datamunge/algorithms/linear_solvers.hpp>
#include <datamunge/algorithms/lll.hpp>
#include <datamunge/algorithms/manacher.hpp>
#include <datamunge/algorithms/matrix_chain.hpp>
#include <datamunge/algorithms/merge.hpp>
#include <datamunge/algorithms/miser.hpp>
#include <datamunge/algorithms/min_conflicts.hpp>
#include <datamunge/algorithms/miller_rabin.hpp>
#include <datamunge/algorithms/modular_exponentiation.hpp>
#include <datamunge/algorithms/multiplication.hpp>
#include <datamunge/algorithms/nesting.hpp>
#include <datamunge/algorithms/network_analysis.hpp>
#include <datamunge/algorithms/number_theory.hpp>
#include <datamunge/algorithms/number_theory_extra.hpp>
#include <datamunge/algorithms/number_theory_advanced.hpp>
#include <datamunge/algorithms/number_theory_more.hpp>
#include <datamunge/algorithms/odds_algorithm.hpp>
#include <datamunge/algorithms/ode.hpp>
#include <datamunge/algorithms/pde_solvers.hpp>
#include <datamunge/algorithms/permutations.hpp>
#include <datamunge/algorithms/phonetic.hpp>
#include <datamunge/algorithms/pi_and_cordic.hpp>
#include <datamunge/algorithms/pollard_kangaroo.hpp>
#include <datamunge/algorithms/pollard_rho.hpp>
#include <datamunge/algorithms/polynomial_gf.hpp>
#include <datamunge/algorithms/primality.hpp>
#include <datamunge/algorithms/prim.hpp>
#include <datamunge/algorithms/prufer.hpp>
#include <datamunge/algorithms/quadratic_sieve.hpp>
#include <datamunge/algorithms/rabin_karp.hpp>
#include <datamunge/algorithms/root_finding.hpp>
#include <datamunge/algorithms/rounding_functions.hpp>
#include <datamunge/algorithms/routing_batch.hpp>
#include <datamunge/algorithms/sieve_of_eratosthenes.hpp>
#include <datamunge/algorithms/simplex.hpp>
#include <datamunge/algorithms/sss_star.hpp>
#include <datamunge/algorithms/stone_sip.hpp>
#include <datamunge/algorithms/search_batch.hpp>
#include <datamunge/algorithms/schreier_sims.hpp>
#include <datamunge/algorithms/search_more.hpp>
#include <datamunge/algorithms/sequence_alignment.hpp>
#include <datamunge/algorithms/sorted_search.hpp>
#include <datamunge/algorithms/srt_division.hpp>
#include <datamunge/algorithms/sorting_dist.hpp>
#include <datamunge/algorithms/sorting_extra.hpp>
#include <datamunge/algorithms/sorting_hybrid.hpp>
#include <datamunge/algorithms/sparse_linalg.hpp>
#include <datamunge/algorithms/stable_matching.hpp>
#include <datamunge/algorithms/string_metrics.hpp>
#include <datamunge/algorithms/string_search_extra.hpp>
#include <datamunge/algorithms/subsequences.hpp>
#include <datamunge/algorithms/subset_sum.hpp>
#include <datamunge/algorithms/substrings.hpp>
#include <datamunge/algorithms/tarjan_lca.hpp>
#include <datamunge/algorithms/ternary_search.hpp>
#include <datamunge/algorithms/todd_coxeter.hpp>
#include <datamunge/algorithms/tricubic_interpolation.hpp>
#include <datamunge/algorithms/topological_sort.hpp>
#include <datamunge/algorithms/trigram_search.hpp>
#include <datamunge/algorithms/tour_search.hpp>
#include <datamunge/algorithms/uniform_binary_search.hpp>
#include <datamunge/algorithms/uniform_cost_search.hpp>
#include <datamunge/algorithms/wang_landau.hpp>
#include <datamunge/algorithms/z_algorithm.hpp>
