#pragma once

// Umbrella header for datamunge::algorithms -- general combinatorial, graph, and string algorithms.

#include <datamunge/algorithms/aho_corasick.hpp>
#include <datamunge/algorithms/advanced_graph.hpp>
#include <datamunge/algorithms/bellman_ford.hpp>
#include <datamunge/algorithms/boyer_moore.hpp>
#include <datamunge/algorithms/blossom.hpp>
#include <datamunge/algorithms/chinese_remainder.hpp>
#include <datamunge/algorithms/counting_sort.hpp>
#include <datamunge/algorithms/cycle_detection.hpp>
#include <datamunge/algorithms/dijkstra.hpp>
#include <datamunge/algorithms/edmonds_karp.hpp>
#include <datamunge/algorithms/extended_euclidean.hpp>
#include <datamunge/algorithms/floyd_warshall.hpp>
#include <datamunge/algorithms/graph_coloring.hpp>
#include <datamunge/algorithms/graph_layout.hpp>
#include <datamunge/algorithms/hopcroft_karp.hpp>
#include <datamunge/algorithms/hungarian.hpp>
#include <datamunge/algorithms/kmp.hpp>
#include <datamunge/algorithms/kruskal.hpp>
#include <datamunge/algorithms/manacher.hpp>
#include <datamunge/algorithms/miller_rabin.hpp>
#include <datamunge/algorithms/modular_exponentiation.hpp>
#include <datamunge/algorithms/network_analysis.hpp>
#include <datamunge/algorithms/number_theory.hpp>
#include <datamunge/algorithms/permutations.hpp>
#include <datamunge/algorithms/pollard_rho.hpp>
#include <datamunge/algorithms/prim.hpp>
#include <datamunge/algorithms/prufer.hpp>
#include <datamunge/algorithms/rabin_karp.hpp>
#include <datamunge/algorithms/root_finding.hpp>
#include <datamunge/algorithms/routing_batch.hpp>
#include <datamunge/algorithms/sieve_of_eratosthenes.hpp>
#include <datamunge/algorithms/search_batch.hpp>
#include <datamunge/algorithms/search_more.hpp>
#include <datamunge/algorithms/sequence_alignment.hpp>
#include <datamunge/algorithms/sorted_search.hpp>
#include <datamunge/algorithms/stable_matching.hpp>
#include <datamunge/algorithms/string_metrics.hpp>
#include <datamunge/algorithms/subsequences.hpp>
#include <datamunge/algorithms/substrings.hpp>
#include <datamunge/algorithms/tarjan_lca.hpp>
#include <datamunge/algorithms/topological_sort.hpp>
#include <datamunge/algorithms/tour_search.hpp>
#include <datamunge/algorithms/z_algorithm.hpp>
