#pragma once

// Schreier-Sims algorithm: a base and strong generating set (BSGS) for a
// permutation group, giving its order and a fast membership test.
//
// Permutations act on {0, 1, ..., n-1} and are represented by their image
// vector: perm[i] is the image of point i.

#include <cstdint>
#include <unordered_map>
#include <vector>

namespace datamunge::algorithms {

struct BSGS {
    int                                                    n{0};
    std::vector<int>                                       base;        // base points
    std::vector<std::unordered_map<int, std::vector<int>>> transversal; // level -> (point -> coset rep)
    unsigned long long                                     order{1};
};

// Compute a BSGS for the group generated by `generators` (each a permutation of
// degree n). The returned structure's `order` is the group order.
BSGS schreier_sims(int n, const std::vector<std::vector<int>>& generators);

// Membership: is `perm` an element of the group described by `g`?
bool bsgs_contains(const BSGS& g, const std::vector<int>& perm);

} // namespace datamunge::algorithms
