/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class AdaGradOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AdaGradOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdaGradOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AdaGradOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_AdaGradOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStep_size(double value) {
    datamungeJNI.AdaGradOptions_step_size_set(swigCPtr, this, value);
  }

  public double getStep_size() {
    return datamungeJNI.AdaGradOptions_step_size_get(swigCPtr, this);
  }

  /**
   *  Added inside the square root to keep early and zero-gradient updates finite.
   */
  public void setEpsilon(double value) {
    datamungeJNI.AdaGradOptions_epsilon_set(swigCPtr, this, value);
  }

  /**
   *  Added inside the square root to keep early and zero-gradient updates finite.
   */
  public double getEpsilon() {
    return datamungeJNI.AdaGradOptions_epsilon_get(swigCPtr, this);
  }

  public void setMax_iterations(long value) {
    datamungeJNI.AdaGradOptions_max_iterations_set(swigCPtr, this, value);
  }

  public long getMax_iterations() {
    return datamungeJNI.AdaGradOptions_max_iterations_get(swigCPtr, this);
  }

  public void setTolerance(double value) {
    datamungeJNI.AdaGradOptions_tolerance_set(swigCPtr, this, value);
  }

  public double getTolerance() {
    return datamungeJNI.AdaGradOptions_tolerance_get(swigCPtr, this);
  }

  public AdaGradOptions() {
    this(datamungeJNI.new_AdaGradOptions(), true);
  }

}
