/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class ARIMAOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ARIMAOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ARIMAOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ARIMAOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_ARIMAOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setP(long value) {
    datamungeJNI.ARIMAOptions_p_set(swigCPtr, this, value);
  }

  public long getP() {
    return datamungeJNI.ARIMAOptions_p_get(swigCPtr, this);
  }

  public void setD(long value) {
    datamungeJNI.ARIMAOptions_d_set(swigCPtr, this, value);
  }

  public long getD() {
    return datamungeJNI.ARIMAOptions_d_get(swigCPtr, this);
  }

  public void setQ(long value) {
    datamungeJNI.ARIMAOptions_q_set(swigCPtr, this, value);
  }

  public long getQ() {
    return datamungeJNI.ARIMAOptions_q_get(swigCPtr, this);
  }

  public void setSeasonal_p(long value) {
    datamungeJNI.ARIMAOptions_seasonal_p_set(swigCPtr, this, value);
  }

  public long getSeasonal_p() {
    return datamungeJNI.ARIMAOptions_seasonal_p_get(swigCPtr, this);
  }

  public void setSeasonal_d(long value) {
    datamungeJNI.ARIMAOptions_seasonal_d_set(swigCPtr, this, value);
  }

  public long getSeasonal_d() {
    return datamungeJNI.ARIMAOptions_seasonal_d_get(swigCPtr, this);
  }

  public void setSeasonal_q(long value) {
    datamungeJNI.ARIMAOptions_seasonal_q_set(swigCPtr, this, value);
  }

  public long getSeasonal_q() {
    return datamungeJNI.ARIMAOptions_seasonal_q_get(swigCPtr, this);
  }

  public void setSeasonal_period(long value) {
    datamungeJNI.ARIMAOptions_seasonal_period_set(swigCPtr, this, value);
  }

  public long getSeasonal_period() {
    return datamungeJNI.ARIMAOptions_seasonal_period_get(swigCPtr, this);
  }

  /**
   *  Fit an intercept (mean of the fully-differenced series). Only meaningful when<br>
   *         d == 0 &amp;&amp; seasonal_d == 0 -- matching R's arima(), a mean term is not fit on a<br>
   *         series that has already been differenced to stationarity.
   */
  public void setInclude_mean(boolean value) {
    datamungeJNI.ARIMAOptions_include_mean_set(swigCPtr, this, value);
  }

  /**
   *  Fit an intercept (mean of the fully-differenced series). Only meaningful when<br>
   *         d == 0 &amp;&amp; seasonal_d == 0 -- matching R's arima(), a mean term is not fit on a<br>
   *         series that has already been differenced to stationarity.
   */
  public boolean getInclude_mean() {
    return datamungeJNI.ARIMAOptions_include_mean_get(swigCPtr, this);
  }

  public void setDe_population_size(long value) {
    datamungeJNI.ARIMAOptions_de_population_size_set(swigCPtr, this, value);
  }

  public long getDe_population_size() {
    return datamungeJNI.ARIMAOptions_de_population_size_get(swigCPtr, this);
  }

  public void setDe_max_generations(long value) {
    datamungeJNI.ARIMAOptions_de_max_generations_set(swigCPtr, this, value);
  }

  public long getDe_max_generations() {
    return datamungeJNI.ARIMAOptions_de_max_generations_get(swigCPtr, this);
  }

  /**
   *  Box constraint applied to every AR/MA coefficient during optimization.
   */
  public void setCoefficient_bound(double value) {
    datamungeJNI.ARIMAOptions_coefficient_bound_set(swigCPtr, this, value);
  }

  /**
   *  Box constraint applied to every AR/MA coefficient during optimization.
   */
  public double getCoefficient_bound() {
    return datamungeJNI.ARIMAOptions_coefficient_bound_get(swigCPtr, this);
  }

  public void setSeed(java.math.BigInteger value) {
    datamungeJNI.ARIMAOptions_seed_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSeed() {
    return datamungeJNI.ARIMAOptions_seed_get(swigCPtr, this);
  }

  public ARIMAOptions() {
    this(datamungeJNI.new_ARIMAOptions(), true);
  }

}
