/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  Base class for user-defined callbacks invoked by datamunge functions.<br>
 * <br>
 *  Derive from this class and override <code>call()</code> to supply custom behavior<br>
 *  wherever a <code>Callback*</code> is accepted.
 */
public class Callback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Callback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Callback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Callback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_Callback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  Applies the callback to a single value.<br>
   *  @param x Input value.<br>
   *  @return Transformed value; the default implementation returns <code>x</code> unchanged.
   */
  public double call(double x) {
    return datamungeJNI.Callback_call(swigCPtr, this, x);
  }

  public Callback() {
    this(datamungeJNI.new_Callback(), true);
  }

}
