/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class DEOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DEOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DEOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DEOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_DEOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPopulation_size(long value) {
    datamungeJNI.DEOptions_population_size_set(swigCPtr, this, value);
  }

  public long getPopulation_size() {
    return datamungeJNI.DEOptions_population_size_get(swigCPtr, this);
  }

  public void setMax_generations(long value) {
    datamungeJNI.DEOptions_max_generations_set(swigCPtr, this, value);
  }

  public long getMax_generations() {
    return datamungeJNI.DEOptions_max_generations_get(swigCPtr, this);
  }

  /**
   *  F: scales the differential perturbation applied by the mutation strategy.
   */
  public void setDifferential_weight(double value) {
    datamungeJNI.DEOptions_differential_weight_set(swigCPtr, this, value);
  }

  /**
   *  F: scales the differential perturbation applied by the mutation strategy.
   */
  public double getDifferential_weight() {
    return datamungeJNI.DEOptions_differential_weight_get(swigCPtr, this);
  }

  /**
   *  CR: probability that a given gene is taken from the mutant vector.
   */
  public void setCrossover_rate(double value) {
    datamungeJNI.DEOptions_crossover_rate_set(swigCPtr, this, value);
  }

  /**
   *  CR: probability that a given gene is taken from the mutant vector.
   */
  public double getCrossover_rate() {
    return datamungeJNI.DEOptions_crossover_rate_get(swigCPtr, this);
  }

  /**
   *  One of "rand1", "best1", "current_to_best1", or "rand2" -- Storn &amp; Price's<br>
   *         DE/x/y/z naming for which base vector(s) the differential perturbation(s) are<br>
   *         added to.
   */
  public void setMutation_strategy(String value) {
    datamungeJNI.DEOptions_mutation_strategy_set(swigCPtr, this, value);
  }

  /**
   *  One of "rand1", "best1", "current_to_best1", or "rand2" -- Storn &amp; Price's<br>
   *         DE/x/y/z naming for which base vector(s) the differential perturbation(s) are<br>
   *         added to.
   */
  public String getMutation_strategy() {
    return datamungeJNI.DEOptions_mutation_strategy_get(swigCPtr, this);
  }

  /**
   *  One of "binomial" or "exponential".
   */
  public void setCrossover_strategy(String value) {
    datamungeJNI.DEOptions_crossover_strategy_set(swigCPtr, this, value);
  }

  /**
   *  One of "binomial" or "exponential".
   */
  public String getCrossover_strategy() {
    return datamungeJNI.DEOptions_crossover_strategy_get(swigCPtr, this);
  }

  /**
   *  Stops after the population best has improved by less than this for 20 consecutive generations.
   */
  public void setTolerance(double value) {
    datamungeJNI.DEOptions_tolerance_set(swigCPtr, this, value);
  }

  /**
   *  Stops after the population best has improved by less than this for 20 consecutive generations.
   */
  public double getTolerance() {
    return datamungeJNI.DEOptions_tolerance_get(swigCPtr, this);
  }

  public void setSeed(java.math.BigInteger value) {
    datamungeJNI.DEOptions_seed_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSeed() {
    return datamungeJNI.DEOptions_seed_get(swigCPtr, this);
  }

  public DEOptions() {
    this(datamungeJNI.new_DEOptions(), true);
  }

}
