/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  An objective function that additionally supports exact gradient evaluation.<br>
 *         Optimizers that consume this type (GradientDescent, Adam, LBFGS) use the full<br>
 *         gradient at every step.
 */
public class DifferentiableFunction extends ArbitraryFunction {
  private transient long swigCPtr;

  protected DifferentiableFunction(long cPtr, boolean cMemoryOwn) {
    super(datamungeJNI.DifferentiableFunction_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DifferentiableFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DifferentiableFunction obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_DifferentiableFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    datamungeJNI.DifferentiableFunction_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    datamungeJNI.DifferentiableFunction_change_ownership(this, swigCPtr, true);
  }

  /**
   *  Returns the gradient of the objective at <code>coordinates</code>.
   */
  public DVector gradient(DVector coordinates) {
    return new DVector(datamungeJNI.DifferentiableFunction_gradient(swigCPtr, this, DVector.getCPtr(coordinates), coordinates), true);
  }

  @SuppressWarnings("this-escape")
  public DifferentiableFunction() {
    this(datamungeJNI.new_DifferentiableFunction(), true);
    datamungeJNI.DifferentiableFunction_director_connect(this, swigCPtr, true, true);
  }

}
