/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class DVectorPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DVectorPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DVectorPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DVectorPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_DVectorPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DVectorPair() {
    this(datamungeJNI.new_DVectorPair__SWIG_0(), true);
  }

  public DVectorPair(DVector first, DVector second) {
    this(datamungeJNI.new_DVectorPair__SWIG_1(DVector.getCPtr(first), first, DVector.getCPtr(second), second), true);
  }

  public DVectorPair(DVectorPair other) {
    this(datamungeJNI.new_DVectorPair__SWIG_2(DVectorPair.getCPtr(other), other), true);
  }

  public void setFirst(DVector value) {
    datamungeJNI.DVectorPair_first_set(swigCPtr, this, DVector.getCPtr(value), value);
  }

  public DVector getFirst() {
    long cPtr = datamungeJNI.DVectorPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DVector(cPtr, false);
  }

  public void setSecond(DVector value) {
    datamungeJNI.DVectorPair_second_set(swigCPtr, this, DVector.getCPtr(value), value);
  }

  public DVector getSecond() {
    long cPtr = datamungeJNI.DVectorPair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DVector(cPtr, false);
  }

}
