/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  Smooth equality-constrained objective for constrained optimizers.
 */
public class EqualityConstrainedFunction extends DifferentiableFunction {
  private transient long swigCPtr;

  protected EqualityConstrainedFunction(long cPtr, boolean cMemoryOwn) {
    super(datamungeJNI.EqualityConstrainedFunction_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EqualityConstrainedFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EqualityConstrainedFunction obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_EqualityConstrainedFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    datamungeJNI.EqualityConstrainedFunction_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    datamungeJNI.EqualityConstrainedFunction_change_ownership(this, swigCPtr, true);
  }

  public DVector constraints(DVector coordinates) {
    return new DVector(datamungeJNI.EqualityConstrainedFunction_constraints(swigCPtr, this, DVector.getCPtr(coordinates), coordinates), true);
  }

  public DVectorVector constraint_jacobian(DVector coordinates) {
    return new DVectorVector(datamungeJNI.EqualityConstrainedFunction_constraint_jacobian(swigCPtr, this, DVector.getCPtr(coordinates), coordinates), true);
  }

  @SuppressWarnings("this-escape")
  public EqualityConstrainedFunction() {
    this(datamungeJNI.new_EqualityConstrainedFunction(), true);
    datamungeJNI.EqualityConstrainedFunction_director_connect(this, swigCPtr, true, true);
  }

}
