/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  Estimation of Distribution Algorithm (EMNA-style, full-covariance Gaussian) on an<br>
 *         ArbitraryFunction within a box constraint. Unlike explicit-operator methods (GA, DE)<br>
 *         or covariance-adapting methods (CMA-ES), EMNA builds an explicit multivariate Gaussian<br>
 *         model of where the good solutions are each generation -- re-estimating its mean and<br>
 *         covariance from scratch as the empirical mean/covariance of the current generation's<br>
 *         elite, with no smoothing or evolution paths -- and samples the next generation directly<br>
 *         from that model. Derivative-free.
 */
public class EstimationOfDistribution {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EstimationOfDistribution(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EstimationOfDistribution obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EstimationOfDistribution obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_EstimationOfDistribution(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EstimationOfDistribution(EstimationOfDistributionOptions options) {
    this(datamungeJNI.new_EstimationOfDistribution__SWIG_0(EstimationOfDistributionOptions.getCPtr(options), options), true);
  }

  public EstimationOfDistribution() {
    this(datamungeJNI.new_EstimationOfDistribution__SWIG_1(), true);
  }

  /**
   *  Minimizes <code>function</code> within [<code>lower_bound</code>, <code>upper_bound]</code>, updating<br>
   *         <code>coordinates</code> in place to the best point found, and returns its value. The<br>
   *         initial <code>coordinates</code> (clamped into bounds) seed the initial Gaussian mean.
   */
  public double optimize(ArbitraryFunction function, DVector coordinates, DVector lower_bound, DVector upper_bound) {
    return datamungeJNI.EstimationOfDistribution_optimize(swigCPtr, this, ArbitraryFunction.getCPtr(function), function, DVector.getCPtr(coordinates), coordinates, DVector.getCPtr(lower_bound), lower_bound, DVector.getCPtr(upper_bound), upper_bound);
  }

}
