/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class ExponentialSmoothingOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ExponentialSmoothingOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExponentialSmoothingOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ExponentialSmoothingOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_ExponentialSmoothingOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTrend(TrendType value) {
    datamungeJNI.ExponentialSmoothingOptions_trend_set(swigCPtr, this, value.swigValue());
  }

  public TrendType getTrend() {
    return TrendType.swigToEnum(datamungeJNI.ExponentialSmoothingOptions_trend_get(swigCPtr, this));
  }

  public void setSeasonal(SeasonalType value) {
    datamungeJNI.ExponentialSmoothingOptions_seasonal_set(swigCPtr, this, value.swigValue());
  }

  public SeasonalType getSeasonal() {
    return SeasonalType.swigToEnum(datamungeJNI.ExponentialSmoothingOptions_seasonal_get(swigCPtr, this));
  }

  public void setSeasonal_period(long value) {
    datamungeJNI.ExponentialSmoothingOptions_seasonal_period_set(swigCPtr, this, value);
  }

  public long getSeasonal_period() {
    return datamungeJNI.ExponentialSmoothingOptions_seasonal_period_get(swigCPtr, this);
  }

  public void setAlpha(double value) {
    datamungeJNI.ExponentialSmoothingOptions_alpha_set(swigCPtr, this, value);
  }

  public double getAlpha() {
    return datamungeJNI.ExponentialSmoothingOptions_alpha_get(swigCPtr, this);
  }

  public void setBeta(double value) {
    datamungeJNI.ExponentialSmoothingOptions_beta_set(swigCPtr, this, value);
  }

  public double getBeta() {
    return datamungeJNI.ExponentialSmoothingOptions_beta_get(swigCPtr, this);
  }

  public void setGamma(double value) {
    datamungeJNI.ExponentialSmoothingOptions_gamma_set(swigCPtr, this, value);
  }

  public double getGamma() {
    return datamungeJNI.ExponentialSmoothingOptions_gamma_get(swigCPtr, this);
  }

  public void setPhi(double value) {
    datamungeJNI.ExponentialSmoothingOptions_phi_set(swigCPtr, this, value);
  }

  public double getPhi() {
    return datamungeJNI.ExponentialSmoothingOptions_phi_get(swigCPtr, this);
  }

  public void setDe_population_size(long value) {
    datamungeJNI.ExponentialSmoothingOptions_de_population_size_set(swigCPtr, this, value);
  }

  public long getDe_population_size() {
    return datamungeJNI.ExponentialSmoothingOptions_de_population_size_get(swigCPtr, this);
  }

  public void setDe_max_generations(long value) {
    datamungeJNI.ExponentialSmoothingOptions_de_max_generations_set(swigCPtr, this, value);
  }

  public long getDe_max_generations() {
    return datamungeJNI.ExponentialSmoothingOptions_de_max_generations_get(swigCPtr, this);
  }

  public void setSeed(java.math.BigInteger value) {
    datamungeJNI.ExponentialSmoothingOptions_seed_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSeed() {
    return datamungeJNI.ExponentialSmoothingOptions_seed_get(swigCPtr, this);
  }

  public ExponentialSmoothingOptions() {
    this(datamungeJNI.new_ExponentialSmoothingOptions(), true);
  }

}
