/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class FireflyAlgorithmOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FireflyAlgorithmOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FireflyAlgorithmOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FireflyAlgorithmOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_FireflyAlgorithmOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPopulation_size(long value) {
    datamungeJNI.FireflyAlgorithmOptions_population_size_set(swigCPtr, this, value);
  }

  public long getPopulation_size() {
    return datamungeJNI.FireflyAlgorithmOptions_population_size_get(swigCPtr, this);
  }

  /**
   *  beta0: attractiveness at distance 0.
   */
  public void setAttractiveness_at_zero(double value) {
    datamungeJNI.FireflyAlgorithmOptions_attractiveness_at_zero_set(swigCPtr, this, value);
  }

  /**
   *  beta0: attractiveness at distance 0.
   */
  public double getAttractiveness_at_zero() {
    return datamungeJNI.FireflyAlgorithmOptions_attractiveness_at_zero_get(swigCPtr, this);
  }

  /**
   *  gamma: controls how fast attractiveness decays with distance.
   */
  public void setLight_absorption(double value) {
    datamungeJNI.FireflyAlgorithmOptions_light_absorption_set(swigCPtr, this, value);
  }

  /**
   *  gamma: controls how fast attractiveness decays with distance.
   */
  public double getLight_absorption() {
    return datamungeJNI.FireflyAlgorithmOptions_light_absorption_get(swigCPtr, this);
  }

  /**
   *  alpha: scale of the per-move random walk term.
   */
  public void setRandomization_step(double value) {
    datamungeJNI.FireflyAlgorithmOptions_randomization_step_set(swigCPtr, this, value);
  }

  /**
   *  alpha: scale of the per-move random walk term.
   */
  public double getRandomization_step() {
    return datamungeJNI.FireflyAlgorithmOptions_randomization_step_get(swigCPtr, this);
  }

  /**
   *  alpha is multiplied by this every iteration (geometric decay -- exploration<br>
   *         shrinks over time).
   */
  public void setRandomization_decay(double value) {
    datamungeJNI.FireflyAlgorithmOptions_randomization_decay_set(swigCPtr, this, value);
  }

  /**
   *  alpha is multiplied by this every iteration (geometric decay -- exploration<br>
   *         shrinks over time).
   */
  public double getRandomization_decay() {
    return datamungeJNI.FireflyAlgorithmOptions_randomization_decay_get(swigCPtr, this);
  }

  public void setMax_iterations(long value) {
    datamungeJNI.FireflyAlgorithmOptions_max_iterations_set(swigCPtr, this, value);
  }

  public long getMax_iterations() {
    return datamungeJNI.FireflyAlgorithmOptions_max_iterations_get(swigCPtr, this);
  }

  /**
   *  Stops after the best-ever value has improved by less than this for 20<br>
   *         consecutive iterations.
   */
  public void setTolerance(double value) {
    datamungeJNI.FireflyAlgorithmOptions_tolerance_set(swigCPtr, this, value);
  }

  /**
   *  Stops after the best-ever value has improved by less than this for 20<br>
   *         consecutive iterations.
   */
  public double getTolerance() {
    return datamungeJNI.FireflyAlgorithmOptions_tolerance_get(swigCPtr, this);
  }

  public void setSeed(java.math.BigInteger value) {
    datamungeJNI.FireflyAlgorithmOptions_seed_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSeed() {
    return datamungeJNI.FireflyAlgorithmOptions_seed_get(swigCPtr, this);
  }

  public FireflyAlgorithmOptions() {
    this(datamungeJNI.new_FireflyAlgorithmOptions(), true);
  }

}
