/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  SWIG-friendly facade for datamunge::stats::GBMRegressor — a sequence of shallow regression trees,<br>
 *         each fit to the residuals of the current ensemble (gradient boosting on squared error).
 */
public class GBMRegressor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GBMRegressor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GBMRegressor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GBMRegressor obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_GBMRegressor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GBMRegressor(DataFrame data, String formula, long n_trees, double learning_rate, long max_depth, long min_samples_split, long min_samples_leaf, double subsample, java.math.BigInteger seed) {
    this(datamungeJNI.new_GBMRegressor__SWIG_0(DataFrame.getCPtr(data), data, formula, n_trees, learning_rate, max_depth, min_samples_split, min_samples_leaf, subsample, seed), true);
  }

  public GBMRegressor(DataFrame data, String formula, long n_trees, double learning_rate, long max_depth, long min_samples_split, long min_samples_leaf, double subsample) {
    this(datamungeJNI.new_GBMRegressor__SWIG_1(DataFrame.getCPtr(data), data, formula, n_trees, learning_rate, max_depth, min_samples_split, min_samples_leaf, subsample), true);
  }

  public GBMRegressor(DataFrame data, String formula, long n_trees, double learning_rate, long max_depth, long min_samples_split, long min_samples_leaf) {
    this(datamungeJNI.new_GBMRegressor__SWIG_2(DataFrame.getCPtr(data), data, formula, n_trees, learning_rate, max_depth, min_samples_split, min_samples_leaf), true);
  }

  public GBMRegressor(DataFrame data, String formula, long n_trees, double learning_rate, long max_depth, long min_samples_split) {
    this(datamungeJNI.new_GBMRegressor__SWIG_3(DataFrame.getCPtr(data), data, formula, n_trees, learning_rate, max_depth, min_samples_split), true);
  }

  public GBMRegressor(DataFrame data, String formula, long n_trees, double learning_rate, long max_depth) {
    this(datamungeJNI.new_GBMRegressor__SWIG_4(DataFrame.getCPtr(data), data, formula, n_trees, learning_rate, max_depth), true);
  }

  public GBMRegressor(DataFrame data, String formula, long n_trees, double learning_rate) {
    this(datamungeJNI.new_GBMRegressor__SWIG_5(DataFrame.getCPtr(data), data, formula, n_trees, learning_rate), true);
  }

  public GBMRegressor(DataFrame data, String formula, long n_trees) {
    this(datamungeJNI.new_GBMRegressor__SWIG_6(DataFrame.getCPtr(data), data, formula, n_trees), true);
  }

  public GBMRegressor(DataFrame data, String formula) {
    this(datamungeJNI.new_GBMRegressor__SWIG_7(DataFrame.getCPtr(data), data, formula), true);
  }

  public SVector predictor_names() {
    return new SVector(datamungeJNI.GBMRegressor_predictor_names(swigCPtr, this), true);
  }

  public long observations() {
    return datamungeJNI.GBMRegressor_observations(swigCPtr, this);
  }

  public long n_trees() {
    return datamungeJNI.GBMRegressor_n_trees(swigCPtr, this);
  }

  public DVector feature_importance() {
    return new DVector(datamungeJNI.GBMRegressor_feature_importance(swigCPtr, this), true);
  }

  public DVector fitted_values() {
    return new DVector(datamungeJNI.GBMRegressor_fitted_values(swigCPtr, this), true);
  }

  public double r_squared() {
    return datamungeJNI.GBMRegressor_r_squared(swigCPtr, this);
  }

  public double rmse() {
    return datamungeJNI.GBMRegressor_rmse(swigCPtr, this);
  }

  /**
   *  Mean squared error on the training set after each boosting round (length n_trees()).
   */
  public DVector training_deviance() {
    return new DVector(datamungeJNI.GBMRegressor_training_deviance(swigCPtr, this), true);
  }

  public String summary() {
    return datamungeJNI.GBMRegressor_summary(swigCPtr, this);
  }

  public void print_summary() {
    datamungeJNI.GBMRegressor_print_summary(swigCPtr, this);
  }

  public DVector predict(DataFrame newdata) {
    return new DVector(datamungeJNI.GBMRegressor_predict(swigCPtr, this, DataFrame.getCPtr(newdata), newdata), true);
  }

  public RPlot plot_predicted_vs_actual() {
    return new RPlot(datamungeJNI.GBMRegressor_plot_predicted_vs_actual(swigCPtr, this), true);
  }

  public RPlot plot_residuals_vs_fitted() {
    return new RPlot(datamungeJNI.GBMRegressor_plot_residuals_vs_fitted(swigCPtr, this), true);
  }

  public RPlot plot_training_deviance() {
    return new RPlot(datamungeJNI.GBMRegressor_plot_training_deviance(swigCPtr, this), true);
  }

}
