/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  SWIG-friendly facade for datamunge::plot::GGPlot — a ggplot2-style grammar-of-graphics<br>
 *         builder. Geom/theme/scale/facet calls are chainable, mirroring ggplot2's own layered<br>
 *         `ggplot(df, aes(...)) + geom_point() + ...` style as closely as C++ method chaining allows.
 */
public class GGPlot {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GGPlot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GGPlot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GGPlot obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_GGPlot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  
   */
  public GGPlot(DataFrame data, String x_column, String y_column, String color_column, String fill_column, String group_column) {
    this(datamungeJNI.new_GGPlot__SWIG_0(DataFrame.getCPtr(data), data, x_column, y_column, color_column, fill_column, group_column), true);
  }

  /**
   *  
   */
  public GGPlot(DataFrame data, String x_column, String y_column, String color_column, String fill_column) {
    this(datamungeJNI.new_GGPlot__SWIG_1(DataFrame.getCPtr(data), data, x_column, y_column, color_column, fill_column), true);
  }

  /**
   *  
   */
  public GGPlot(DataFrame data, String x_column, String y_column, String color_column) {
    this(datamungeJNI.new_GGPlot__SWIG_2(DataFrame.getCPtr(data), data, x_column, y_column, color_column), true);
  }

  /**
   *  
   */
  public GGPlot(DataFrame data, String x_column, String y_column) {
    this(datamungeJNI.new_GGPlot__SWIG_3(DataFrame.getCPtr(data), data, x_column, y_column), true);
  }

  /**
   *  
   */
  public GGPlot(DataFrame data, String x_column) {
    this(datamungeJNI.new_GGPlot__SWIG_4(DataFrame.getCPtr(data), data, x_column), true);
  }

  public GGPlot geom_point(RGB color, double size) {
    return new GGPlot(datamungeJNI.GGPlot_geom_point__SWIG_0(swigCPtr, this, RGB.getCPtr(color), color, size), false);
  }

  public GGPlot geom_point(RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_point__SWIG_1(swigCPtr, this, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_point() {
    return new GGPlot(datamungeJNI.GGPlot_geom_point__SWIG_2(swigCPtr, this), false);
  }

  public GGPlot geom_line(RGB color, double width) {
    return new GGPlot(datamungeJNI.GGPlot_geom_line__SWIG_0(swigCPtr, this, RGB.getCPtr(color), color, width), false);
  }

  public GGPlot geom_line(RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_line__SWIG_1(swigCPtr, this, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_line() {
    return new GGPlot(datamungeJNI.GGPlot_geom_line__SWIG_2(swigCPtr, this), false);
  }

  public GGPlot geom_bar(RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_bar__SWIG_0(swigCPtr, this, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_bar() {
    return new GGPlot(datamungeJNI.GGPlot_geom_bar__SWIG_1(swigCPtr, this), false);
  }

  public GGPlot geom_col(RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_col__SWIG_0(swigCPtr, this, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_col() {
    return new GGPlot(datamungeJNI.GGPlot_geom_col__SWIG_1(swigCPtr, this), false);
  }

  public GGPlot geom_histogram(long bins, RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_histogram__SWIG_0(swigCPtr, this, bins, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_histogram(long bins) {
    return new GGPlot(datamungeJNI.GGPlot_geom_histogram__SWIG_1(swigCPtr, this, bins), false);
  }

  public GGPlot geom_histogram() {
    return new GGPlot(datamungeJNI.GGPlot_geom_histogram__SWIG_2(swigCPtr, this), false);
  }

  public GGPlot geom_boxplot(RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_boxplot__SWIG_0(swigCPtr, this, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_boxplot() {
    return new GGPlot(datamungeJNI.GGPlot_geom_boxplot__SWIG_1(swigCPtr, this), false);
  }

  public GGPlot geom_smooth(RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_smooth__SWIG_0(swigCPtr, this, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_smooth() {
    return new GGPlot(datamungeJNI.GGPlot_geom_smooth__SWIG_1(swigCPtr, this), false);
  }

  public GGPlot geom_area(RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_area__SWIG_0(swigCPtr, this, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_area() {
    return new GGPlot(datamungeJNI.GGPlot_geom_area__SWIG_1(swigCPtr, this), false);
  }

  public GGPlot geom_ribbon(String ymin_column, String ymax_column, RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_ribbon__SWIG_0(swigCPtr, this, ymin_column, ymax_column, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_ribbon(String ymin_column, String ymax_column) {
    return new GGPlot(datamungeJNI.GGPlot_geom_ribbon__SWIG_1(swigCPtr, this, ymin_column, ymax_column), false);
  }

  public GGPlot geom_density(RGB color) {
    return new GGPlot(datamungeJNI.GGPlot_geom_density__SWIG_0(swigCPtr, this, RGB.getCPtr(color), color), false);
  }

  public GGPlot geom_density() {
    return new GGPlot(datamungeJNI.GGPlot_geom_density__SWIG_1(swigCPtr, this), false);
  }

  public GGPlot facet_wrap(String column, long ncol) {
    return new GGPlot(datamungeJNI.GGPlot_facet_wrap__SWIG_0(swigCPtr, this, column, ncol), false);
  }

  public GGPlot facet_wrap(String column) {
    return new GGPlot(datamungeJNI.GGPlot_facet_wrap__SWIG_1(swigCPtr, this, column), false);
  }

  public GGPlot theme_minimal() {
    return new GGPlot(datamungeJNI.GGPlot_theme_minimal(swigCPtr, this), false);
  }

  public GGPlot theme_bw() {
    return new GGPlot(datamungeJNI.GGPlot_theme_bw(swigCPtr, this), false);
  }

  public GGPlot theme_classic() {
    return new GGPlot(datamungeJNI.GGPlot_theme_classic(swigCPtr, this), false);
  }

  public GGPlot scale_color_manual(SWIGTYPE_p_std__vectorT_datamunge__plot__RGB_t values) {
    return new GGPlot(datamungeJNI.GGPlot_scale_color_manual(swigCPtr, this, SWIGTYPE_p_std__vectorT_datamunge__plot__RGB_t.getCPtr(values)), false);
  }

  public GGPlot labs(String title, String x, String y) {
    return new GGPlot(datamungeJNI.GGPlot_labs__SWIG_0(swigCPtr, this, title, x, y), false);
  }

  public GGPlot labs(String title, String x) {
    return new GGPlot(datamungeJNI.GGPlot_labs__SWIG_1(swigCPtr, this, title, x), false);
  }

  public GGPlot labs(String title) {
    return new GGPlot(datamungeJNI.GGPlot_labs__SWIG_2(swigCPtr, this, title), false);
  }

  public GGPlot labs() {
    return new GGPlot(datamungeJNI.GGPlot_labs__SWIG_3(swigCPtr, this), false);
  }

  public void save(String path) {
    datamungeJNI.GGPlot_save(swigCPtr, this, path);
  }

  public void save_svg(String path) {
    datamungeJNI.GGPlot_save_svg(swigCPtr, this, path);
  }

  public void show(String title_hint) {
    datamungeJNI.GGPlot_show__SWIG_0(swigCPtr, this, title_hint);
  }

  public void show() {
    datamungeJNI.GGPlot_show__SWIG_1(swigCPtr, this);
  }

}
