/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class GibbsResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GibbsResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GibbsResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GibbsResult obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_GibbsResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  Post-warmup draws, one vector&lt;double&gt; per sample.
   */
  public void setSamples(DVectorVector value) {
    datamungeJNI.GibbsResult_samples_set(swigCPtr, this, DVectorVector.getCPtr(value), value);
  }

  /**
   *  Post-warmup draws, one vector&lt;double&gt; per sample.
   */
  public DVectorVector getSamples() {
    long cPtr = datamungeJNI.GibbsResult_samples_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DVectorVector(cPtr, false);
  }

  /**
   *  Mean acceptance rate per coordinate (across all iterations), in parameter order.
   */
  public void setAccept_rates(DVector value) {
    datamungeJNI.GibbsResult_accept_rates_set(swigCPtr, this, DVector.getCPtr(value), value);
  }

  /**
   *  Mean acceptance rate per coordinate (across all iterations), in parameter order.
   */
  public DVector getAccept_rates() {
    long cPtr = datamungeJNI.GibbsResult_accept_rates_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DVector(cPtr, false);
  }

  public void setFinal_step_sizes(DVector value) {
    datamungeJNI.GibbsResult_final_step_sizes_set(swigCPtr, this, DVector.getCPtr(value), value);
  }

  public DVector getFinal_step_sizes() {
    long cPtr = datamungeJNI.GibbsResult_final_step_sizes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DVector(cPtr, false);
  }

  public GibbsResult() {
    this(datamungeJNI.new_GibbsResult(), true);
  }

}
