/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class GreyWolfOptimizerOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GreyWolfOptimizerOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GreyWolfOptimizerOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GreyWolfOptimizerOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_GreyWolfOptimizerOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPopulation_size(long value) {
    datamungeJNI.GreyWolfOptimizerOptions_population_size_set(swigCPtr, this, value);
  }

  public long getPopulation_size() {
    return datamungeJNI.GreyWolfOptimizerOptions_population_size_get(swigCPtr, this);
  }

  public void setMax_iterations(long value) {
    datamungeJNI.GreyWolfOptimizerOptions_max_iterations_set(swigCPtr, this, value);
  }

  public long getMax_iterations() {
    return datamungeJNI.GreyWolfOptimizerOptions_max_iterations_get(swigCPtr, this);
  }

  /**
   *  Stops after the best-ever value has improved by less than this for 20 consecutive iterations.
   */
  public void setTolerance(double value) {
    datamungeJNI.GreyWolfOptimizerOptions_tolerance_set(swigCPtr, this, value);
  }

  /**
   *  Stops after the best-ever value has improved by less than this for 20 consecutive iterations.
   */
  public double getTolerance() {
    return datamungeJNI.GreyWolfOptimizerOptions_tolerance_get(swigCPtr, this);
  }

  public void setSeed(java.math.BigInteger value) {
    datamungeJNI.GreyWolfOptimizerOptions_seed_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSeed() {
    return datamungeJNI.GreyWolfOptimizerOptions_seed_get(swigCPtr, this);
  }

  public GreyWolfOptimizerOptions() {
    this(datamungeJNI.new_GreyWolfOptimizerOptions(), true);
  }

}
