/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  Importance sampling against a multivariate Gaussian proposal N(mean, covariance) --<br>
 *         a natural choice when a Laplace approximation is available and reasonably close to<br>
 *         the target's shape (e.g. bayes::MAP's mode paired with a numerically estimated<br>
 *         Hessian there). Produces a weighted i.i.d. sample in one shot rather than a Markov<br>
 *         chain -- no warmup, nothing to check for mixing -- but accuracy depends entirely on<br>
 *         how well the Gaussian proposal covers the target's mass; effective_sample_size is<br>
 *         the diagnostic to check before trusting the result.
 */
public class ImportanceSampling {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImportanceSampling(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImportanceSampling obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ImportanceSampling obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_ImportanceSampling(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ImportanceSampling(ImportanceSamplingOptions options) {
    this(datamungeJNI.new_ImportanceSampling__SWIG_0(ImportanceSamplingOptions.getCPtr(options), options), true);
  }

  public ImportanceSampling() {
    this(datamungeJNI.new_ImportanceSampling__SWIG_1(), true);
  }

  /**
   *  <code>log_target</code> need only be evaluable (optim::ArbitraryFunction), not<br>
   *         differentiable. <code>proposal_covariance</code> (a plain d x d nested vector, not<br>
   *         linalg::DenseMatrix -- matrices never cross the SWIG boundary as DenseMatrix<br>
   *         anywhere in this library, only as nested vectors) must be symmetric positive<br>
   *         definite.
   */
  public ImportanceSamplingResult sample(ArbitraryFunction log_target, DVector proposal_mean, DVectorVector proposal_covariance) {
    return new ImportanceSamplingResult(datamungeJNI.ImportanceSampling_sample(swigCPtr, this, ArbitraryFunction.getCPtr(log_target), log_target, DVector.getCPtr(proposal_mean), proposal_mean, DVectorVector.getCPtr(proposal_covariance), proposal_covariance), true);
  }

}
