/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  SWIG-friendly facade for datamunge::stats::INLAMixedModel — a mixed model (same<br>
 *         formula grammar as GLMM/LMM) fit by Integrated Nested Laplace Approximation instead<br>
 *         of penalized quasi-likelihood/REML: a genuinely Bayesian alternative returning real<br>
 *         posterior means/sds (including for the variance components) rather than point<br>
 *         estimates + asymptotic standard errors. See datamunge::bayes::INLA (C++-only, not<br>
 *         exposed to bindings -- same reasoning as AutodiffModel) for the underlying algorithm.
 */
public class INLAMixedModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected INLAMixedModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(INLAMixedModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(INLAMixedModel obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_INLAMixedModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  @param family One of "gaussian" (identity link), "binomial" (logit link), or "poisson" (log link).<br>
   *  @param strategy One of "grid" (integrate over hyperparameter uncertainty) or "eb"<br>
   *                  (empirical Bayes: fix hyperparameters at their posterior mode).
   */
  public INLAMixedModel(DataFrame data, String formula, String family, String strategy, double fixed_effect_prior_sd, long grid_points_per_dim, double grid_span, long mode_population_size, long mode_max_generations, long seed) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_0(DataFrame.getCPtr(data), data, formula, family, strategy, fixed_effect_prior_sd, grid_points_per_dim, grid_span, mode_population_size, mode_max_generations, seed), true);
  }

  /**
   *  @param family One of "gaussian" (identity link), "binomial" (logit link), or "poisson" (log link).<br>
   *  @param strategy One of "grid" (integrate over hyperparameter uncertainty) or "eb"<br>
   *                  (empirical Bayes: fix hyperparameters at their posterior mode).
   */
  public INLAMixedModel(DataFrame data, String formula, String family, String strategy, double fixed_effect_prior_sd, long grid_points_per_dim, double grid_span, long mode_population_size, long mode_max_generations) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_1(DataFrame.getCPtr(data), data, formula, family, strategy, fixed_effect_prior_sd, grid_points_per_dim, grid_span, mode_population_size, mode_max_generations), true);
  }

  /**
   *  @param family One of "gaussian" (identity link), "binomial" (logit link), or "poisson" (log link).<br>
   *  @param strategy One of "grid" (integrate over hyperparameter uncertainty) or "eb"<br>
   *                  (empirical Bayes: fix hyperparameters at their posterior mode).
   */
  public INLAMixedModel(DataFrame data, String formula, String family, String strategy, double fixed_effect_prior_sd, long grid_points_per_dim, double grid_span, long mode_population_size) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_2(DataFrame.getCPtr(data), data, formula, family, strategy, fixed_effect_prior_sd, grid_points_per_dim, grid_span, mode_population_size), true);
  }

  /**
   *  @param family One of "gaussian" (identity link), "binomial" (logit link), or "poisson" (log link).<br>
   *  @param strategy One of "grid" (integrate over hyperparameter uncertainty) or "eb"<br>
   *                  (empirical Bayes: fix hyperparameters at their posterior mode).
   */
  public INLAMixedModel(DataFrame data, String formula, String family, String strategy, double fixed_effect_prior_sd, long grid_points_per_dim, double grid_span) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_3(DataFrame.getCPtr(data), data, formula, family, strategy, fixed_effect_prior_sd, grid_points_per_dim, grid_span), true);
  }

  /**
   *  @param family One of "gaussian" (identity link), "binomial" (logit link), or "poisson" (log link).<br>
   *  @param strategy One of "grid" (integrate over hyperparameter uncertainty) or "eb"<br>
   *                  (empirical Bayes: fix hyperparameters at their posterior mode).
   */
  public INLAMixedModel(DataFrame data, String formula, String family, String strategy, double fixed_effect_prior_sd, long grid_points_per_dim) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_4(DataFrame.getCPtr(data), data, formula, family, strategy, fixed_effect_prior_sd, grid_points_per_dim), true);
  }

  /**
   *  @param family One of "gaussian" (identity link), "binomial" (logit link), or "poisson" (log link).<br>
   *  @param strategy One of "grid" (integrate over hyperparameter uncertainty) or "eb"<br>
   *                  (empirical Bayes: fix hyperparameters at their posterior mode).
   */
  public INLAMixedModel(DataFrame data, String formula, String family, String strategy, double fixed_effect_prior_sd) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_5(DataFrame.getCPtr(data), data, formula, family, strategy, fixed_effect_prior_sd), true);
  }

  /**
   *  @param family One of "gaussian" (identity link), "binomial" (logit link), or "poisson" (log link).<br>
   *  @param strategy One of "grid" (integrate over hyperparameter uncertainty) or "eb"<br>
   *                  (empirical Bayes: fix hyperparameters at their posterior mode).
   */
  public INLAMixedModel(DataFrame data, String formula, String family, String strategy) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_6(DataFrame.getCPtr(data), data, formula, family, strategy), true);
  }

  /**
   *  @param family One of "gaussian" (identity link), "binomial" (logit link), or "poisson" (log link).<br>
   *  
   */
  public INLAMixedModel(DataFrame data, String formula, String family) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_7(DataFrame.getCPtr(data), data, formula, family), true);
  }

  /**
   *  
   */
  public INLAMixedModel(DataFrame data, String formula) {
    this(datamungeJNI.new_INLAMixedModel__SWIG_8(DataFrame.getCPtr(data), data, formula), true);
  }

  public String formula_text() {
    return datamungeJNI.INLAMixedModel_formula_text(swigCPtr, this);
  }

  public String family() {
    return datamungeJNI.INLAMixedModel_family(swigCPtr, this);
  }

  public String group_variable() {
    return datamungeJNI.INLAMixedModel_group_variable(swigCPtr, this);
  }

  public SVector random_effect_names() {
    return new SVector(datamungeJNI.INLAMixedModel_random_effect_names(swigCPtr, this), true);
  }

  public long observations() {
    return datamungeJNI.INLAMixedModel_observations(swigCPtr, this);
  }

  public long num_groups() {
    return datamungeJNI.INLAMixedModel_num_groups(swigCPtr, this);
  }

  public DVector fixed_effects_mean() {
    return new DVector(datamungeJNI.INLAMixedModel_fixed_effects_mean(swigCPtr, this), true);
  }

  public DVector fixed_effects_sd() {
    return new DVector(datamungeJNI.INLAMixedModel_fixed_effects_sd(swigCPtr, this), true);
  }

  public SVector coefficient_names() {
    return new SVector(datamungeJNI.INLAMixedModel_coefficient_names(swigCPtr, this), true);
  }

  public DVector random_effect_std_devs() {
    return new DVector(datamungeJNI.INLAMixedModel_random_effect_std_devs(swigCPtr, this), true);
  }

  /**
   *  Gaussian family only; throws for binomial/poisson (dispersion fixed at 1).
   */
  public double residual_std_dev() {
    return datamungeJNI.INLAMixedModel_residual_std_dev(swigCPtr, this);
  }

  public SVector group_labels() {
    return new SVector(datamungeJNI.INLAMixedModel_group_labels(swigCPtr, this), true);
  }

  /**
   *  The posterior-mean/sd BLUP-like random-effect vector for the group at<br>
   *         <code>group_index</code> (see group_labels()), in random_effect_names() order.
   */
  public DVector random_effects_mean_for_group(long group_index) {
    return new DVector(datamungeJNI.INLAMixedModel_random_effects_mean_for_group(swigCPtr, this, group_index), true);
  }

  public DVector random_effects_sd_for_group(long group_index) {
    return new DVector(datamungeJNI.INLAMixedModel_random_effects_sd_for_group(swigCPtr, this, group_index), true);
  }

  /**
   *  log p(y), approximated by the same INLA machinery used to fit the model.
   */
  public double log_marginal_likelihood() {
    return datamungeJNI.INLAMixedModel_log_marginal_likelihood(swigCPtr, this);
  }

  public String summary() {
    return datamungeJNI.INLAMixedModel_summary(swigCPtr, this);
  }

  public void print_summary() {
    datamungeJNI.INLAMixedModel_print_summary(swigCPtr, this);
  }

  public DVector predict(DataFrame newdata) {
    return new DVector(datamungeJNI.INLAMixedModel_predict(swigCPtr, this, DataFrame.getCPtr(newdata), newdata), true);
  }

}
