/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class InteriorPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InteriorPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InteriorPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(InteriorPoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_InteriorPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InteriorPoint(InteriorPointOptions options) {
    this(datamungeJNI.new_InteriorPoint__SWIG_0(InteriorPointOptions.getCPtr(options), options), true);
  }

  public InteriorPoint() {
    this(datamungeJNI.new_InteriorPoint__SWIG_1(), true);
  }

  public double optimize(InequalityConstrainedFunction function, DVector coordinates) {
    return datamungeJNI.InteriorPoint_optimize(swigCPtr, this, InequalityConstrainedFunction.getCPtr(function), function, DVector.getCPtr(coordinates), coordinates);
  }

}
