/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  SWIG-friendly facade for datamunge::stats::Isomap — nonlinear manifold learning via<br>
 *         geodesic (shortest-path, over a k-nearest-neighbor graph) distances embedded with<br>
 *         classical MDS. Throws if the k-nearest-neighbor graph is disconnected.
 */
public class Isomap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Isomap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Isomap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Isomap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_Isomap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  @param metric One of "euclidean" (default) or "manhattan".
   */
  public Isomap(DataFrame data, SVector feature_columns, long n_components, long n_neighbors, String metric) {
    this(datamungeJNI.new_Isomap__SWIG_0(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, n_neighbors, metric), true);
  }

  /**
   *  
   */
  public Isomap(DataFrame data, SVector feature_columns, long n_components, long n_neighbors) {
    this(datamungeJNI.new_Isomap__SWIG_1(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, n_neighbors), true);
  }

  /**
   *  
   */
  public Isomap(DataFrame data, SVector feature_columns, long n_components) {
    this(datamungeJNI.new_Isomap__SWIG_2(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components), true);
  }

  /**
   *  
   */
  public Isomap(DataFrame data, SVector feature_columns) {
    this(datamungeJNI.new_Isomap__SWIG_3(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public Isomap(DataFrame data, String encoded_feature_columns, long n_components, long n_neighbors, String metric) {
    this(datamungeJNI.new_Isomap__SWIG_4(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, n_neighbors, metric), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public Isomap(DataFrame data, String encoded_feature_columns, long n_components, long n_neighbors) {
    this(datamungeJNI.new_Isomap__SWIG_5(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, n_neighbors), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public Isomap(DataFrame data, String encoded_feature_columns, long n_components) {
    this(datamungeJNI.new_Isomap__SWIG_6(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public Isomap(DataFrame data, String encoded_feature_columns) {
    this(datamungeJNI.new_Isomap__SWIG_7(DataFrame.getCPtr(data), data, encoded_feature_columns), true);
  }

  public SVector feature_names() {
    return new SVector(datamungeJNI.Isomap_feature_names(swigCPtr, this), true);
  }

  public long observations() {
    return datamungeJNI.Isomap_observations(swigCPtr, this);
  }

  public long n_components() {
    return datamungeJNI.Isomap_n_components(swigCPtr, this);
  }

  public SizeVector kept_row_indices() {
    return new SizeVector(datamungeJNI.Isomap_kept_row_indices(swigCPtr, this), true);
  }

  public DVector eigenvalues() {
    return new DVector(datamungeJNI.Isomap_eigenvalues(swigCPtr, this), true);
  }

  public double goodness_of_fit() {
    return datamungeJNI.Isomap_goodness_of_fit(swigCPtr, this);
  }

  public DVector dimension(long index) {
    return new DVector(datamungeJNI.Isomap_dimension(swigCPtr, this, index), true);
  }

  /**
   *  The fitted embedding as a DataFrame ("Dim1", "Dim2", ... columns), one row per kept<br>
   *         observation -- ready to bind_cols()/plot with the rest of the DataFrame API.
   */
  public DataFrame embedding_frame() {
    long cPtr = datamungeJNI.Isomap_embedding_frame(swigCPtr, this);
    return (cPtr == 0) ? null : new DataFrame(cPtr, false);
  }

  public String summary() {
    return datamungeJNI.Isomap_summary(swigCPtr, this);
  }

  public void print_summary() {
    datamungeJNI.Isomap_print_summary(swigCPtr, this);
  }

  public RPlot plot_embedding(long dimension_x, long dimension_y) {
    return new RPlot(datamungeJNI.Isomap_plot_embedding__SWIG_0(swigCPtr, this, dimension_x, dimension_y), true);
  }

  public RPlot plot_embedding(long dimension_x) {
    return new RPlot(datamungeJNI.Isomap_plot_embedding__SWIG_1(swigCPtr, this, dimension_x), true);
  }

  public RPlot plot_embedding() {
    return new RPlot(datamungeJNI.Isomap_plot_embedding__SWIG_2(swigCPtr, this), true);
  }

  public RPlot plot_embedding_grouped(SVector group_labels, long dimension_x, long dimension_y) {
    return new RPlot(datamungeJNI.Isomap_plot_embedding_grouped__SWIG_0(swigCPtr, this, SVector.getCPtr(group_labels), group_labels, dimension_x, dimension_y), true);
  }

  public RPlot plot_embedding_grouped(SVector group_labels, long dimension_x) {
    return new RPlot(datamungeJNI.Isomap_plot_embedding_grouped__SWIG_1(swigCPtr, this, SVector.getCPtr(group_labels), group_labels, dimension_x), true);
  }

  public RPlot plot_embedding_grouped(SVector group_labels) {
    return new RPlot(datamungeJNI.Isomap_plot_embedding_grouped__SWIG_2(swigCPtr, this, SVector.getCPtr(group_labels), group_labels), true);
  }

}
