/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class LBFGSOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LBFGSOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LBFGSOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LBFGSOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_LBFGSOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMax_iterations(long value) {
    datamungeJNI.LBFGSOptions_max_iterations_set(swigCPtr, this, value);
  }

  public long getMax_iterations() {
    return datamungeJNI.LBFGSOptions_max_iterations_get(swigCPtr, this);
  }

  /**
   *  Stops when the gradient norm drops below this.
   */
  public void setTolerance(double value) {
    datamungeJNI.LBFGSOptions_tolerance_set(swigCPtr, this, value);
  }

  /**
   *  Stops when the gradient norm drops below this.
   */
  public double getTolerance() {
    return datamungeJNI.LBFGSOptions_tolerance_get(swigCPtr, this);
  }

  /**
   *  Number of (s, y) curvature pairs retained for the two-loop recursion.
   */
  public void setHistory_size(long value) {
    datamungeJNI.LBFGSOptions_history_size_set(swigCPtr, this, value);
  }

  /**
   *  Number of (s, y) curvature pairs retained for the two-loop recursion.
   */
  public long getHistory_size() {
    return datamungeJNI.LBFGSOptions_history_size_get(swigCPtr, this);
  }

  /**
   *  Armijo sufficient-decrease constant for the line search.
   */
  public void setArmijo_c1(double value) {
    datamungeJNI.LBFGSOptions_armijo_c1_set(swigCPtr, this, value);
  }

  /**
   *  Armijo sufficient-decrease constant for the line search.
   */
  public double getArmijo_c1() {
    return datamungeJNI.LBFGSOptions_armijo_c1_get(swigCPtr, this);
  }

  /**
   *  Weak-Wolfe curvature constant for the line search (typical value for L-BFGS).
   */
  public void setWolfe_c2(double value) {
    datamungeJNI.LBFGSOptions_wolfe_c2_set(swigCPtr, this, value);
  }

  /**
   *  Weak-Wolfe curvature constant for the line search (typical value for L-BFGS).
   */
  public double getWolfe_c2() {
    return datamungeJNI.LBFGSOptions_wolfe_c2_get(swigCPtr, this);
  }

  public void setMax_line_search_trials(long value) {
    datamungeJNI.LBFGSOptions_max_line_search_trials_set(swigCPtr, this, value);
  }

  public long getMax_line_search_trials() {
    return datamungeJNI.LBFGSOptions_max_line_search_trials_get(swigCPtr, this);
  }

  public LBFGSOptions() {
    this(datamungeJNI.new_LBFGSOptions(), true);
  }

}
