/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  One manually-specified legend row, as drawn by R's `legend()`. When a plot has any manual<br>
 *  entries, they replace the default auto-generated (one-row-per-labeled-series) legend.
 */
public class LegendEntry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LegendEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LegendEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LegendEntry obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_LegendEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLabel(String value) {
    datamungeJNI.LegendEntry_label_set(swigCPtr, this, value);
  }

  public String getLabel() {
    return datamungeJNI.LegendEntry_label_get(swigCPtr, this);
  }

  public void setColor(RGB value) {
    datamungeJNI.LegendEntry_color_set(swigCPtr, this, RGB.getCPtr(value), value);
  }

  public RGB getColor() {
    long cPtr = datamungeJNI.LegendEntry_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RGB(cPtr, false);
  }

  public LegendEntry() {
    this(datamungeJNI.new_LegendEntry(), true);
  }

}
