/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  SWIG-friendly facade for datamunge::stats::MDS — classical (metric/Torgerson)<br>
 *         multidimensional scaling fit from a DataFrame and a list of numeric feature columns:<br>
 *         embeds the rows in a low-dimensional space that best reproduces their original<br>
 *         pairwise distances.
 */
public class MDS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MDS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MDS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MDS obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_MDS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  @param metric One of "euclidean" (default) or "manhattan".
   */
  public MDS(DataFrame data, SVector feature_columns, long n_components, String metric) {
    this(datamungeJNI.new_MDS__SWIG_0(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, metric), true);
  }

  /**
   *  
   */
  public MDS(DataFrame data, SVector feature_columns, long n_components) {
    this(datamungeJNI.new_MDS__SWIG_1(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components), true);
  }

  /**
   *  
   */
  public MDS(DataFrame data, SVector feature_columns) {
    this(datamungeJNI.new_MDS__SWIG_2(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public MDS(DataFrame data, String encoded_feature_columns, long n_components, String metric) {
    this(datamungeJNI.new_MDS__SWIG_3(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, metric), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public MDS(DataFrame data, String encoded_feature_columns, long n_components) {
    this(datamungeJNI.new_MDS__SWIG_4(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public MDS(DataFrame data, String encoded_feature_columns) {
    this(datamungeJNI.new_MDS__SWIG_5(DataFrame.getCPtr(data), data, encoded_feature_columns), true);
  }

  public SVector feature_names() {
    return new SVector(datamungeJNI.MDS_feature_names(swigCPtr, this), true);
  }

  public long observations() {
    return datamungeJNI.MDS_observations(swigCPtr, this);
  }

  public long n_components() {
    return datamungeJNI.MDS_n_components(swigCPtr, this);
  }

  /**
   *  Row indices (into the DataFrame passed to the constructor) that survived<br>
   *         null-dropping, in fitted order -- use to align an external label vector for<br>
   *         plot_embedding_grouped().
   */
  public SizeVector kept_row_indices() {
    return new SizeVector(datamungeJNI.MDS_kept_row_indices(swigCPtr, this), true);
  }

  public DVector eigenvalues() {
    return new DVector(datamungeJNI.MDS_eigenvalues(swigCPtr, this), true);
  }

  public double goodness_of_fit() {
    return datamungeJNI.MDS_goodness_of_fit(swigCPtr, this);
  }

  public DVector dimension(long index) {
    return new DVector(datamungeJNI.MDS_dimension(swigCPtr, this, index), true);
  }

  /**
   *  The fitted embedding as a DataFrame ("Dim1", "Dim2", ... columns), one row per kept<br>
   *         observation -- ready to bind_cols()/plot with the rest of the DataFrame API.
   */
  public DataFrame embedding_frame() {
    long cPtr = datamungeJNI.MDS_embedding_frame(swigCPtr, this);
    return (cPtr == 0) ? null : new DataFrame(cPtr, false);
  }

  public String summary() {
    return datamungeJNI.MDS_summary(swigCPtr, this);
  }

  public void print_summary() {
    datamungeJNI.MDS_print_summary(swigCPtr, this);
  }

  /**
   *  Scatter of the embedding in the (dimension_x, dimension_y) plane, single series.
   */
  public RPlot plot_embedding(long dimension_x, long dimension_y) {
    return new RPlot(datamungeJNI.MDS_plot_embedding__SWIG_0(swigCPtr, this, dimension_x, dimension_y), true);
  }

  /**
   *  Scatter of the embedding in the (dimension_x, dimension_y) plane, single series.
   */
  public RPlot plot_embedding(long dimension_x) {
    return new RPlot(datamungeJNI.MDS_plot_embedding__SWIG_1(swigCPtr, this, dimension_x), true);
  }

  /**
   *  Scatter of the embedding in the (dimension_x, dimension_y) plane, single series.
   */
  public RPlot plot_embedding() {
    return new RPlot(datamungeJNI.MDS_plot_embedding__SWIG_2(swigCPtr, this), true);
  }

  /**
   *  Same, colored by an external grouping vector (e.g. a withheld response column);<br>
   *         `group_labels` must have one entry per kept_row_indices() entry.
   */
  public RPlot plot_embedding_grouped(SVector group_labels, long dimension_x, long dimension_y) {
    return new RPlot(datamungeJNI.MDS_plot_embedding_grouped__SWIG_0(swigCPtr, this, SVector.getCPtr(group_labels), group_labels, dimension_x, dimension_y), true);
  }

  /**
   *  Same, colored by an external grouping vector (e.g. a withheld response column);<br>
   *         `group_labels` must have one entry per kept_row_indices() entry.
   */
  public RPlot plot_embedding_grouped(SVector group_labels, long dimension_x) {
    return new RPlot(datamungeJNI.MDS_plot_embedding_grouped__SWIG_1(swigCPtr, this, SVector.getCPtr(group_labels), group_labels, dimension_x), true);
  }

  /**
   *  Same, colored by an external grouping vector (e.g. a withheld response column);<br>
   *         `group_labels` must have one entry per kept_row_indices() entry.
   */
  public RPlot plot_embedding_grouped(SVector group_labels) {
    return new RPlot(datamungeJNI.MDS_plot_embedding_grouped__SWIG_2(swigCPtr, this, SVector.getCPtr(group_labels), group_labels), true);
  }

}
