/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  Full-batch Nadam (Dozat 2016) on a DifferentiableFunction: Adam's adaptive second<br>
 *         moment combined with a Nesterov-style, bias-corrected first-moment direction.
 */
public class Nadam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Nadam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Nadam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Nadam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_Nadam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Nadam(NadamOptions options) {
    this(datamungeJNI.new_Nadam__SWIG_0(NadamOptions.getCPtr(options), options), true);
  }

  public Nadam() {
    this(datamungeJNI.new_Nadam__SWIG_1(), true);
  }

  public double optimize(DifferentiableFunction function, DVector coordinates) {
    return datamungeJNI.Nadam_optimize(swigCPtr, this, DifferentiableFunction.getCPtr(function), function, DVector.getCPtr(coordinates), coordinates);
  }

}
