/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  SWIG-friendly facade for datamunge::stats::NaiveBayesClassifier — a Naive Bayes classifier that<br>
 *         models numeric predictors with per-class Gaussians and categorical predictors with per-class<br>
 *         frequency tables (each categorical predictor's levels modeled jointly as one variable, not as<br>
 *         separate independent dummy features).
 */
public class NaiveBayesClassifier {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NaiveBayesClassifier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NaiveBayesClassifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(NaiveBayesClassifier obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_NaiveBayesClassifier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NaiveBayesClassifier(DataFrame data, String formula, double laplace_smoothing, double var_smoothing) {
    this(datamungeJNI.new_NaiveBayesClassifier__SWIG_0(DataFrame.getCPtr(data), data, formula, laplace_smoothing, var_smoothing), true);
  }

  public NaiveBayesClassifier(DataFrame data, String formula, double laplace_smoothing) {
    this(datamungeJNI.new_NaiveBayesClassifier__SWIG_1(DataFrame.getCPtr(data), data, formula, laplace_smoothing), true);
  }

  public NaiveBayesClassifier(DataFrame data, String formula) {
    this(datamungeJNI.new_NaiveBayesClassifier__SWIG_2(DataFrame.getCPtr(data), data, formula), true);
  }

  public SVector classes() {
    return new SVector(datamungeJNI.NaiveBayesClassifier_classes(swigCPtr, this), true);
  }

  public SVector predictor_names() {
    return new SVector(datamungeJNI.NaiveBayesClassifier_predictor_names(swigCPtr, this), true);
  }

  public long observations() {
    return datamungeJNI.NaiveBayesClassifier_observations(swigCPtr, this);
  }

  public DVector class_priors() {
    return new DVector(datamungeJNI.NaiveBayesClassifier_class_priors(swigCPtr, this), true);
  }

  public double training_accuracy() {
    return datamungeJNI.NaiveBayesClassifier_training_accuracy(swigCPtr, this);
  }

  /**
   *  "actual" column plus one numeric column per class (counts), both ordered as classes().
   */
  public DataFrame confusion_matrix() {
    long cPtr = datamungeJNI.NaiveBayesClassifier_confusion_matrix(swigCPtr, this);
    return (cPtr == 0) ? null : new DataFrame(cPtr, false);
  }

  public String summary() {
    return datamungeJNI.NaiveBayesClassifier_summary(swigCPtr, this);
  }

  public void print_summary() {
    datamungeJNI.NaiveBayesClassifier_print_summary(swigCPtr, this);
  }

  public SVector predict(DataFrame newdata) {
    return new SVector(datamungeJNI.NaiveBayesClassifier_predict(swigCPtr, this, DataFrame.getCPtr(newdata), newdata), true);
  }

  /**
   *  "class" column plus one numeric probability column per class (prob_&lt;class&gt;).
   */
  public DataFrame predict_frame(DataFrame newdata) {
    long cPtr = datamungeJNI.NaiveBayesClassifier_predict_frame(swigCPtr, this, DataFrame.getCPtr(newdata), newdata);
    return (cPtr == 0) ? null : new DataFrame(cPtr, false);
  }

  public ScatterPlot plot_classification(DataFrame data, String x_feature, String y_feature) {
    return new ScatterPlot(datamungeJNI.NaiveBayesClassifier_plot_classification(swigCPtr, this, DataFrame.getCPtr(data), data, x_feature, y_feature), true);
  }

  /**
   *  Background grid of predicted class regions; requires exactly two predictors, both numeric.
   */
  public ScatterPlot plot_decision_regions(String x_feature, String y_feature, long grid_resolution) {
    return new ScatterPlot(datamungeJNI.NaiveBayesClassifier_plot_decision_regions__SWIG_0(swigCPtr, this, x_feature, y_feature, grid_resolution), true);
  }

  /**
   *  Background grid of predicted class regions; requires exactly two predictors, both numeric.
   */
  public ScatterPlot plot_decision_regions(String x_feature, String y_feature) {
    return new ScatterPlot(datamungeJNI.NaiveBayesClassifier_plot_decision_regions__SWIG_1(swigCPtr, this, x_feature, y_feature), true);
  }

}
