/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class Newton {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Newton(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Newton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Newton obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_Newton(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Newton(NewtonOptions options) {
    this(datamungeJNI.new_Newton__SWIG_0(NewtonOptions.getCPtr(options), options), true);
  }

  public Newton() {
    this(datamungeJNI.new_Newton__SWIG_1(), true);
  }

  public double optimize(HessianFunction function, DVector coordinates) {
    return datamungeJNI.Newton_optimize(swigCPtr, this, HessianFunction.getCPtr(function), function, DVector.getCPtr(coordinates), coordinates);
  }

}
