/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class ParallelTemperingOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParallelTemperingOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParallelTemperingOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ParallelTemperingOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_ParallelTemperingOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_replicas(long value) {
    datamungeJNI.ParallelTemperingOptions_num_replicas_set(swigCPtr, this, value);
  }

  public long getNum_replicas() {
    return datamungeJNI.ParallelTemperingOptions_num_replicas_get(swigCPtr, this);
  }

  /**
   *  T_max, the hottest replica's fixed temperature.
   */
  public void setInitial_temperature(double value) {
    datamungeJNI.ParallelTemperingOptions_initial_temperature_set(swigCPtr, this, value);
  }

  /**
   *  T_max, the hottest replica's fixed temperature.
   */
  public double getInitial_temperature() {
    return datamungeJNI.ParallelTemperingOptions_initial_temperature_get(swigCPtr, this);
  }

  /**
   *  T_min, the coldest replica's fixed temperature.
   */
  public void setFinal_temperature(double value) {
    datamungeJNI.ParallelTemperingOptions_final_temperature_set(swigCPtr, this, value);
  }

  /**
   *  T_min, the coldest replica's fixed temperature.
   */
  public double getFinal_temperature() {
    return datamungeJNI.ParallelTemperingOptions_final_temperature_get(swigCPtr, this);
  }

  /**
   *  Base standard deviation of each replica's Gaussian proposal; scaled per-replica by<br>
   *         sqrt(T_i / T_min) so hotter replicas take proportionally larger exploratory steps.
   */
  public void setStep_std_dev(double value) {
    datamungeJNI.ParallelTemperingOptions_step_std_dev_set(swigCPtr, this, value);
  }

  /**
   *  Base standard deviation of each replica's Gaussian proposal; scaled per-replica by<br>
   *         sqrt(T_i / T_min) so hotter replicas take proportionally larger exploratory steps.
   */
  public double getStep_std_dev() {
    return datamungeJNI.ParallelTemperingOptions_step_std_dev_get(swigCPtr, this);
  }

  /**
   *  Attempt a replica-exchange swap sweep every this many single-replica update sweeps.
   */
  public void setSwap_interval(long value) {
    datamungeJNI.ParallelTemperingOptions_swap_interval_set(swigCPtr, this, value);
  }

  /**
   *  Attempt a replica-exchange swap sweep every this many single-replica update sweeps.
   */
  public long getSwap_interval() {
    return datamungeJNI.ParallelTemperingOptions_swap_interval_get(swigCPtr, this);
  }

  public void setMax_sweeps(long value) {
    datamungeJNI.ParallelTemperingOptions_max_sweeps_set(swigCPtr, this, value);
  }

  public long getMax_sweeps() {
    return datamungeJNI.ParallelTemperingOptions_max_sweeps_get(swigCPtr, this);
  }

  public void setSeed(java.math.BigInteger value) {
    datamungeJNI.ParallelTemperingOptions_seed_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSeed() {
    return datamungeJNI.ParallelTemperingOptions_seed_get(swigCPtr, this);
  }

  public ParallelTemperingOptions() {
    this(datamungeJNI.new_ParallelTemperingOptions(), true);
  }

}
