/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  SWIG-friendly facade for datamunge::stats::PCA — principal component analysis fit<br>
 *         from a DataFrame and a list of numeric feature columns via eigendecomposition of the<br>
 *         correlation (default) or covariance matrix.
 */
public class PCA {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PCA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PCA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PCA obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_PCA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  @param center Mean-center each feature before fitting; almost always left true.<br>
   *  @param scale Standardize each feature to unit variance before fitting (i.e. fit on the<br>
   *               correlation matrix rather than the covariance matrix); recommended whenever<br>
   *               features are on different scales, and the default here.
   */
  public PCA(DataFrame data, SVector feature_columns, boolean center, boolean scale) {
    this(datamungeJNI.new_PCA__SWIG_0(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, center, scale), true);
  }

  /**
   *  @param center Mean-center each feature before fitting; almost always left true.<br>
   *  
   */
  public PCA(DataFrame data, SVector feature_columns, boolean center) {
    this(datamungeJNI.new_PCA__SWIG_1(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, center), true);
  }

  /**
   *  
   */
  public PCA(DataFrame data, SVector feature_columns) {
    this(datamungeJNI.new_PCA__SWIG_2(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public PCA(DataFrame data, String encoded_feature_columns, boolean center, boolean scale) {
    this(datamungeJNI.new_PCA__SWIG_3(DataFrame.getCPtr(data), data, encoded_feature_columns, center, scale), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public PCA(DataFrame data, String encoded_feature_columns, boolean center) {
    this(datamungeJNI.new_PCA__SWIG_4(DataFrame.getCPtr(data), data, encoded_feature_columns, center), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public PCA(DataFrame data, String encoded_feature_columns) {
    this(datamungeJNI.new_PCA__SWIG_5(DataFrame.getCPtr(data), data, encoded_feature_columns), true);
  }

  public SVector feature_names() {
    return new SVector(datamungeJNI.PCA_feature_names(swigCPtr, this), true);
  }

  public long observations() {
    return datamungeJNI.PCA_observations(swigCPtr, this);
  }

  public long num_components() {
    return datamungeJNI.PCA_num_components(swigCPtr, this);
  }

  /**
   *  Row indices (into the DataFrame passed to the constructor) that survived<br>
   *         null-dropping, in fitted order -- use to align an external label vector for<br>
   *         plot_scores_grouped().
   */
  public SizeVector kept_row_indices() {
    return new SizeVector(datamungeJNI.PCA_kept_row_indices(swigCPtr, this), true);
  }

  public DVector explained_variance() {
    return new DVector(datamungeJNI.PCA_explained_variance(swigCPtr, this), true);
  }

  public DVector explained_variance_ratio() {
    return new DVector(datamungeJNI.PCA_explained_variance_ratio(swigCPtr, this), true);
  }

  public DVector cumulative_explained_variance_ratio() {
    return new DVector(datamungeJNI.PCA_cumulative_explained_variance_ratio(swigCPtr, this), true);
  }

  public DVector component_loadings(long component_index) {
    return new DVector(datamungeJNI.PCA_component_loadings(swigCPtr, this, component_index), true);
  }

  public DVector component_scores(long component_index) {
    return new DVector(datamungeJNI.PCA_component_scores(swigCPtr, this, component_index), true);
  }

  /**
   *  The fitted training scores as a DataFrame ("PC1", "PC2", ... columns), one row per<br>
   *         kept observation -- ready to bind_cols()/plot with the rest of the DataFrame API.
   */
  public DataFrame scores_frame() {
    long cPtr = datamungeJNI.PCA_scores_frame(swigCPtr, this);
    return (cPtr == 0) ? null : new DataFrame(cPtr, false);
  }

  /**
   *  Projects new data onto the already-fitted components, as a DataFrame with the same<br>
   *         "PC1", "PC2", ... columns as scores_frame().
   */
  public DataFrame transform(DataFrame newdata) {
    long cPtr = datamungeJNI.PCA_transform(swigCPtr, this, DataFrame.getCPtr(newdata), newdata);
    return (cPtr == 0) ? null : new DataFrame(cPtr, false);
  }

  public String summary() {
    return datamungeJNI.PCA_summary(swigCPtr, this);
  }

  public void print_summary() {
    datamungeJNI.PCA_print_summary(swigCPtr, this);
  }

  /**
   *  Scatter of scores in the (component_x, component_y) plane, single series.
   */
  public RPlot plot_scores(long component_x, long component_y) {
    return new RPlot(datamungeJNI.PCA_plot_scores__SWIG_0(swigCPtr, this, component_x, component_y), true);
  }

  /**
   *  Scatter of scores in the (component_x, component_y) plane, single series.
   */
  public RPlot plot_scores(long component_x) {
    return new RPlot(datamungeJNI.PCA_plot_scores__SWIG_1(swigCPtr, this, component_x), true);
  }

  /**
   *  Scatter of scores in the (component_x, component_y) plane, single series.
   */
  public RPlot plot_scores() {
    return new RPlot(datamungeJNI.PCA_plot_scores__SWIG_2(swigCPtr, this), true);
  }

  /**
   *  Same, colored by an external grouping vector (e.g. a withheld response column);<br>
   *         `group_labels` must have one entry per kept_row_indices() entry.
   */
  public RPlot plot_scores_grouped(SVector group_labels, long component_x, long component_y) {
    return new RPlot(datamungeJNI.PCA_plot_scores_grouped__SWIG_0(swigCPtr, this, SVector.getCPtr(group_labels), group_labels, component_x, component_y), true);
  }

  /**
   *  Same, colored by an external grouping vector (e.g. a withheld response column);<br>
   *         `group_labels` must have one entry per kept_row_indices() entry.
   */
  public RPlot plot_scores_grouped(SVector group_labels, long component_x) {
    return new RPlot(datamungeJNI.PCA_plot_scores_grouped__SWIG_1(swigCPtr, this, SVector.getCPtr(group_labels), group_labels, component_x), true);
  }

  /**
   *  Same, colored by an external grouping vector (e.g. a withheld response column);<br>
   *         `group_labels` must have one entry per kept_row_indices() entry.
   */
  public RPlot plot_scores_grouped(SVector group_labels) {
    return new RPlot(datamungeJNI.PCA_plot_scores_grouped__SWIG_2(swigCPtr, this, SVector.getCPtr(group_labels), group_labels), true);
  }

  /**
   *  Scree plot: percent of variance explained by each component, as a bar chart.
   */
  public RPlot plot_scree() {
    return new RPlot(datamungeJNI.PCA_plot_scree(swigCPtr, this), true);
  }

}
