/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  Randomized cyclic block coordinate descent on a DifferentiableFunction.  Every epoch<br>
 *         randomly permutes the coordinates, partitions that permutation into blocks, and visits<br>
 *         each block exactly once.  A block uses a simultaneous partial-gradient step with an<br>
 *         Armijo backtracking line search.
 */
public class RandomizedBlockCoordinateDescent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RandomizedBlockCoordinateDescent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RandomizedBlockCoordinateDescent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RandomizedBlockCoordinateDescent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_RandomizedBlockCoordinateDescent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RandomizedBlockCoordinateDescent(RandomizedBlockCoordinateDescentOptions options) {
    this(datamungeJNI.new_RandomizedBlockCoordinateDescent__SWIG_0(RandomizedBlockCoordinateDescentOptions.getCPtr(options), options), true);
  }

  public RandomizedBlockCoordinateDescent() {
    this(datamungeJNI.new_RandomizedBlockCoordinateDescent__SWIG_1(), true);
  }

  public double optimize(DifferentiableFunction function, DVector coordinates) {
    return datamungeJNI.RandomizedBlockCoordinateDescent_optimize(swigCPtr, this, DifferentiableFunction.getCPtr(function), function, DVector.getCPtr(coordinates), coordinates);
  }

}
