/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class SAGAOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SAGAOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SAGAOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SAGAOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_SAGAOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStep_size(double value) {
    datamungeJNI.SAGAOptions_step_size_set(swigCPtr, this, value);
  }

  public double getStep_size() {
    return datamungeJNI.SAGAOptions_step_size_get(swigCPtr, this);
  }

  public void setMax_iterations(long value) {
    datamungeJNI.SAGAOptions_max_iterations_set(swigCPtr, this, value);
  }

  public long getMax_iterations() {
    return datamungeJNI.SAGAOptions_max_iterations_get(swigCPtr, this);
  }

  public void setTolerance(double value) {
    datamungeJNI.SAGAOptions_tolerance_set(swigCPtr, this, value);
  }

  public double getTolerance() {
    return datamungeJNI.SAGAOptions_tolerance_get(swigCPtr, this);
  }

  public void setSeed(java.math.BigInteger value) {
    datamungeJNI.SAGAOptions_seed_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSeed() {
    return datamungeJNI.SAGAOptions_seed_get(swigCPtr, this);
  }

  public SAGAOptions() {
    this(datamungeJNI.new_SAGAOptions(), true);
  }

}
