/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

public class SPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_SPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SPair() {
    this(datamungeJNI.new_SPair__SWIG_0(), true);
  }

  public SPair(String first, String second) {
    this(datamungeJNI.new_SPair__SWIG_1(first, second), true);
  }

  public SPair(SPair other) {
    this(datamungeJNI.new_SPair__SWIG_2(SPair.getCPtr(other), other), true);
  }

  public void setFirst(String value) {
    datamungeJNI.SPair_first_set(swigCPtr, this, value);
  }

  public String getFirst() {
    return datamungeJNI.SPair_first_get(swigCPtr, this);
  }

  public void setSecond(String value) {
    datamungeJNI.SPair_second_set(swigCPtr, this, value);
  }

  public String getSecond() {
    return datamungeJNI.SPair_second_get(swigCPtr, this);
  }

}
