/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.datamunge.jdatamunge;

/**
 *  SWIG-friendly facade for datamunge::stats::TSNE — t-distributed Stochastic Neighbor<br>
 *         Embedding, a nonlinear method that preserves local neighborhood structure (via a<br>
 *         perplexity-calibrated probability distribution) primarily for 2D/3D visualization.
 */
public class TSNE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TSNE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TSNE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TSNE obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        datamungeJNI.delete_TSNE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  @param metric One of "euclidean" (default) or "manhattan".
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum, double final_momentum, long momentum_switch_iteration, String metric, java.math.BigInteger seed) {
    this(datamungeJNI.new_TSNE__SWIG_0(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum, final_momentum, momentum_switch_iteration, metric, seed), true);
  }

  /**
   *  @param metric One of "euclidean" (default) or "manhattan".
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum, double final_momentum, long momentum_switch_iteration, String metric) {
    this(datamungeJNI.new_TSNE__SWIG_1(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum, final_momentum, momentum_switch_iteration, metric), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum, double final_momentum, long momentum_switch_iteration) {
    this(datamungeJNI.new_TSNE__SWIG_2(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum, final_momentum, momentum_switch_iteration), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum, double final_momentum) {
    this(datamungeJNI.new_TSNE__SWIG_3(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum, final_momentum), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum) {
    this(datamungeJNI.new_TSNE__SWIG_4(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations) {
    this(datamungeJNI.new_TSNE__SWIG_5(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration) {
    this(datamungeJNI.new_TSNE__SWIG_6(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate) {
    this(datamungeJNI.new_TSNE__SWIG_7(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations, learning_rate), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity, long max_iterations) {
    this(datamungeJNI.new_TSNE__SWIG_8(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity, max_iterations), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components, double perplexity) {
    this(datamungeJNI.new_TSNE__SWIG_9(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components, perplexity), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns, long n_components) {
    this(datamungeJNI.new_TSNE__SWIG_10(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns, n_components), true);
  }

  /**
   *  
   */
  public TSNE(DataFrame data, SVector feature_columns) {
    this(datamungeJNI.new_TSNE__SWIG_11(DataFrame.getCPtr(data), data, SVector.getCPtr(feature_columns), feature_columns), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum, double final_momentum, long momentum_switch_iteration, String metric, java.math.BigInteger seed) {
    this(datamungeJNI.new_TSNE__SWIG_12(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum, final_momentum, momentum_switch_iteration, metric, seed), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum, double final_momentum, long momentum_switch_iteration, String metric) {
    this(datamungeJNI.new_TSNE__SWIG_13(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum, final_momentum, momentum_switch_iteration, metric), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum, double final_momentum, long momentum_switch_iteration) {
    this(datamungeJNI.new_TSNE__SWIG_14(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum, final_momentum, momentum_switch_iteration), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum, double final_momentum) {
    this(datamungeJNI.new_TSNE__SWIG_15(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum, final_momentum), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations, double initial_momentum) {
    this(datamungeJNI.new_TSNE__SWIG_16(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations, initial_momentum), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration, long early_exaggeration_iterations) {
    this(datamungeJNI.new_TSNE__SWIG_17(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration, early_exaggeration_iterations), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate, double early_exaggeration) {
    this(datamungeJNI.new_TSNE__SWIG_18(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations, learning_rate, early_exaggeration), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations, double learning_rate) {
    this(datamungeJNI.new_TSNE__SWIG_19(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations, learning_rate), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity, long max_iterations) {
    this(datamungeJNI.new_TSNE__SWIG_20(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity, max_iterations), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components, double perplexity) {
    this(datamungeJNI.new_TSNE__SWIG_21(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components, perplexity), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns, long n_components) {
    this(datamungeJNI.new_TSNE__SWIG_22(DataFrame.getCPtr(data), data, encoded_feature_columns, n_components), true);
  }

  /**
   *  Same as the vector&lt;string&gt; constructor, but feature_columns is a single "<count>\x1e<br>
   *         col1\x1fcol2\x1f..."-encoded string -- see KMeans's encoded constructor for why.
   */
  public TSNE(DataFrame data, String encoded_feature_columns) {
    this(datamungeJNI.new_TSNE__SWIG_23(DataFrame.getCPtr(data), data, encoded_feature_columns), true);
  }

  public SVector feature_names() {
    return new SVector(datamungeJNI.TSNE_feature_names(swigCPtr, this), true);
  }

  public long observations() {
    return datamungeJNI.TSNE_observations(swigCPtr, this);
  }

  public long n_components() {
    return datamungeJNI.TSNE_n_components(swigCPtr, this);
  }

  public SizeVector kept_row_indices() {
    return new SizeVector(datamungeJNI.TSNE_kept_row_indices(swigCPtr, this), true);
  }

  /**
   *  The achieved perplexity for each fitted point after the per-point binary search --<br>
   *         should be close to the constructor's perplexity argument if calibration converged.
   */
  public DVector achieved_perplexity() {
    return new DVector(datamungeJNI.TSNE_achieved_perplexity(swigCPtr, this), true);
  }

  public DVector dimension(long index) {
    return new DVector(datamungeJNI.TSNE_dimension(swigCPtr, this, index), true);
  }

  public DataFrame embedding_frame() {
    long cPtr = datamungeJNI.TSNE_embedding_frame(swigCPtr, this);
    return (cPtr == 0) ? null : new DataFrame(cPtr, false);
  }

  public String summary() {
    return datamungeJNI.TSNE_summary(swigCPtr, this);
  }

  public void print_summary() {
    datamungeJNI.TSNE_print_summary(swigCPtr, this);
  }

  public RPlot plot_embedding(long dimension_x, long dimension_y) {
    return new RPlot(datamungeJNI.TSNE_plot_embedding__SWIG_0(swigCPtr, this, dimension_x, dimension_y), true);
  }

  public RPlot plot_embedding(long dimension_x) {
    return new RPlot(datamungeJNI.TSNE_plot_embedding__SWIG_1(swigCPtr, this, dimension_x), true);
  }

  public RPlot plot_embedding() {
    return new RPlot(datamungeJNI.TSNE_plot_embedding__SWIG_2(swigCPtr, this), true);
  }

  public RPlot plot_embedding_grouped(SVector group_labels, long dimension_x, long dimension_y) {
    return new RPlot(datamungeJNI.TSNE_plot_embedding_grouped__SWIG_0(swigCPtr, this, SVector.getCPtr(group_labels), group_labels, dimension_x, dimension_y), true);
  }

  public RPlot plot_embedding_grouped(SVector group_labels, long dimension_x) {
    return new RPlot(datamungeJNI.TSNE_plot_embedding_grouped__SWIG_1(swigCPtr, this, SVector.getCPtr(group_labels), group_labels, dimension_x), true);
  }

  public RPlot plot_embedding_grouped(SVector group_labels) {
    return new RPlot(datamungeJNI.TSNE_plot_embedding_grouped__SWIG_2(swigCPtr, this, SVector.getCPtr(group_labels), group_labels), true);
  }

}
